import { useId } from 'react';
import { AUDIENCES, FIELD_TYPES, SERVICE_TEMPLATES, createDefinition, type ServiceDefinition, type DefinitionField, type TemplateId } from '@workspace/service-definition';
import './services.css';
export function DefinitionEditor({value,onChange,language='ar'}:{value:ServiceDefinition|null|undefined;onChange:(d:ServiceDefinition|null)=>void;language?:'ar'|'en'}) {
 const uid=useId(),w=(a:string,e:string)=>language==='ar'?a:e;
 if(!value)return <div className="sv-editor-section"><p className="sv-help">{w('هذه خدمة قديمة بدون تعريف مرن. بياناتها وحجوزاتها محفوظة.','This legacy service has no flexible definition. Its data and bookings are preserved.')}</p><button type="button" className="sv-button" onClick={()=>onChange(createDefinition('custom',language))}>{w('أضف تصميمًا وحقول حجز','Add a design and booking fields')}</button></div>;
 const d=value,change=(patch:Partial<ServiceDefinition>)=>onChange({...d,...patch});
 const fieldChange=(index:number,patch:Partial<DefinitionField>)=>change({intakeFields:d.intakeFields.map((f,i)=>i===index?{...f,...patch}:f)});
 const audiences:Record<string,string>={unspecified:w('غير محدد','Not specified'),all:w('للجميع','All'),men:w('رجال','Men'),women:w('نساء','Women'),children:w('أطفال','Children')};
 const fieldLabels:Record<string,string>={short_text:w('نص قصير','Short text'),long_text:w('نص طويل','Long text'),select:w('اختيار واحد','Single choice'),number:w('رقم','Number'),boolean:w('نعم / لا','Yes / No')};
 return <div className="sv-definition-editor">
  <div className="sv-field-grid"><label className="sv-field">{w('قالب العرض','Presentation template')}<select value={d.template} onChange={e=>{const template=e.target.value as TemplateId,preset=SERVICE_TEMPLATES.find(t=>t.id===template)!;change({template,section:SERVICE_TEMPLATES.some(t=>Object.values(t.section).includes(d.section))?preset.section[language]:d.section});}}>{SERVICE_TEMPLATES.map(t=><option key={t.id} value={t.id}>{t.label[language]}</option>)}</select></label>
   <label className="sv-field">{w('قسم الخدمات','Service section')}<input maxLength={80} value={d.section} onChange={e=>change({section:e.target.value})}/></label>
   <label className="sv-field">{w('الفئة المستهدفة','Audience')}<select value={d.audience} onChange={e=>change({audience:e.target.value as ServiceDefinition['audience']})}>{AUDIENCES.map(a=><option key={a} value={a}>{audiences[a]}</option>)}</select></label>
   <label className="sv-field">{w('المنطقة، عند الحاجة','Area, when relevant')}<input maxLength={100} value={d.bodyArea??''} onChange={e=>change({bodyArea:e.target.value.trim()?e.target.value:null})}/></label></div>
  <label className="sv-field">{w('وصف إداري مختصر للخدمة','Short administrative description')}<textarea maxLength={500} value={d.description??''} onChange={e=>change({description:e.target.value.trim()?e.target.value:null})}/></label>
  <label className="sv-field">{w('تأكيد النطاق الطبي','Medical scope confirmation')}<select value={d.medicalScope} onChange={e=>change({medicalScope:e.target.value as ServiceDefinition['medicalScope']})}><option value="needs_review">{w('تحتاج مراجعة المدير','Manager review needed')}</option><option value="medical">{w('أؤكد أنها خدمة طبية تقدّمها عيادتنا','I confirm our clinic provides this medical service')}</option><option value="out_of_scope">{w('خارج الخدمات الطبية — غير قابلة للاعتماد','Outside medical scope — cannot save')}</option></select></label>
  {!!d.unsupportedCapabilities.length&&<div className="sv-warning"><strong>{w('طلبات لا ينفّذها النظام تلقائيًا','Requests not implemented automatically')}</strong>{d.unsupportedCapabilities.map((cap,i)=><p key={i}>{cap} <button type="button" className="sv-link" onClick={()=>{if(window.confirm(w('هذا يحذف الطلب من نطاق الخدمة فقط؛ لا ينفّذه. هل تتابع؟','This removes the request from scope; it does not implement it. Continue?')))change({unsupportedCapabilities:d.unsupportedCapabilities.filter((_,n)=>n!==i)});}}>{w('استبعاد الطلب','Exclude request')}</button></p>)}</div>}
  <section className="sv-editor-section"><div className="sv-row"><h4>{w('حقول استمارة الحجز','Booking intake fields')}</h4><span className="sv-help">{d.intakeFields.length}/12</span></div><p className="sv-help">{w('أضف فقط ما تحتاجه العيادة للحجز. لا تدخل بروتوكولات علاجية أو كلمات مرور.','Only request information needed for booking. No treatment protocols or passwords.')}</p>
   {d.intakeFields.map((field,i)=><fieldset className="sv-field-row" key={field.id}><legend>{w('حقل','Field')} {i+1}</legend><div className="sv-field-grid"><label className="sv-field" htmlFor={`${uid}-${field.id}`}>{w('السؤال','Question')}<input id={`${uid}-${field.id}`} maxLength={100} value={field.label} onChange={e=>fieldChange(i,{label:e.target.value})}/></label><label className="sv-field">{w('نوع الإجابة','Answer type')}<select value={field.type} onChange={e=>fieldChange(i,{type:e.target.value as DefinitionField['type'],options:e.target.value==='select'?field.options:[]})}>{FIELD_TYPES.map(t=><option key={t} value={t}>{fieldLabels[t]}</option>)}</select></label></div>
    {field.type==='select'&&<label className="sv-field">{w('الخيارات، كل خيار بسطر (2–20)','Options, one per line (2–20)')}<textarea value={field.options.join('\n')} onChange={e=>fieldChange(i,{options:e.target.value.split('\n')})}/></label>}
    <label className="sv-field">{w('توضيح اختياري','Optional help')}<input maxLength={240} value={field.help??''} onChange={e=>fieldChange(i,{help:e.target.value.trim()?e.target.value:null})}/></label><div className="sv-row"><label className="sv-check"><input type="checkbox" checked={field.required} onChange={e=>fieldChange(i,{required:e.target.checked})}/>{w('إجابة مطلوبة','Required answer')}</label><button type="button" className="sv-link sv-danger" onClick={()=>change({intakeFields:d.intakeFields.filter((_,n)=>n!==i)})}>{w('حذف الحقل','Remove field')}</button></div>
   </fieldset>)}
   <button type="button" className="sv-button" disabled={d.intakeFields.length>=12} onClick={()=>{const random=Array.from(crypto.getRandomValues(new Uint8Array(6)),b=>b.toString(16).padStart(2,'0')).join('');change({intakeFields:[...d.intakeFields,{id:`field_${random}`,label:'',type:'short_text',required:false,help:null,options:[]}]});}}>{w('+ إضافة حقل','+ Add field')}</button>
  </section>
 </div>;
}
