import { CategoryField } from '../category-field';
import { useEffect, useState } from 'react';
import { SERVICE_TEMPLATES, createDefinition, parseServiceDefinition, ServiceDefinitionError, type TemplateId, type IntakeAnswers } from '@workspace/service-definition';
import type { Session, Draft, ServiceDraft, ServiceOptions, Review } from '../concierge/contract';
import { createRequestId } from '../concierge/api';
import { ServiceCard, ServiceGlyph, missingLabel } from './service-card';
import { DefinitionEditor } from './definition-editor';
import { IntakeFields } from './intake-fields';
type Language='ar'|'en';
const emptyOptions:ServiceOptions={branches:[],employees:[],rooms:[]};
function newService(template:TemplateId,language:Language):ServiceDraft {
 return {key:`service_${createRequestId().replace(/-/g,'').slice(0,20)}`,name:null,nameLang:language,branchKey:null,branchScope:null,durationMinutes:null,price:null,currency:'JOD',category:null,requiresRoom:null,employeeIds:[],roomIds:[],definition:createDefinition(template,language)};
}
function ServiceEditor({initial,options,language,busy,onCancel,onSave}:{initial:ServiceDraft;options:ServiceOptions;language:Language;busy:boolean;onCancel:()=>void;onSave:(s:ServiceDraft)=>Promise<void>}) {
 const [service,setService]=useState<ServiceDraft>(()=>({...structuredClone(initial),currency:'JOD'})),[error,setError]=useState(''),[answers,setAnswers]=useState<IntakeAnswers>({});
 const w=(a:string,e:string)=>language==='ar'?a:e,change=(p:Partial<ServiceDraft>)=>setService(s=>({...s,...p}));
 const branchId=options.branches.find(b=>b.key===service.branchKey)?.id??null;
 const compatible=(branch:number|null)=>service.branchScope!=='branch'||branch===null||branch===branchId;
 const employees=options.employees.filter(e=>compatible(e.branchId)),rooms=options.rooms.filter(r=>r.status==='available'&&compatible(r.branchId));
 const save=async()=>{setError('');try{const definition=parseServiceDefinition(service.definition);await onSave({...service,currency:'JOD',definition,name:service.name?.trim()||null,nameLang:/[\u0600-\u06ff]/u.test(service.name??'')?'ar':language});}catch(e){setError(e instanceof ServiceDefinitionError?w('راجع تعريف الخدمة: ','Check service definition: ')+e.issues.map(i=>i.field).join(' · '):w('لم تُحفظ التعديلات. راجع رسالة النظام وأعد المحاولة.','Changes were not saved. Check the system message and retry.'));}};
 return <section className="sv-editor" data-testid="wizard-service-editor">
  <div className="sv-editor-heading"><div><p className="sv-eyebrow">{w('التفاصيل التي تصنع الفرق','DETAILS THAT MATTER')}</p><h3>{w('صمّم خدمتك','Shape your service')}</h3></div><button className="sv-link" type="button" disabled={busy} onClick={onCancel}>{w('رجوع','Back')}</button></div>
  <fieldset disabled={busy} className="sv-editor-fields">
   <label className="sv-field">{w('اسم الخدمة كما تقدّمها العيادة','Service name as offered by the clinic')}<input maxLength={120} value={service.name??''} onChange={e=>change({name:e.target.value||null})} placeholder={w('مثال: ليزر اللحية للرجال','Example: Beard laser for men')} data-testid="wizard-service-name"/></label>
   <div className="sv-field-grid"><label className="sv-field">{w('مدة الموعد بالدقائق','Duration in minutes')}<input type="number" min={1} max={1440} step={1} value={service.durationMinutes??''} placeholder={w('غير محددة','Not specified')} onChange={e=>change({durationMinutes:e.target.value===''?null:Number(e.target.value)})}/></label><label className="sv-field">{w('السعر','Price')}<input type="number" min={0} max={999999999.999} step="0.001" value={service.price??''} placeholder={w('غير محدد','Not specified')} onChange={e=>change({price:e.target.value||null})}/></label>
   <p className="sv-help">{w('الأسعار بالدينار الأردني (JOD).','Prices are in Jordanian dinars (JOD).')}</p>
   <label className="sv-field">{w('هل تحتاج الخدمة إلى غرفة؟','Does this service require a room?')}<select value={service.requiresRoom===null?'':String(service.requiresRoom)} onChange={e=>change({requiresRoom:e.target.value===''?null:e.target.value==='true',...(e.target.value==='false'?{roomIds:[]}: {})})}><option value="">{w('لم يُحدد بعد','Not specified')}</option><option value="true">{w('نعم','Yes')}</option><option value="false">{w('لا','No')}</option></select></label>
   <label className="sv-field">{w('نطاق الخدمة','Service scope')}<select value={service.branchScope??''} onChange={e=>change({branchScope:e.target.value as ServiceDraft['branchScope']||null,branchKey:null,employeeIds:[],roomIds:[]})}><option value="">{w('لم يُحدد بعد','Not specified')}</option><option value="all">{w('كل فروع العيادة','All clinic branches')}</option><option value="branch">{w('فرع محدد','One branch')}</option></select></label>
   {service.branchScope==='branch'&&<label className="sv-field">{w('الفرع','Branch')}<select value={service.branchKey??''} onChange={e=>change({branchKey:e.target.value||null,employeeIds:[],roomIds:[]})}><option value="">{w('اختر الفرع','Select branch')}</option>{options.branches.map(b=><option key={b.id} value={b.key}>{b.name}</option>)}</select></label>}</div>
   <details className="sv-assignment"><summary>{w('مقدّمو الخدمة والغرف','Service providers and rooms')}</summary><p className="sv-help">{w('لن يظهر وقت متاح للحجز بدون مقدّم خدمة وجدول دوام صالح، وغرفة متاحة إذا كانت مطلوبة.','Booking availability requires an assigned provider, valid working hours and an available room when required.')}</p><fieldset className="sv-pickers"><legend>{w('مقدّمو الخدمة','Service providers')}</legend>{employees.length?employees.map(e=><label className="sv-check" key={e.id}><input type="checkbox" checked={service.employeeIds?.includes(e.id)??false} onChange={event=>change({employeeIds:event.target.checked?[...(service.employeeIds??[]),e.id]:(service.employeeIds??[]).filter(id=>id!==e.id)})}/>{e.name}</label>):<p className="sv-help">{w('لا يوجد موظفون متاحون ضمن صلاحياتك ونطاق الفرع. أكملهم من قسم الموظفين.','No employees available for this scope/access. Configure them in Employees.')}</p>}</fieldset>
    {service.requiresRoom&&<fieldset className="sv-pickers"><legend>{w('الغرف المتاحة','Available rooms')}</legend>{rooms.length?rooms.map(r=><label className="sv-check" key={r.id}><input type="checkbox" checked={service.roomIds?.includes(r.id)??false} onChange={e=>change({roomIds:e.target.checked?[...(service.roomIds??[]),r.id]:(service.roomIds??[]).filter(id=>id!==r.id)})}/>{r.name}</label>):<p className="sv-help">{w('أكمل الغرف وربطها بالخدمات من قسم الغرف.','Configure and link service rooms in Rooms.')}</p>}</fieldset>}
   </details>
   <CategoryField label={w('التصنيف','Category')} value={service.category??''} options={options.categories??[]} language={language} onChange={value=>change({category:value.trim()||null})} testId="wizard-service-category"/>
   <DefinitionEditor value={service.definition} onChange={definition=>{change({definition});setAnswers({});}} language={language}/>
   <details className="sv-preview-details" open><summary>{w('معاينة فورية للتصميم','Live design preview')}</summary><ServiceCard service={service} language={language} draft/><IntakeFields definition={service.definition} answers={answers} onChange={setAnswers} language={language} preview/></details>
   {error&&<p className="sv-error" role="alert">{error}</p>}
   <div className="sv-editor-actions"><button className="sv-button sv-primary" type="button" onClick={()=>void save()} data-testid="wizard-save-service">{busy?w('جارٍ الحفظ…','Saving…'):w('حفظ في المسودة','Save to draft')}</button><button type="button" className="sv-button" onClick={onCancel}>{w('إلغاء التعديل','Cancel edits')}</button></div>
   <p className="sv-help">{w('يحفظ هذا التعديل في المسودة فقط. راجع الإعداد كاملًا قبل إضافة الخدمات إلى نظام المواعيد.','This saves only the draft. Review setup before adding services to your appointment system.')}</p>
  </fieldset>
 </section>;
}
export type ServiceWizardPanelProps={session:Session;language:Language;options:ServiceOptions|null;optionsError:boolean;busy:boolean;previews:ServiceDraft[];review:Review|null;onSave:(draft:Draft)=>Promise<void>;onAccept:(key:string)=>Promise<void>;onReview:()=>void;onBack:()=>void;onApply:()=>Promise<void>;onRetryOptions:()=>void;onEditing:(editing:boolean)=>void};
export function ServiceWizardPanel(p:ServiceWizardPanelProps){
 const {session,language,previews,review}=p,w=(a:string,e:string)=>language==='ar'?a:e;
 const [editing,setEditing]=useState<ServiceDraft|null>(null),[choosing,setChoosing]=useState(false),[confirmed,setConfirmed]=useState(false),[operationError,setOperationError]=useState('');
 const options=p.options??emptyOptions;
 useEffect(()=>{setConfirmed(false);},[review?.revision,session.revision]);
 useEffect(()=>{p.onEditing(!!editing);return()=>p.onEditing(false);},[!!editing]);
 const perform=async(action:()=>Promise<void>)=>{setOperationError('');try{await action();}catch{setOperationError(w('لم يكتمل الطلب. راجع رسالة النظام قبل إعادة المحاولة.','The request did not complete. Check the system message before retrying.'));}};
 const remove=(key:string)=>{if(window.confirm(w('حذف هذه الخدمة من مسودة الإعداد؟ لا يمس أي موعد موجود.','Remove this service from the setup draft? Existing appointments are not affected.')))void perform(()=>p.onSave({...session.draft,services:session.draft.services.filter(s=>s.key!==key)}));};
 if(editing)return <ServiceEditor key={editing.key} initial={editing} options={options} language={language} busy={p.busy} onCancel={()=>setEditing(null)} onSave={async s=>{const exists=session.draft.services.some(v=>v.key===s.key);await p.onSave({...session.draft,services:exists?session.draft.services.map(v=>v.key===s.key?s:v):[...session.draft.services,s]});setEditing(null);}}/>;
 const merged=session.draft.services.map(s=>previews.find(p=>p.key===s.key)??s);
 for(const s of previews)if(!merged.some(v=>v.key===s.key))merged.push(s);
 const sections=Array.from(new Set(merged.map(s=>s.definition?.section||w('خدمات العيادة','Clinic services'))));
 return <div className="sv-wizard" data-testid="service-wizard-panel">
  <header className="sv-wizard-heading"><div><p className="sv-eyebrow">{w('عيادتك، بطريقتها','YOUR CLINIC, YOUR WAY')}</p><h2>{review?w('مراجعة إعداد العيادة','Review clinic setup'):w('خدمات تتشكّل أمامك','Your services, taking shape')}</h2><p>{w('نضيف ما تقدّمه عيادتك فقط. باقي أقسام النظام تبقى كما هي.','Only what your clinic offers. The rest of your system stays unchanged.')}</p></div><span className="sv-step-badge">{review?'02':'01'}<small>/ 02</small></span></header>
  <div className="sv-wizard-meta"><span className="sv-live-dot"/><span>{previews.length?w('معاينة مؤقتة — لم تُحفظ بعد','Temporary preview — not saved yet'):w('مسودة محفوظة، بانتظار اعتمادك','Saved draft, awaiting your approval')}</span><strong>{session.draft.services.length} {w('خدمات','services')}</strong></div>
  {p.optionsError&&<p className="sv-warning">{w('تعذّر تحميل بيانات الفروع والموظفين والغرف.','Could not load branches, employees and rooms.')} <button className="sv-link" type="button" onClick={p.onRetryOptions}>{w('إعادة المحاولة','Retry')}</button></p>}
  {operationError&&<p className="sv-error" role="alert">{operationError}</p>}
  {!review&&<div className="sv-row"><p className="sv-help">{w('خدمات طبية جاهزة للتخصيص، أو خدمة جديدة بالكامل.','Adapt a medical template, or define a new service.')}</p><button type="button" className="sv-button sv-primary" disabled={p.busy||!p.options} onClick={()=>setChoosing(!choosing)} data-testid="wizard-add-service">{w('+ إضافة خدمة','+ Add service')}</button></div>}
  {choosing&&!review&&<div className="sv-template-grid" data-testid="wizard-template-picker">{SERVICE_TEMPLATES.map(t=><button type="button" key={t.id} onClick={()=>{setEditing(newService(t.id,language));setChoosing(false);}} className="sv-template" disabled={p.busy}><ServiceGlyph template={t.id}/><strong>{t.label[language]}</strong><span>{t.hint[language]}</span></button>)}</div>}
  {!merged.length&&!choosing&&<div className="sv-empty"><span className="sv-empty-glyph"><ServiceGlyph template="custom"/></span><h3>{w('لنبدأ بخدمة واحدة','Start with one service')}</h3><p>{w('احكِ للمساعد: «عندي ليزر للرجال، اللحية فقط». أو أضفها يدويًا من القوالب.','Tell the assistant: “Beard laser for men only.” Or add it manually using a template.')}</p><span>{w('لا أسعار مفترضة. لا خدمات إضافية.','No assumed prices. No extra services.')}</span></div>}
  {sections.map(section=><section key={section} className="sv-section"><div className="sv-section-heading"><h3>{section}</h3><span>{merged.filter(s=>(s.definition?.section||w('خدمات العيادة','Clinic services'))===section).length}</span></div><div className="sv-grid">{merged.filter(s=>(s.definition?.section||w('خدمات العيادة','Clinic services'))===section).map(s=><ServiceCard key={s.key} service={s} language={language} draft pending={previews.some(p=>p.key===s.key)} branch={s.branchScope==='all'?w('كل الفروع','All branches'):options.branches.find(b=>b.key===s.branchKey)?.name} footer={<><div className="sv-row"><span className="sv-source">{session.serviceSources?.[s.key]?.kind==='public'?w('من رابط، باختيار المدير','From link, selected by manager'):session.serviceSources?.[s.key]?.kind==='conversation'?w('من المحادثة','From conversation'):w('إدخال يدوي','Manual entry')}</span>{!review&&<span className="sv-actions"><button className="sv-link" type="button" disabled={p.busy||!!previews.length} onClick={()=>setEditing(s)}>{w('تعديل','Edit')}</button><button className="sv-link sv-danger" type="button" disabled={p.busy||!!previews.length} onClick={()=>remove(s.key)}>{w('حذف','Remove')}</button></span>}</div><label className="sv-check"><input type="checkbox" checked={!!s.followUpEnabled} disabled={p.busy||!!previews.length} onChange={e=>void perform(()=>p.onSave({...session.draft,services:session.draft.services.map(row=>row.key===s.key?{...row,followUpEnabled:e.target.checked}:row)}))}/>{w('رتوش / موعد متابعة — السعر الافتراضي 0 JOD، ويمكن تغييره لكل موعد','Retouch / follow-up appointment — default 0 JOD, editable per appointment')}</label>{review&&s.definition?.intakeFields.length?<ul className="sv-review-fields">{s.definition.intakeFields.map(f=><li key={f.id}>{f.label}{f.required?w(' (مطلوب)',' (required)'):''}</li>)}</ul>:null}{review&&(!s.employeeIds?.length||s.requiresRoom&&!s.roomIds?.length)&&<p className="sv-help">{w('تحتاج استكمال ربط الموظفين أو الغرف قبل ظهور مواعيد متاحة.','Provider/room assignment must be completed before appointments become available.')}</p>}</>}/>)}</div></section>)}
  {!review&&!!session.serviceSuggestions?.length&&<section className="sv-suggestions"><h3>{w('مذكورة في الروابط — لم تُضف تلقائيًا','Mentioned in links — not added automatically')}</h3><p className="sv-help">{w('اختر فقط الخدمات التي تقدّمها عيادتك الآن، ثم راجع تعريفها.','Select only services currently offered, then review their definitions.')}</p>{session.serviceSuggestions.map(s=><div className="sv-suggestion" key={s.key}><div><strong>{s.name}</strong>{s.detail&&<p>{s.detail}</p>}{s.sourceUrl&&<a href={s.sourceUrl} rel="noopener noreferrer" target="_blank">{w('المصدر العام','Public source')}</a>}</div><button className="sv-button" type="button" disabled={p.busy} onClick={()=>void perform(()=>p.onAccept(s.key))}>{w('نقدّم هذه الخدمة','We offer this')}</button></div>)}</section>}
  {review?<section className="sv-approval"><h3>{w('احفظ الإعداد بعد مراجعتك','Save setup after your review')}</h3>{!!review.issues.length&&<div className="sv-warning" role="alert"><strong>{w('أكمل النقاط التالية أولًا:','Complete these items first:')}</strong><ul>{review.issues.map((i,n)=><li key={n}>{session.draft.services.find(s=>s.key===i.key)?.name??i.key}: {missingLabel(i.field,language)} <small>({i.code})</small></li>)}</ul></div>}<label className="sv-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} disabled={p.busy}/>{w('راجعت الهوية والخدمات وبياناتها، وأوافق على حفظ هذه التغييرات داخل نظام العيادة.','I reviewed identity and service details, and approve saving these changes inside the clinic system.')}</label><div className="sv-row"><button className="sv-button" type="button" disabled={p.busy} onClick={p.onBack}>{w('رجوع للتعديل','Back to editing')}</button><button className="sv-button sv-primary" type="button" disabled={p.busy||!confirmed||!!review.issues.length||review.revision!==session.revision} onClick={()=>void perform(p.onApply)} data-testid="wizard-save-setup">{w('حفظ إعداد العيادة','Save clinic setup')}</button></div></section>:(!!merged.length||!!session.workspace?.dirty)&&<div className="sv-continue"><p>{w('التغييرات مسودة محفوظة حتى تحفظ إعداد العيادة. لا توجد خطوة نشر عام.','Changes stay in your saved draft until you save clinic setup. There is no public publishing step.')}</p><button className="sv-button sv-primary" type="button" disabled={p.busy||!!previews.length} onClick={p.onReview} data-testid="wizard-review">{w('مراجعة واعتماد ←','Review and approve →')}</button></div>}
 </div>;
}
