import {WORKSPACE_FIELDS,parseWorkspaceProfile,validWorkspaceLogo,WorkspaceValidationError,JORMALL_PRIMARY,JORMALL_ACCENT,type WorkspaceDraft,type WorkspaceProfile,type WorkspaceField} from '@workspace/service-definition';
import {logoPalette} from '../concierge/branding';
import {workspaceSurface,type WorkspaceSection} from './surface';
import './workspace.css';
import { createPhoneInput } from '../phone-input';
export type IdentityPanelProps={draft:WorkspaceDraft;revision:number;language:'ar'|'en';busy:boolean;review:boolean;sections:WorkspaceSection[];onSave:(profile:WorkspaceProfile)=>Promise<void>;onFact:(id:string,accept:boolean)=>Promise<void>;onReload:()=>Promise<void>;onDirty:(dirty:boolean)=>void};
const labels:Record<WorkspaceField,[string,string]>={nameAr:['اسم العيادة بالعربية','Clinic name in Arabic'],nameEn:['اسم العيادة بالإنجليزية','Clinic name in English'],subtitleAr:['وصف مختصر بالعربية (اختياري)','Short description in Arabic (optional)'],subtitleEn:['وصف مختصر بالإنجليزية (اختياري)','Short description in English (optional)'],phone:['هاتف العيادة','Clinic phone'],email:['بريد العيادة','Clinic email'],address:['عنوان العيادة','Clinic address'],website:['رابط مرجعي للعيادة (اختياري)','Reference clinic URL (optional)'],logoDataUrl:['شعار العيادة','Clinic logo'],primaryColor:['اللون الرئيسي','Primary color'],accentColor:['اللون الثانوي','Accent color']};
function el<K extends keyof HTMLElementTagNameMap>(tag:K,cls:string,text?:string){const e=document.createElement(tag);e.className=cls;if(text)e.textContent=text;return e;}
/** DOM component embedded in the original concierge, with a scoped preview and no external runtime. */
export class WorkspaceIdentityPanel {
 private props:IdentityPanelProps;private profile:WorkspaceProfile;private dirty=false;private mobile=false;private expanded=false;private error='';private saving=false;private preview=el('div','cw-preview');
 constructor(private host:HTMLElement,props:IdentityPanelProps){this.props=props;this.profile=structuredClone(props.draft.profile);this.render();}
 update(props:IdentityPanelProps){this.props=props;if(!this.dirty&&!this.saving){this.profile=structuredClone(props.draft.profile);this.render();}else{for(const b of this.host.querySelectorAll<HTMLButtonElement>('button'))b.disabled=props.busy||this.saving;}}
 dispose(){this.host.replaceChildren();this.dirty=false;}
 private w(a:string,e:string){return this.props.language==='ar'?a:e;}
 private title(f:WorkspaceField){return labels[f][this.props.language==='ar'?0:1];}
 private markDirty(){if(!this.dirty){this.dirty=true;this.props.onDirty(true);}this.updatePreview();const status=this.host.querySelector('.cw-save-status');if(status)status.textContent=this.w('لديك تعديلات محلية غير محفوظة.','You have unsaved local edits.');}
 private updatePreview(){try{this.preview.replaceChildren(workspaceSurface(parseWorkspaceProfile(this.profile),this.props.language,this.props.sections,{preview:true}));}catch{/* Incomplete edits never replace the last valid preview. */}this.preview.classList.toggle('cw-preview-mobile',this.mobile);}
 private button(text:string,action:()=>void,cls='cw-button'){const b=el('button',cls,text);b.type='button';b.disabled=this.props.busy||this.saving;b.onclick=action;return b;}
 private async operation(action:()=>Promise<void>){if(this.props.busy||this.saving)return;this.saving=true;this.error='';this.render();try{await action();}catch{this.error=this.w('لم تُحفظ التغييرات. راجع رسالة النظام ثم أعد المحاولة؛ بياناتك ما زالت هنا.','Changes were not saved. Check the system message and retry; your edits are still here.');}finally{this.saving=false;if(!this.dirty)this.profile=structuredClone(this.props.draft.profile);this.render();}}
 private render(){
  const p=this.props,ar=p.language==='ar',box=el('section','cw-panel');box.dataset.testid='workspace-identity-panel';box.lang=p.language;box.dir=ar?'rtl':'ltr';
  const top=el('div','cw-panel-heading'),text=el('div','');text.append(el('p','cw-eyebrow',this.w('مصمّم لعيادتك','MADE FOR YOUR CLINIC')),el('h2','',this.w('الهوية ومساحة العمل','Identity & workspace')));top.append(text);
  if(!p.review)top.append(this.button(this.expanded?this.w('إغلاق المحرر','Close editor'):this.w('تعديل الهوية','Edit identity'),()=>{if(this.dirty&&!window.confirm(this.w('لديك تعديل غير محفوظ. اترك المحرر مفتوحًا للحفظ، أو اضغط موافق لإلغاء التعديل.','Unsaved changes. Cancel to keep editing, or confirm to discard.')))return;if(this.dirty){this.dirty=false;this.profile=structuredClone(p.draft.profile);p.onDirty(false);}this.expanded=!this.expanded;this.render();}));box.append(top);
  box.append(el('p','cw-help',this.w('الاسم والشعار والألوان تظهر داخل نظامك الحالي. الخدمات فقط تنشئ أقسامًا مخصصة؛ الأقسام الأساسية تبقى ثابتة.','Name, logo and colors appear inside your existing system. Only your services create custom sections; core navigation stays fixed.')));
  const toolbar=el('div','cw-preview-tools'),desktop=this.button(this.w('كمبيوتر','Desktop'),()=>{this.mobile=false;this.updatePreview();desktop.setAttribute('aria-pressed','true');mobile.setAttribute('aria-pressed','false');}),mobile=this.button(this.w('هاتف','Mobile'),()=>{this.mobile=true;this.updatePreview();desktop.setAttribute('aria-pressed','false');mobile.setAttribute('aria-pressed','true');});desktop.setAttribute('aria-pressed',String(!this.mobile));mobile.setAttribute('aria-pressed',String(this.mobile));toolbar.append(desktop,mobile,el('span','cw-help',this.w('معاينة غير عامة','Private preview')));box.append(toolbar);this.preview=el('div','cw-preview');this.updatePreview();box.append(this.preview);
  const suggested=Object.values(p.draft.sources).some(s=>s?.kind==='suggestion');if(suggested)box.append(el('p','cw-help',this.w('الألوان الافتراضية اقتراح تصميم، وليست ألوانًا مستخرجة من عيادتك.','Default colors are design suggestions, not extracted clinic branding.')));
  if(this.expanded&&!p.review){
   const form=el('form','cw-form');form.noValidate=true;const grid=el('div','cw-form-grid');
   for(const f of WORKSPACE_FIELDS){if(f==='logoDataUrl')continue;if(f==='phone'){grid.append(createPhoneInput({value:this.profile.phone??'',label:this.title(f),language:p.language,testId:'workspace-phone',disabled:p.busy||this.saving,onChange:value=>{this.profile.phone=value||null;this.markDirty();}}).node);continue;}const label=el('label','cw-field',this.title(f)),input=el('input','');input.name=f;input.dataset.testid=`workspace-${f}`;input.value=this.profile[f]??'';input.maxLength=f==='address'?400:f==='website'?500:f.startsWith('subtitle')?240:120;input.disabled=p.busy||this.saving;
    input.type=f.endsWith('Color')?'color':f==='email'?'email':f==='website'?'url':'text';if(f.endsWith('En')||['email','website'].includes(f))input.dir='ltr';else if(f.endsWith('Ar'))input.dir='rtl';
    input.oninput=()=>{this.profile[f]=input.value.trim()||null;this.markDirty();};label.append(input);
    const src=p.draft.sources[f];if(src){const line=el('small','cw-source',src.kind==='public'?this.w('من مصدر عام، أكّده المدير','Public source, owner confirmed'):src.kind==='owner'?this.w('إدخال المدير','Owner input'):src.kind==='suggestion'?this.w('اقتراح قابل للتعديل','Editable suggestion'):this.w('من حساب العيادة','Existing clinic account'));if(src.url){const a=el('a','',this.w(' المصدر',' Source'));a.href=src.url;a.target='_blank';a.rel='noopener noreferrer';line.append(a);}label.append(line);}grid.append(label);
   }form.append(grid);
   const logo=el('label','cw-field',this.title('logoDataUrl')),upload=el('input','');upload.type='file';upload.accept='image/png,image/jpeg,image/webp';upload.dataset.testid='workspace-logo-upload';upload.disabled=p.busy||this.saving;
   upload.onchange=async()=>{const file=upload.files?.[0];if(!file)return;try{if(file.size>90000||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error();const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error());reader.readAsDataURL(file);});if(!validWorkspaceLogo(data))throw Error();const img=new Image();img.src=data;await img.decode();if(img.naturalWidth*img.naturalHeight>16000000)throw Error();const palette=logoPalette(img);this.profile.logoDataUrl=data;if(palette[0])this.profile.primaryColor=palette[0];if(palette[1])this.profile.accentColor=palette[1];this.markDirty();this.error='';this.render();}catch{this.error=this.w('استخدم شعار PNG أو JPEG أو WebP بحجم لا يتجاوز 90 KB.','Use a PNG, JPEG or WebP logo no larger than 90 KB.');this.render();}};logo.append(upload,el('small','cw-help',this.w('حتى 90 KB. لا ملفات SVG أو HTML.','Up to 90 KB. No SVG or HTML files.')));form.append(logo);
   if(this.profile.logoDataUrl)form.append(this.button(this.w('إزالة الشعار','Remove logo'),()=>{this.profile.logoDataUrl=null;this.profile.primaryColor=JORMALL_PRIMARY;this.profile.accentColor=JORMALL_ACCENT;this.markDirty();this.render();}));
   const actions=el('div','cw-form-actions'),save=el('button','cw-button cw-primary',this.saving?this.w('جارٍ الحفظ…','Saving…'):this.w('حفظ الهوية في الإعداد','Save identity to setup'));save.type='submit';save.disabled=p.busy||this.saving;save.dataset.testid='workspace-save-identity';actions.append(save,this.button(this.w('إلغاء التعديلات','Discard edits'),()=>{this.profile=structuredClone(p.draft.profile);this.dirty=false;p.onDirty(false);this.error='';this.render();}));form.append(actions);
   form.onsubmit=e=>{e.preventDefault();let profile:WorkspaceProfile;try{profile=parseWorkspaceProfile(this.profile);}catch(error){this.error=this.w('راجع الحقول: ','Check fields: ')+(error instanceof WorkspaceValidationError?error.fields.map(f=>labels[f as WorkspaceField]?this.title(f as WorkspaceField):this.w('اسم العيادة مطلوب بإحدى اللغتين','A clinic name is required in either language')).join('، '):'');this.render();return;}void this.operation(async()=>{await p.onSave(profile);this.dirty=false;p.onDirty(false);this.expanded=false;});};box.append(form);
  }
  if(!p.review&&p.draft.proposals.length){const proposals=el('section','cw-proposals');proposals.append(el('h3','',this.w('حقائق من الروابط تحتاج قرارك','Source facts awaiting your decision')),el('p','cw-help',this.w('تأكيد هوية العيادة لا يستبدل بياناتك. اختر كل حقيقة أو تجاهلها.','Identity confirmation never overwrites your data. Select or dismiss each fact.')));
   for(const fact of p.draft.proposals){const card=el('article','cw-proposal');card.append(el('strong','',this.title(fact.field)));if(fact.field==='logoDataUrl'&&validWorkspaceLogo(fact.value)){const img=el('img','cw-proposal-logo');img.src=fact.value;img.alt=this.w('الشعار المقترح من المصدر','Proposed source logo');card.append(img);}else card.append(el('p','cw-fact-value',fact.value));
    const current=p.draft.profile[fact.field];if(current&&current!==fact.value)card.append(el('p','cw-conflict',this.w('تختلف عن القيمة الحالية؛ الاستبدال يحتاج اختيارك.','Differs from the current value; replacing it requires your choice.')));
    card.append(el('small','cw-help',this.w('مستخرج من بيانات الصفحة؛ ليس تحققًا مستقلًا.','Extracted page metadata; not independently verified.')));const a=el('a','cw-source',this.w('عرض المصدر','View source'));a.href=fact.sourceUrl;a.target='_blank';a.rel='noopener noreferrer';card.append(a);const buttons=el('div','cw-form-actions');buttons.append(this.button(this.w('استخدام هذه القيمة','Use this value'),()=>{if(this.dirty)return;void this.operation(()=>p.onFact(fact.id,true));}),this.button(this.w('تجاهل','Dismiss'),()=>{if(this.dirty)return;void this.operation(()=>p.onFact(fact.id,false));}));card.append(buttons);proposals.append(card);
   }box.append(proposals);
  }
  if(!p.review){const recovery=el('details','cw-recovery'),summary=el('summary','',this.w('حل تعارض تعديل الهوية','Resolve identity edit conflict'));recovery.append(summary,el('p','cw-help',this.w('إذا عدّل مدير آخر الهوية، حمّل هويته المحفوظة دون حذف مسودة خدماتك.','When another manager changes identity, reload the saved identity without deleting your service draft.')),this.button(this.w('تحميل الهوية المحفوظة','Reload saved identity'),()=>{if(window.confirm(this.w('إلغاء تعديلات الهوية فقط وتحميل آخر نسخة؟ الخدمات لن تتغير.','Discard only identity edits and load the latest version? Services stay unchanged.'))){this.dirty=false;p.onDirty(false);void this.operation(p.onReload);}}));box.append(recovery);}
  if(this.error){const alert=el('p','cw-error',this.error);alert.setAttribute('role','alert');box.append(alert);}
  const saved=el('p','cw-save-status',this.dirty?this.w('لديك تعديلات محلية غير محفوظة.','You have unsaved local edits.'):p.draft.dirty?this.w('محفوظ في الإعداد. سيُطبّق عند حفظ إعداد العيادة.','Saved to setup. It applies when you save clinic setup.'):this.w('يعرض الهوية الحالية للعيادة.','Showing the current clinic identity.'));saved.setAttribute('role','status');box.append(saved);
  this.host.replaceChildren(box);
 }
}
