import {useState} from 'react';
import {useMutation,useQueryClient} from '@tanstack/react-query';
import {api} from '@/lib/api';
import {useI18n,useErrorMessage} from '@/lib/i18n';
import type {InventoryExtra,InventoryDetail} from '@/lib/operations-api';
import {FormField,FormError} from '@/components/form-field';
import {TextareaField,SelectField} from '@/components/setup/controls';
import {Button} from '@/components/ui/button';

const supplierFields=[
  ['supplier','اسم المورد','Supplier name','text',120],['supplierPhone','رقم المورد','Supplier phone','tel',50],['supplierEmail','إيميل المورد','Supplier email','email',200],
  ['supplierLocation','موقع / عنوان المورد','Supplier location / address','text',500],['supplierContactPerson','اسم مسؤول التواصل','Contact person','text',120],
  ['supplierContactPhone','رقم مسؤول التواصل','Contact person phone','tel',50],['supplierContactEmail','إيميل مسؤول التواصل','Contact person email','email',200],
  ['supplierWebsite','موقع المورد الإلكتروني','Supplier website','text',500],
] as const;
export function SupplierFields({value,onChange}:{value:InventoryExtra;onChange:(patch:Partial<InventoryExtra>)=>void}){
  const {lang}=useI18n();return <fieldset className="space-y-3 rounded-xl border p-4" data-testid="inventory-supplier-fields"><legend className="px-1 text-sm font-semibold">{lang==='ar'?'تفاصيل المورد — جميع الحقول اختيارية':'Supplier details — all fields optional'}</legend><p className="text-xs text-muted-foreground">{lang==='ar'?'أضف المعلومات المتوفرة الآن، ويمكنك إكمالها لاحقًا.':'Add what you know now. You can complete these details later.'}</p><div className="grid gap-3 sm:grid-cols-2">{supplierFields.map(([key,ar,en,type,max])=><FormField key={key} label={lang==='ar'?ar:en} type={type} maxLength={max} value={value[key]??''} onChange={e=>onChange({[key]:e.target.value})} dir={['email','tel'].includes(type)?'ltr':undefined} testId={`inventory-${key}`}/>)}</div><TextareaField label={lang==='ar'?'تفاصيل أخرى معروفة عن المورد':'Other known supplier details'} value={value.supplierNotes??''} onChange={supplierNotes=>onChange({supplierNotes})} maxLength={3000} testId="inventory-supplierNotes"/></fieldset>;
}
export function InventoryPricingFields({value,onChange,unit}:{value:InventoryExtra;onChange:(patch:Partial<InventoryExtra>)=>void;unit:string}){
  const {lang}=useI18n(),billable=value.billingType==='patient_charge';return <fieldset className="space-y-3 rounded-xl border p-4" data-testid="inventory-pricing-fields"><legend className="px-1 text-sm font-semibold">{lang==='ar'?'طريقة حساب سعر الصنف':'How this item is charged'}</legend><SelectField label={lang==='ar'?'استخدام الصنف':'Item usage'} value={value.billingType??'clinic_cost'} onChange={billingType=>onChange({billingType:billingType as InventoryExtra['billingType'],sellingPrice:billingType==='clinic_cost'?null:value.sellingPrice??null})} testId="inventory-billing-type"><option value="clinic_cost">{lang==='ar'?'مستهلك للعيادة — مثل القفازات والسرنجات':'Clinic consumable — e.g. gloves and syringes'}</option><option value="patient_charge">{lang==='ar'?'يُضاف سعره إلى المريض — مثل الفيلر':'Charged to patient — e.g. filler'}</option></SelectField>{billable?<><FormField label={lang==='ar'?`سعر البيع لكل ${unit} (JOD)`:`Selling price per ${unit} (JOD)`} type="number" required min="0" max="999999999.999" step="0.001" value={value.sellingPrice??''} onChange={e=>onChange({sellingPrice:e.target.value||null})} testId="inventory-selling-price"/><p className="text-xs text-muted-foreground">{lang==='ar'?'الكمية المستخدمة × سعر البيع تُضاف إلى أتعاب الطبيب المحددة في الخدمة. اربط الصنف بالخدمة في المعدات والماتيريال.':'Quantity used × selling price is added to the doctor’s fee set on the service. Link this item to its service in Equipment & Materials.'}</p></>:<p className="text-xs text-muted-foreground">{lang==='ar'?'لا يحتاج سعر بيع. تُحسب تكلفة الشراء ضمن تكلفة العيادة، ولا يُضاف سعر للمريض.':'No selling price needed. Purchase cost is included in clinic costs, with no separate patient charge.'}</p>}</fieldset>;
}
export function InventoryDetailsEditor({item}:{item:InventoryDetail}){
  const {lang}=useI18n(),errorText=useErrorMessage(),qc=useQueryClient(),[editing,setEditing]=useState(false),[extra,setExtra]=useState<InventoryExtra>(item.extra??{});
  const save=useMutation({mutationFn:()=>api(`/clinic/inventory/items/${item.id}`,{method:'PATCH',body:{extra}}),onSuccess:async()=>{setEditing(false);await Promise.all(['operations','inventory','costing','scheduling'].map(key=>qc.invalidateQueries({queryKey:[key]})));}});
  return <section className="space-y-3 rounded-xl border bg-card p-4" data-testid="inventory-supplier-details"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{lang==='ar'?'المورد وتسعير الصنف':'Supplier and item pricing'}</h2>{item.canManage&&!editing&&<Button variant="outline" onClick={()=>setEditing(true)} data-testid="edit-inventory-details">{lang==='ar'?'تعديل التفاصيل':'Edit details'}</Button>}</div>
    {editing?<form onSubmit={e=>{e.preventDefault();save.mutate();}} className="space-y-4"><fieldset disabled={save.isPending} className="space-y-4"><InventoryPricingFields value={extra} unit={item.unit} onChange={patch=>setExtra(old=>({...old,...patch}))}/><SupplierFields value={extra} onChange={patch=>setExtra(old=>({...old,...patch}))}/><FormError message={save.error?errorText(save.error):undefined}/><div className="flex gap-2"><Button type="submit" data-testid="save-inventory-details">{lang==='ar'?'حفظ التفاصيل':'Save details'}</Button><Button type="button" variant="outline" onClick={()=>{setExtra(item.extra??{});setEditing(false);}}>{lang==='ar'?'إلغاء':'Cancel'}</Button></div></fieldset></form>:<><p className="text-sm">{item.extra?.billingType==='patient_charge'?(lang==='ar'?`يُضاف للمريض: ${item.extra.sellingPrice} JOD / ${item.unit}`:`Charged to patient: ${item.extra.sellingPrice} JOD / ${item.unit}`):(lang==='ar'?'مستهلك للعيادة — لا يوجد سعر بيع للمريض':'Clinic consumable — no patient selling price')}</p><dl className="grid gap-3 text-sm sm:grid-cols-2">{supplierFields.filter(([key])=>item.extra?.[key]).map(([key,ar,en])=><div key={key}><dt className="text-xs text-muted-foreground">{lang==='ar'?ar:en}</dt><dd className="whitespace-pre-wrap break-words">{item.extra?.[key]}</dd></div>)}</dl>{item.extra?.supplierNotes&&<p className="whitespace-pre-wrap break-words text-sm">{item.extra.supplierNotes}</p>}</>}
  </section>;
}
