import {useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api} from '@/lib/api';
import {useI18n,useErrorMessage} from '@/lib/i18n';
import type {InventoryDetail} from '@/lib/operations-api';
import type {InventoryCatalog} from '@/lib/inventory-locations-api';
import {Button} from '@/components/ui/button';
import {FormError} from '@/components/form-field';

export type ServiceUsage={serviceId:number;quantity:string};
export type UsageService={id:number;name:string;branchId:number|null};
export const validServiceUsage=(lines:ServiceUsage[])=>lines.every(line=>/^\d{1,9}(?:\.\d{1,3})?$/.test(line.quantity)&&Number(line.quantity)>0);
export function ServiceUsageFields({services,value,onChange,unit,branchIds}:{services:UsageService[];value:ServiceUsage[];onChange:(value:ServiceUsage[])=>void;unit:string;branchIds:number[]}){
  const {lang,t}=useI18n(),L=(ar:string,en:string)=>lang==='ar'?ar:en;
  const available=services.filter(service=>service.branchId===null||branchIds.includes(service.branchId));
  return <fieldset className="space-y-3 rounded-xl border p-4" data-testid="inventory-service-usage"><legend className="px-1 text-sm font-semibold">{L('الخدمات والكمية التقريبية','Services & estimated usage')}</legend><p className="text-xs text-muted-foreground">{L('اختر الخدمات التي تستخدم هذا الصنف، وحدد الكمية المتوقعة لكل جلسة. يمكنك اختيار أكثر من خدمة.','Choose the services that use this item and the expected quantity per session. You can select several services.')}</p><div className="space-y-2">{available.map(service=>{const line=value.find(line=>line.serviceId===service.id);return <div key={service.id} className="grid gap-3 rounded-lg border p-3 sm:grid-cols-[1fr_180px]"><label className="flex items-center gap-2 text-sm"><input type="checkbox" className="accent-primary" checked={Boolean(line)} data-testid={`inventory-service-${service.id}`} onChange={event=>onChange(event.target.checked?[...value,{serviceId:service.id,quantity:''}]:value.filter(line=>line.serviceId!==service.id))}/>{service.name}</label>{line&&<label className="grid gap-1 text-xs"><span>{L('الكمية لكل جلسة','Quantity per session')} ({t(`p4.units.${unit}`)})</span><input aria-label={`${service.name} ${L('الكمية لكل جلسة','Quantity per session')}`} data-testid={`inventory-service-quantity-${service.id}`} required type="number" min="0.001" max="999999999.999" step="0.001" value={line.quantity} className="w-full rounded-lg border bg-background px-3 py-2 text-sm" onChange={event=>onChange(value.map(row=>row.serviceId===service.id?{...row,quantity:event.target.value}:row))}/></label>}</div>;})}</div>{!available.length&&<p className="text-sm text-muted-foreground">{L('لا توجد خدمات متاحة في الفروع المختارة. يمكنك ربط الصنف بعد إضافة الخدمات.','No services are available at these branches. You can link this item after adding services.')}</p>}<p className="text-xs text-muted-foreground">{L('هذه كمية تقديرية للتخطيط والتسعير. تُسجّل الكمية الفعلية المستخدمة عند إكمال الموعد.','This estimate is used for planning and pricing. Actual usage is recorded when the appointment is completed.')}</p></fieldset>;
}
export function InventoryServiceUsageEditor({item}:{item:InventoryDetail}){
  const {lang,t}=useI18n(),L=(ar:string,en:string)=>lang==='ar'?ar:en,errorText=useErrorMessage(),qc=useQueryClient(),[editing,setEditing]=useState(false),[value,setValue]=useState<ServiceUsage[]>(item.serviceUsage??[]);
  const catalog=useQuery({queryKey:['inventory','catalog'],queryFn:()=>api<InventoryCatalog>('/clinic/inventory/catalog'),enabled:editing});
  const save=useMutation({mutationFn:()=>api(`/clinic/inventory/items/${item.id}`,{method:'PATCH',body:{extra:{},serviceUsage:value}}),onSuccess:async()=>{setEditing(false);await Promise.all(['operations','inventory','costing','scheduling'].map(key=>qc.invalidateQueries({queryKey:[key]})));}});
  return <section className="space-y-3 rounded-xl border bg-card p-4" data-testid="inventory-service-usage-details"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">{L('استخدام الصنف في الخدمات','Service usage')}</h2>{item.canManage&&!editing&&<Button variant="outline" data-testid="edit-inventory-service-usage" onClick={()=>{setValue(item.serviceUsage??[]);setEditing(true);}}>{L('تعديل الخدمات والكميات','Edit services & quantities')}</Button>}</div>{editing?<form className="space-y-3" onSubmit={event=>{event.preventDefault();if(validServiceUsage(value))save.mutate();}}><fieldset disabled={save.isPending||catalog.isPending} className="space-y-3"><ServiceUsageFields services={catalog.data?.services??[]} value={value} onChange={setValue} unit={item.unit} branchIds={[item.branchId]}/><FormError message={catalog.error?errorText(catalog.error):save.error?errorText(save.error):undefined}/><div className="flex gap-2"><Button type="submit" data-testid="save-inventory-service-usage" disabled={!validServiceUsage(value)||Boolean(catalog.error)}>{L('حفظ','Save')}</Button><Button type="button" variant="outline" onClick={()=>setEditing(false)}>{L('إلغاء','Cancel')}</Button></div></fieldset></form>:<><p className="text-xs text-muted-foreground">{L('الكمية التقريبية لكل جلسة في هذا الفرع','Estimated quantity per session at this branch')}</p>{item.serviceUsage?.length?<ul className="space-y-2">{item.serviceUsage.map(line=><li key={line.serviceId} className="flex flex-wrap justify-between gap-2 rounded-lg bg-muted/40 p-3 text-sm"><span>{line.name}</span><b>{Number(line.quantity)} {t(`p4.units.${item.unit}`)}</b></li>)}</ul>:<p className="text-sm text-muted-foreground">{L('لم يتم اختيار خدمات لهذا الصنف بعد','No services selected for this item yet')}</p>}</>}</section>;
}
