import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Link} from 'wouter';
import {Boxes,ChevronDown} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {FormError} from '@/components/form-field';
import {api} from '@/lib/api';
import {useI18n,useErrorMessage} from '@/lib/i18n';
import {useOperationsCommand,type Branch} from '@/lib/operations-api';
import type {BranchStock,InventoryProduct,InventoryOverview,InventoryCatalog} from '@/lib/inventory-locations-api';

const input='w-full min-w-0 rounded-xl border bg-background px-3 py-2 text-sm';
export function AvailabilityFields({branches,availability,branchIds,onChange}:{branches:Branch[];availability:'all'|'selected';branchIds:number[];onChange:(availability:'all'|'selected',branchIds:number[])=>void}){
 const {lang}=useI18n(),L=(ar:string,en:string)=>lang==='ar'?ar:en;
 return <fieldset className="space-y-3 rounded-xl border p-3" data-testid="inventory-availability"><legend className="px-1 text-sm font-semibold">{L('توفر الصنف في الفروع','Item availability')}</legend>
  <label className="flex gap-2 text-sm"><input type="radio" name="item-availability" checked={availability==='all'} onChange={()=>onChange('all',branches.map(branch=>branch.id))}/>{L('كل الفروع، بما فيها الفروع الجديدة','All branches, including future branches')}</label>
  <label className="flex gap-2 text-sm"><input type="radio" name="item-availability" checked={availability==='selected'} onChange={()=>onChange('selected',branchIds.length?branchIds:[branches[0]?.id??0])}/>{L('فروع محددة','Specific branches')}</label>
  {availability==='selected'&&<div className="grid gap-2 sm:grid-cols-2">{branches.map(branch=><label key={branch.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={branchIds.includes(branch.id)} onChange={event=>onChange('selected',event.target.checked?[...branchIds,branch.id]:branchIds.filter(id=>id!==branch.id))}/>{branch.name}</label>)}</div>}
 </fieldset>;
}
export function StockHierarchy({product,roomTracking,selectedBranchId}:{product:InventoryProduct;roomTracking:boolean;selectedBranchId?:number}){
 const {lang}=useI18n(),L=(ar:string,en:string)=>lang==='ar'?ar:en;
 return <article className="min-w-0 rounded-2xl border bg-card p-4" data-testid={`inventory-product-${product.id}`}><details open={Boolean(selectedBranchId)}>
  <summary className="flex cursor-pointer list-none flex-wrap items-center justify-between gap-3"><span className="flex min-w-0 items-center gap-3"><Boxes className="size-5 shrink-0 text-primary"/><span className="min-w-0"><b className="block break-words">{product.name}</b><small className="text-muted-foreground">{product.extra.category} {product.extra.sku&&`· ${product.extra.sku}`} · {product.availability==='all'?L('كل الفروع','All branches'):L('فروع محددة','Specific branches')}</small></span></span><span className="flex items-center gap-3"><span className="text-end"><small className="block text-muted-foreground">{L('إجمالي العيادة','Clinic total')}</small><b dir="ltr" data-testid={`inventory-total-${product.id}`}>{product.totalQuantity} {product.unit}</b></span><ChevronDown className="size-4"/></span></summary>
  <p className="mt-3 text-xs text-muted-foreground">{L('المخزون الرئيسي ← الفرع','Main inventory → branch')}{roomTracking?L(' ← الغرفة',' → room'):''}</p>
  <dl className="mt-3 grid gap-2 text-xs text-muted-foreground sm:grid-cols-3">{[[L('العلامة التجارية','Brand'),product.extra.brand],[L('الحد الأدنى لكل فرع','Minimum per branch'),product.extra.minimumStock??'0'],[L('الصلاحية','Expiry'),product.extra.expiryDate]].map(([label,value])=><div key={label}><dt>{label}</dt><dd className="font-medium text-foreground">{value||'—'}</dd></div>)}</dl>
  <div className="mt-3 grid gap-3 md:grid-cols-2">{product.branches.map(branch=><BranchQuantities key={branch.id} branch={branch} unit={product.unit} roomTracking={roomTracking} selected={branch.id===selectedBranchId}/>)}</div>
 </details></article>;
}
function BranchQuantities({branch,unit,roomTracking,selected}:{branch:BranchStock;unit:string;roomTracking:boolean;selected:boolean}){
 const {lang}=useI18n(),L=(ar:string,en:string)=>lang==='ar'?ar:en;
 return <section className={`min-w-0 rounded-xl border p-3 ${selected?'border-primary bg-primary/5':'bg-muted/20'}`} data-testid={`inventory-branch-${branch.itemId}`}><div className="flex flex-wrap justify-between gap-2 text-sm"><b>{branch.name}</b><b dir="ltr">{branch.quantity} {unit}</b></div>
  {roomTracking&&<dl className="mt-3 space-y-2 border-t pt-3 text-sm"><div className="flex justify-between gap-2"><dt>{L('مخزن الفرع','Branch store')}</dt><dd dir="ltr">{branch.storeQuantity} {unit}</dd></div>{branch.rooms.map(room=><div className="flex justify-between gap-2" key={room.id} data-testid={`inventory-room-${branch.itemId}-${room.id}`}><dt className="break-words">{room.name}</dt><dd className="shrink-0" dir="ltr">{room.quantity} {unit}</dd></div>)}{!branch.rooms.length&&<p className="text-xs text-muted-foreground">{L('لا توجد غرف في هذا الفرع بعد','No rooms in this branch yet')}</p>}</dl>}
  <Link href={`/business/inventory/${branch.itemId}`} className="mt-3 inline-block text-xs underline">{L('التفاصيل وسجل الحركات','Details and movements')}</Link>
 </section>;
}
export function InventoryAvailabilityEditor({productId,availability,stocks}:{productId:number;availability:'all'|'selected';stocks:BranchStock[]}){
 const {lang}=useI18n(),errorText=useErrorMessage(),L=(ar:string,en:string)=>lang==='ar'?ar:en,qc=useQueryClient(),[editing,setEditing]=useState(false),[scope,setScope]=useState(availability),[ids,setIds]=useState(stocks.map(branch=>branch.id));
 const catalog=useQuery({queryKey:['inventory','catalog'],queryFn:()=>api<InventoryCatalog>('/clinic/inventory/catalog'),enabled:editing});
 const command=useOperationsCommand(()=>{setEditing(false);void qc.invalidateQueries({queryKey:['inventory']});void qc.invalidateQueries({queryKey:['costing']});});
 return <section className="space-y-3 rounded-xl border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">{L('توفر الصنف في الفروع','Item availability')}</h2><Button size="sm" variant="outline" onClick={()=>{setScope(availability);setIds(stocks.map(branch=>branch.id));setEditing(value=>!value);}}>{editing?L('إلغاء','Cancel'):L('تعديل الفروع','Edit branches')}</Button></div>
  {editing?<><AvailabilityFields branches={catalog.data?.branches??[]} availability={scope} branchIds={ids} onChange={(scope,ids)=>{setScope(scope);setIds(ids);}}/><p className="text-xs text-muted-foreground">{L('قبل إزالة فرع، انقل مخزونه وأزل الصنف من وصفات الخدمات وأوامر الشراء المفتوحة فيه.','Before removing a branch, transfer its stock and remove this item from its service recipes and open purchase orders.')}</p>{(catalog.error||command.error)&&<FormError message={errorText(catalog.error??command.error)}/>}<Button disabled={command.isPending||!catalog.data||scope==='selected'&&!ids.length} onClick={()=>command.mutate({path:`/clinic/inventory/products/${productId}/availability`,body:{availability:scope,...(scope==='selected'?{branchIds:ids}:{})}})}>{L('حفظ الفروع','Save branches')}</Button></>:<p className="text-sm text-muted-foreground">{availability==='all'?L('كل الفروع، بما فيها الفروع الجديدة','All branches, including future branches'):stocks.map(branch=>branch.name).join(' · ')}</p>}
 </section>;
}
export function InventoryMovementSettings(){
 const {lang}=useI18n(),errorText=useErrorMessage(),L=(ar:string,en:string)=>lang==='ar'?ar:en,qc=useQueryClient(),[mode,setMode]=useState<'branch'|'room'>('branch');
 const settings=useQuery({queryKey:['inventory','settings'],queryFn:()=>api<{movementMode:'branch'|'room';version:number;canManage:boolean}>('/clinic/inventory/settings')});
 useEffect(()=>{if(settings.data)setMode(settings.data.movementMode);},[settings.data]);
 const command=useOperationsCommand(()=>{void qc.invalidateQueries({queryKey:['inventory']});});
 return <section className="space-y-3 rounded-2xl border bg-card p-4 sm:p-5" data-testid="inventory-movement-settings"><h2 className="font-semibold">{L('حركات المخزون','Inventory movements')}</h2><p className="text-sm text-muted-foreground">{L('يظهر المخزون دائماً بإجمالي العيادة ورصيد كل فرع. اختر إن كنت تحتاج توزيعاً إضافياً على الغرف.','Inventory always shows the clinic total and each branch’s balance. Choose whether to track stock in rooms as well.')}</p>
  {settings.isPending?<p role="status">{L('جار التحميل…','Loading…')}</p>:settings.data&&<fieldset disabled={!settings.data.canManage||command.isPending} className="space-y-3"><label className="flex gap-2 rounded-xl border p-3 text-sm"><input type="radio" name="inventory-movement-mode" checked={mode==='branch'} onChange={()=>setMode('branch')}/><span><b className="block">{L('حسب الفرع','Per branch')}</b>{L('المخزون الرئيسي ← الفرع','Main inventory → branch')}</span></label><label className="flex gap-2 rounded-xl border p-3 text-sm"><input type="radio" name="inventory-movement-mode" checked={mode==='room'} onChange={()=>setMode('room')}/><span><b className="block">{L('حسب الفرع والغرفة','Per branch and room')}</b>{L('المخزون الرئيسي ← الفرع ← الغرفة','Main inventory → branch → room')}</span></label>
  {settings.data.movementMode==='room'&&mode==='branch'&&<p className="text-xs text-muted-foreground">{L('ستعود كميات الغرف إلى مخزن فرعها مع الحفاظ على الإجماليات وسجل الحركات.','Room quantities will return to their branch store. Totals and movement history are preserved.')}</p>}
  {settings.data.canManage&&<Button disabled={mode===settings.data.movementMode||command.isPending} data-testid="save-inventory-settings" onClick={()=>command.mutate({path:'/clinic/inventory/settings',body:{movementMode:mode,expectedVersion:settings.data!.version}})}>{L('حفظ إعدادات الحركات','Save movement settings')}</Button>}</fieldset>}
  {(settings.error||command.error)&&<FormError message={errorText(settings.error??command.error)}/>}
 </section>;
}
export function InventoryStockForm({mode,onClose,onSaved}:{mode:'use'|'adjust'|'transfer';onClose:()=>void;onSaved:()=>void}){
 const {lang}=useI18n(),errorText=useErrorMessage(),L=(ar:string,en:string)=>lang==='ar'?ar:en,[search,setSearch]=useState(''),[debounced,setDebounced]=useState(''),[page,setPage]=useState(1),[productId,setProductId]=useState(0),[sourceId,setSourceId]=useState(0),[targetId,setTargetId]=useState(0),[fromRoomId,setFromRoomId]=useState(0),[toRoomId,setToRoomId]=useState(0),[quantity,setQuantity]=useState('1'),[adjustType,setAdjustType]=useState<'add'|'remove'|'damaged'|'expired'>('remove'),[notes,setNotes]=useState(''),[appointmentId,setAppointmentId]=useState(''),[expiryDate,setExpiryDate]=useState('');
 useEffect(()=>{if(search===debounced)return;const timer=setTimeout(()=>{setDebounced(search);setPage(1);setProductId(0);setSourceId(0);setTargetId(0);setFromRoomId(0);setToRoomId(0);},250);return()=>clearTimeout(timer);},[search,debounced]);
 const q=useQuery({queryKey:['inventory','movement-picker',debounced,page],queryFn:()=>api<InventoryOverview>(`/clinic/inventory/overview?${new URLSearchParams({search:debounced,page:String(page),pageSize:'20'})}`)}),command=useOperationsCommand(onSaved);
 const product=q.data?.items.find(item=>item.id===productId)??q.data?.items[0],source=product?.branches.find(branch=>branch.itemId===sourceId)??product?.branches[0],target=product?.branches.find(branch=>branch.itemId===targetId)??product?.branches.find(branch=>branch.itemId!==source?.itemId)??source,roomTracking=q.data?.movementMode==='room';
 const sourceQuantity=fromRoomId?source?.rooms.find(room=>room.id===fromRoomId)?.quantity:source?.storeQuantity;
 const valid=Boolean(product&&source&&/^\d+(?:\.\d{1,3})?$/.test(quantity)&&Number(quantity)>0&&(mode==='adjust'&&adjustType==='add'||Number(quantity)<=Number(sourceQuantity))&&(mode!=='transfer'||target&&(source.itemId!==target.itemId||fromRoomId!==toRoomId))&&(mode!=='adjust'||notes.trim())&&(!appointmentId||Number.isSafeInteger(Number(appointmentId))&&Number(appointmentId)>0));
 const reset=()=>{setSourceId(0);setTargetId(0);setFromRoomId(0);setToRoomId(0);};
 const submit=()=>{if(!valid||!source||!target)return;command.mutate(mode==='transfer'?{path:'/clinic/inventory/transfers',body:{fromItemId:source.itemId,toItemId:target.itemId,fromRoomId:fromRoomId||null,toRoomId:toRoomId||null,quantity,notes}}:{path:`/clinic/inventory/items/${source.itemId}/movements`,body:{kind:mode==='adjust'&&adjustType==='add'?'receipt':'adjustment',roomId:fromRoomId||null,...(mode==='adjust'&&adjustType==='add'?{expiryDate:expiryDate||null}:{}),quantity:`${mode==='adjust'&&adjustType==='add'?'':'-'}${quantity}`,reason:mode==='use'?`Usage: ${notes.trim()||'Inventory item used'}`:`${adjustType}: ${notes.trim()}`,reasonLang:'en',...(mode==='use'&&appointmentId?{appointmentReferenceId:Number(appointmentId)}:{})}});};
 const locations=(branch:BranchStock|undefined,value:number,onChange:(value:number)=>void,label:string)=><label className="grid gap-1 text-sm"><span>{label}</span><select className={input} aria-label={label} value={value} onChange={event=>onChange(Number(event.target.value))}><option value={0}>{L('مخزن الفرع','Branch store')} ({branch?.storeQuantity??'0.000'})</option>{branch?.rooms.map(room=><option value={room.id} key={room.id}>{room.name} ({room.quantity})</option>)}</select></label>;
 return <div className="space-y-4"><label className="grid gap-1 text-sm">{L('بحث عن صنف','Search items')}<input aria-label={L('بحث عن صنف','Search items')} className={input} value={search} onChange={event=>setSearch(event.target.value)}/></label>
  {(q.error||command.error)&&<FormError message={errorText(q.error??command.error)}/>}
  <label className="grid gap-1 text-sm">{L('الصنف','Item')}<select aria-label={L('الصنف','Item')} className={input} value={product?.id??0} onChange={event=>{setProductId(Number(event.target.value));reset();}}>{q.data?.items.map(item=><option key={item.id} value={item.id}>{item.name} · {item.totalQuantity} {item.unit}</option>)}</select></label>
  {q.data&&q.data.total>20&&<div className="flex justify-between"><Button variant="outline" disabled={page<=1} onClick={()=>{setPage(page-1);setProductId(0);reset();}}>{L('السابق','Previous')}</Button><span className="text-sm">{page} / {Math.ceil(q.data.total/20)}</span><Button variant="outline" disabled={page*20>=q.data.total} onClick={()=>{setPage(page+1);setProductId(0);reset();}}>{L('التالي','Next')}</Button></div>}
  <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">{mode==='transfer'?L('من الفرع','From branch'):L('الفرع','Branch')}<select aria-label={mode==='transfer'?L('من الفرع','From branch'):L('الفرع','Branch')} className={input} value={source?.itemId??0} onChange={event=>{setSourceId(Number(event.target.value));setFromRoomId(0);}}>{product?.branches.map(branch=><option key={branch.itemId} value={branch.itemId}>{branch.name}</option>)}</select></label>
  {roomTracking&&locations(source,fromRoomId,setFromRoomId,mode==='transfer'?L('من الموقع','From location'):L('الموقع','Location'))}
  {mode==='transfer'&&<><label className="grid gap-1 text-sm">{L('إلى الفرع','To branch')}<select aria-label={L('إلى الفرع','To branch')} className={input} value={target?.itemId??0} onChange={event=>{setTargetId(Number(event.target.value));setToRoomId(0);}}>{product?.branches.map(branch=><option key={branch.itemId} value={branch.itemId}>{branch.name}</option>)}</select></label>{roomTracking&&locations(target,toRoomId,setToRoomId,L('إلى الموقع','To location'))}</>}
  </div><p className="text-xs text-muted-foreground">{L('المتاح في الموقع المحدد','Available at the selected location')}: <b dir="ltr">{sourceQuantity??'0.000'} {product?.unit}</b></p>
  {mode==='adjust'&&<label className="grid gap-1 text-sm">{L('نوع التعديل','Adjustment type')}<select aria-label={L('نوع التعديل','Adjustment type')} className={input} value={adjustType} onChange={event=>setAdjustType(event.target.value as typeof adjustType)}>{(['add','remove','damaged','expired'] as const).map(value=><option value={value} key={value}>{({add:L('إضافة','Add'),remove:L('خصم','Remove'),damaged:L('تالف','Damaged'),expired:L('منتهي الصلاحية','Expired')})[value]}</option>)}</select></label>}
  <label className="grid gap-1 text-sm">{L('الكمية','Quantity')}<input aria-label={L('الكمية','Quantity')} className={input} type="number" min="0.001" step="0.001" value={quantity} onChange={event=>setQuantity(event.target.value)}/></label>
  {mode==='adjust'&&adjustType==='add'&&<label className="grid gap-1 text-sm">{L('تاريخ صلاحية الدفعة (اختياري)','Batch expiry date (optional)')}<input aria-label={L('تاريخ صلاحية الدفعة (اختياري)','Batch expiry date (optional)')} type="date" className={input} value={expiryDate} onChange={event=>setExpiryDate(event.target.value)} data-testid="inventory-stock-expiry"/></label>}{mode==='use'&&<label className="grid gap-1 text-sm">{L('رقم الموعد كمرجع (اختياري)','Appointment reference (optional)')}<input aria-label={L('رقم الموعد كمرجع (اختياري)','Appointment reference (optional)')} className={input} type="number" min={1} value={appointmentId} onChange={event=>setAppointmentId(event.target.value)}/></label>}
  <label className="grid gap-1 text-sm">{L('ملاحظات','Notes')}<textarea aria-label={L('ملاحظات','Notes')} className={input} value={notes} maxLength={1000} onChange={event=>setNotes(event.target.value)}/></label>
  {mode==='transfer'&&<p className="text-xs text-muted-foreground">{L('التحويل يغير التوزيع فقط؛ يبقى إجمالي العيادة كما هو.','A transfer changes the distribution and preserves the clinic total.')}</p>}
  <div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose}>{L('إلغاء','Cancel')}</Button><Button disabled={command.isPending||q.isFetching||!valid} onClick={submit} data-testid="save-inventory-stock">{mode==='transfer'?L('تحويل','Transfer'):mode==='use'?L('تسجيل الاستخدام','Record usage'):L('حفظ التعديل','Save adjustment')}</Button></div>
 </div>;
}
