import { Router, type IRouter } from 'express';
import { z } from 'zod';
import { requireAuth, requirePasswordChanged } from '../middlewares/auth';
import { waitingCreateSchema, waitingListSchema, waitingDecisionSchema, suggestionSchema, confirmReplacementSchema,
  inventoryCreateSchema, inventoryUpdateSchema, inventoryListSchema, purchaseOrderCreateSchema, purchaseOrderReceiveSchema, transferStockSchema, movementSchema, consumptionSchema } from '../domain/operations-validation';
import { addWaitingEntry, listWaitingEntries, replacementView, suggestReplacement, declineWaitingEntry, confirmReplacement, refreshWaiting } from '../services/waiting-list';
import { inventoryCatalog, createInventoryItem, listInventory, inventoryDashboard, inventoryReports, updateInventoryItem, inventoryDetail, recordMovement, appointmentConsumption, recordAppointmentConsumption, serviceActualUse } from '../services/inventory';
import {validDate} from '../domain/scheduling-rules';
import {listPurchaseOrders,purchaseOrderDetail,createPurchaseOrder,receivePurchaseOrder,cancelPurchaseOrder,transferStock,listTransfers} from '../services/inventory-workflows';
import {inventoryAvailabilitySchema,inventorySettingsSchema} from '../domain/inventory-locations';
import {inventoryOverview,getInventorySettings,saveInventorySettings,saveInventoryAvailability} from '../services/inventory-locations';
const router:IRouter=Router();
const id=(v:unknown)=>z.coerce.number().int().positive().parse(v);
const pagination=z.object({page:z.coerce.number().int().min(1).max(100000).default(1),pageSize:z.coerce.number().int().min(1).max(50).default(20)}).strict();
router.use('/clinic/waiting-list',requireAuth,requirePasswordChanged);
router.use('/clinic/inventory',requireAuth,requirePasswordChanged);
router.get('/clinic/waiting-list',async(req,res)=>{res.json(await listWaitingEntries(req.user!,waitingListSchema.parse(req.query)));});
router.post('/clinic/waiting-list',async(req,res)=>{res.status(201).json(await addWaitingEntry(req.user!,waitingCreateSchema.parse(req.body)));});
router.post('/clinic/waiting-list/refresh',async(req,res)=>{res.json(await refreshWaiting(req.user!,suggestionSchema.parse(req.body)));});
router.post('/clinic/waiting-list/:id/decline',async(req,res)=>{res.json(await declineWaitingEntry(req.user!,id(req.params.id),waitingDecisionSchema.parse(req.body)));});
router.post('/clinic/waiting-list/offers/:id/confirm',async(req,res)=>{
  const result=await confirmReplacement(req.user!,id(req.params.id),confirmReplacementSchema.parse(req.body));res.status('error' in result?409:200).json(result);
});
router.get('/clinic/appointments/:id/replacement',requireAuth,requirePasswordChanged,async(req,res)=>{res.json(await replacementView(req.user!,id(req.params.id)));});
router.post('/clinic/appointments/:id/replacement/suggest',requireAuth,requirePasswordChanged,async(req,res)=>{res.json(await suggestReplacement(req.user!,id(req.params.id),suggestionSchema.parse(req.body)));});
router.get('/clinic/inventory/catalog',async(req,res)=>{res.json(await inventoryCatalog(req.user!));});
router.get('/clinic/inventory/overview',async(req,res)=>{res.json(await inventoryOverview(req.user!,inventoryListSchema.parse(req.query)));});
router.get('/clinic/inventory/settings',async(req,res)=>{res.json(await getInventorySettings(req.user!));});
router.post('/clinic/inventory/settings',async(req,res)=>{res.json(await saveInventorySettings(req.user!,inventorySettingsSchema.parse(req.body)));});
router.post('/clinic/inventory/products/:id/availability',async(req,res)=>{res.json(await saveInventoryAvailability(req.user!,id(req.params.id),inventoryAvailabilitySchema.parse(req.body)));});
router.get('/clinic/inventory/dashboard',async(req,res)=>{res.json(await inventoryDashboard(req.user!));});
router.get('/clinic/inventory/reports',async(req,res)=>{const range=z.object({from:z.string().refine(validDate),to:z.string().refine(validDate)}).strict().refine(value=>value.to>=value.from&&Date.parse(value.to)-Date.parse(value.from)<=93*86400000,'invalid_date_range').parse(req.query);res.json(await inventoryReports(req.user!,range.from,range.to));});
router.get('/clinic/inventory/orders',async(req,res)=>{const filter=z.object({branchId:z.coerce.number().int().positive().optional(),status:z.enum(['pending','partial','received','cancelled']).optional()}).strict().parse(req.query);res.json(await listPurchaseOrders(req.user!,filter));});
router.post('/clinic/inventory/orders',async(req,res)=>{res.status(201).json(await createPurchaseOrder(req.user!,purchaseOrderCreateSchema.parse(req.body)));});
router.get('/clinic/inventory/orders/:id',async(req,res)=>{res.json(await purchaseOrderDetail(req.user!,id(req.params.id)));});
router.post('/clinic/inventory/orders/:id/receive',async(req,res)=>{res.json(await receivePurchaseOrder(req.user!,id(req.params.id),purchaseOrderReceiveSchema.parse(req.body)));});
router.post('/clinic/inventory/orders/:id/cancel',async(req,res)=>{res.json(await cancelPurchaseOrder(req.user!,id(req.params.id)));});
router.get('/clinic/inventory/transfers',async(req,res)=>{res.json(await listTransfers(req.user!));});
router.post('/clinic/inventory/transfers',async(req,res)=>{res.status(201).json(await transferStock(req.user!,transferStockSchema.parse(req.body)));});
router.get('/clinic/inventory/items',async(req,res)=>{res.json(await listInventory(req.user!,inventoryListSchema.parse(req.query)));});
router.post('/clinic/inventory/items',async(req,res)=>{res.status(201).json(await createInventoryItem(req.user!,inventoryCreateSchema.parse(req.body)));});
router.patch('/clinic/inventory/items/:id',async(req,res)=>{res.json(await updateInventoryItem(req.user!,id(req.params.id),inventoryUpdateSchema.parse(req.body)));});
router.get('/clinic/inventory/items/:id',async(req,res)=>{const q=pagination.parse(req.query);res.json(await inventoryDetail(req.user!,id(req.params.id),q.page,q.pageSize));});
router.post('/clinic/inventory/items/:id/movements',async(req,res)=>{res.status(201).json(await recordMovement(req.user!,id(req.params.id),movementSchema.parse(req.body)));});
router.get('/clinic/appointments/:id/consumption',requireAuth,requirePasswordChanged,async(req,res)=>{res.json(await appointmentConsumption(req.user!,id(req.params.id)));});
router.post('/clinic/appointments/:id/consumption',requireAuth,requirePasswordChanged,async(req,res)=>{res.json(await recordAppointmentConsumption(req.user!,id(req.params.id),consumptionSchema.parse(req.body)));});
router.get('/clinic/services/:id/actual-use',requireAuth,requirePasswordChanged,async(req,res)=>{const q=pagination.parse(req.query);res.json(await serviceActualUse(req.user!,id(req.params.id),q.page,q.pageSize));});
export default router;
