import { Router, type IRouter } from 'express';
import { z } from 'zod';
import { requireAuth, requirePasswordChanged } from '../middlewares/auth';
import { bookingSchema, availabilitySchema, calendarSchema, catalogSchema, transitionSchema, rescheduleSchema, appointmentNotesSchema, bookingCustomerSchema } from '../domain/scheduling-validation';
import { calendarCounts, availability, createAppointment, listAppointments, getAppointment, transitionAppointment, rescheduleAppointment, saveAppointmentNotes, schedulingCatalog, schedulingHome, customerAppointments, createBookingCustomer } from '../services/scheduling';
const router: IRouter = Router();
const id = (value: unknown) => z.coerce.number().int().positive().parse(value);
router.use('/clinic/scheduling', requireAuth, requirePasswordChanged);
router.use('/clinic/appointments', requireAuth, requirePasswordChanged);
router.get('/clinic/scheduling/catalog', async (req, res) => {res.json(await schedulingCatalog(req.user!, catalogSchema.parse(req.query)));});
router.get('/clinic/scheduling/availability', async (req, res) => {res.json(await availability(req.user!, availabilitySchema.parse(req.query)));});
router.get('/clinic/scheduling/calendar', async (req, res) => {res.json(await calendarCounts(req.user!, calendarSchema.parse(req.query)));});
router.get('/clinic/scheduling/home', async (req, res) => {const branchId=z.coerce.number().int().positive().optional().parse(req.query.branchId);res.json(await schedulingHome(req.user!,branchId));});
router.post('/clinic/scheduling/customer', async (req, res) => {res.status(201).json(await createBookingCustomer(req.user!, bookingCustomerSchema.parse(req.body)));});
router.get('/clinic/appointments', async (req, res) => {res.json(await listAppointments(req.user!, calendarSchema.parse(req.query)));});
router.post('/clinic/appointments', async (req, res) => {res.status(201).json(await createAppointment(req.user!, bookingSchema.parse(req.body)));});
router.get('/clinic/appointments/:id', async (req, res) => {res.json(await getAppointment(req.user!, id(req.params.id)));});
router.post('/clinic/appointments/:id/status', async (req, res) => {res.json(await transitionAppointment(req.user!, id(req.params.id), transitionSchema.parse(req.body)));});
router.post('/clinic/appointments/:id/reschedule', async (req, res) => {res.json(await rescheduleAppointment(req.user!, id(req.params.id), rescheduleSchema.parse(req.body)));});
router.post('/clinic/appointments/:id/notes', async (req, res) => {res.json(await saveAppointmentNotes(req.user!, id(req.params.id), appointmentNotesSchema.parse(req.body)));});
router.get('/clinic/customers/:id/appointments', requireAuth, requirePasswordChanged, async (req, res) => {res.json(await customerAppointments(req.user!, id(req.params.id), calendarSchema.parse(req.query)));});
export default router;
