import {InventoryBatches} from '@/components/operations/inventory-batches';
import {InventoryServiceUsageEditor} from '@/components/operations/inventory-service-usage';
import {StockHierarchy,InventoryAvailabilityEditor} from '@/components/operations/inventory-locations';
import { useEffect,useState } from 'react';
import {InventoryDetailsEditor} from '@/components/operations/inventory-details';
import { Link,useLocation,useRoute } from 'wouter';
import { useQuery } from '@tanstack/react-query';
import { PageHeader } from '@/components/app-shell';
import { Button } from '@/components/ui/button';
import { FormError,FormField } from '@/components/form-field';
import { SelectField,EnteredName,TextareaField } from '@/components/setup/controls';
import { api } from '@/lib/api';
import { useAuth } from '@/lib/auth';
import { can } from '@/lib/setup-api';
import { useI18n,useErrorMessage } from '@/lib/i18n';
import { queryString,formatAppointmentTime } from '@/lib/scheduling-api';
import { UNITS,useOperationsCommand,type Branch,type Unit,type InventoryItem,type InventoryDetail,type Page } from '@/lib/operations-api';
function NewInventoryItem({branches,onClose}:{branches:Branch[];onClose:()=>void}) {
  const {t,lang}=useI18n(),errorMessage=useErrorMessage(),[,navigate]=useLocation();
  const [name,setName]=useState(''),[nameLang,setNameLang]=useState<'en'|'ar'>(lang),[branchId,setBranchId]=useState(''),[unit,setUnit]=useState<Unit>('piece');
  const command=useOperationsCommand(r=>navigate(`/business/inventory/${r.id}`));
  return <form className="space-y-4 rounded-xl border bg-card p-4 sm:p-5" onSubmit={e=>{e.preventDefault();command.mutate({path:'/clinic/inventory/items',body:{name,nameLang,branchId:Number(branchId),unit}});}} data-testid="inventory-create-form"><fieldset disabled={command.isPending} className="space-y-4"><h2 className="font-semibold">{t('p4.addItem')}</h2>
    <p className="text-xs text-muted-foreground">{t('p4.itemIdentityHint')}</p><div className="grid gap-4 sm:grid-cols-2">
      <SelectField label={t('p2.fields.nameLang')} value={nameLang} onChange={v=>setNameLang(v as 'en'|'ar')} testId="inventory-name-language"><option value="en">English</option><option value="ar">العربية</option></SelectField>
      <FormField label={t('p4.itemName')} value={name} onChange={e=>setName(e.target.value)} required maxLength={120} lang={nameLang} dir={nameLang==='ar'?'rtl':'ltr'} testId="inventory-name"/>
      <SelectField label={t('p3.branch')} value={branchId} onChange={setBranchId} required testId="inventory-create-branch"><option value="">{t('p4.choose')}</option>{branches.map(b=><option key={b.id} value={b.id} lang={b.nameLang}>{b.name}</option>)}</SelectField>
      <SelectField label={t('p4.unit')} value={unit} onChange={v=>setUnit(v as Unit)} required testId="inventory-unit">{UNITS.map(u=><option key={u} value={u}>{t(`p4.units.${u}`)}</option>)}</SelectField>
    </div><FormError message={command.error?errorMessage(command.error):undefined}/><div className="flex flex-wrap gap-2"><Button type="submit" data-testid="inventory-create-save">{t('p4.addItem')}</Button><Button type="button" variant="outline" onClick={onClose} data-testid="inventory-create-cancel">{t('common.cancel')}</Button></div></fieldset>
  </form>;
}
export default function InventoryPage() {
  const {user}=useAuth(),{t}=useI18n(),errorMessage=useErrorMessage(),allowed=can(user,'inventory.read');
  const [adding,setAdding]=useState(false),[branchId,setBranchId]=useState(''),[search,setSearch]=useState(''),[debounced,setDebounced]=useState(''),[page,setPage]=useState(1);
  useEffect(()=>{const timer=setTimeout(()=>{setDebounced(search);setPage(1);},250);return()=>clearTimeout(timer);},[search]);
  const catalog=useQuery({queryKey:['operations','inventory','catalog'],queryFn:()=>api<{branches:Branch[];canManage:boolean}>('/clinic/inventory/catalog'),enabled:allowed});
  const q=useQuery({queryKey:['operations','inventory','items',branchId,debounced,page],queryFn:()=>api<Page<InventoryItem>>(`/clinic/inventory/items?${queryString({branchId,search:debounced,page,pageSize:20})}`),enabled:allowed});
  if(!allowed)return <FormError message={t('p4.permissionDenied')}/>;
  return <div className="mx-auto max-w-5xl space-y-5"><Link href="/business" className="focus-ring inline-block rounded text-sm underline" data-testid="inventory-back-business">{t('sections.business.title')}</Link><PageHeader title={t('p4.inventoryTitle')}/><p className="text-sm text-muted-foreground">{t('p4.inventoryIntro')}</p>
    {catalog.error&&<FormError message={errorMessage(catalog.error)}/>}{catalog.data?.canManage&&!adding&&<Button onClick={()=>setAdding(true)} data-testid="inventory-add-item">{t('p4.addItem')}</Button>}{adding&&catalog.data?.canManage&&<NewInventoryItem branches={catalog.data.branches} onClose={()=>setAdding(false)}/>}
    <div className="grid gap-3 sm:grid-cols-2"><FormField label={t('p4.searchItems')} type="search" value={search} onChange={e=>setSearch(e.target.value)} maxLength={120} testId="inventory-search"/><SelectField label={t('p3.branch')} value={branchId} onChange={v=>{setBranchId(v);setPage(1);}} testId="inventory-filter-branch"><option value="">{t('p2.allBranches')}</option>{catalog.data?.branches.map(b=><option key={b.id} value={b.id} lang={b.nameLang}>{b.name}</option>)}</SelectField></div>
    {q.isPending?<p role="status">{t('common.loading')}</p>:q.isError?<FormError message={errorMessage(q.error)}/>:!q.data?.items.length?<p className="rounded-lg border p-4 text-sm" data-testid="inventory-empty">{t('p4.inventoryEmpty')}</p>:<div className="grid gap-3 sm:grid-cols-2">{q.data.items.map(item=><article key={item.id} className="space-y-3 rounded-xl border bg-card p-4" data-testid={`inventory-item-${item.id}`}><h2 className="font-semibold"><EnteredName item={item}/></h2><p className="text-sm text-muted-foreground"><EnteredName item={item.branch}/></p><dl><dt className="text-xs text-muted-foreground">{t('p4.balance')}</dt><dd className="text-xl font-semibold"><bdi dir="ltr">{item.balance}</bdi> <span className="text-sm">{t(`p4.units.${item.unit}`)}</span></dd></dl><Link href={`/business/inventory/${item.id}`} className="focus-ring inline-block rounded text-sm font-medium underline" data-testid={`inventory-open-${item.id}`}>{t('p4.movementHistory')}</Link></article>)}</div>}
    {q.data&&<nav className="flex flex-wrap items-center justify-between gap-3" aria-label={t('p4.inventoryTitle')}><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)} data-testid="inventory-prev">{t('p2.previous')}</Button><span className="text-xs text-muted-foreground">{t('p2.page',{page,pages:Math.max(1,Math.ceil(q.data.total/20))})}</span><Button variant="outline" disabled={page*20>=q.data.total} onClick={()=>setPage(page+1)} data-testid="inventory-next">{t('p2.next')}</Button></nav>}
  </div>;
}
function MovementForm({item}:{item:InventoryDetail}) {
  const {t,lang}=useI18n(),errorMessage=useErrorMessage(),[kind,setKind]=useState<'receipt'|'adjustment'>('receipt'),[quantity,setQuantity]=useState(''),[reason,setReason]=useState(''),[reasonLang,setReasonLang]=useState<'en'|'ar'>(lang),[roomId,setRoomId]=useState(''),[expiryDate,setExpiryDate]=useState('');
  const command=useOperationsCommand(()=>{setQuantity('');setReason('');});
  return <form className="space-y-4 rounded-xl border bg-card p-4 sm:p-5" onSubmit={e=>{e.preventDefault();command.mutate({path:`/clinic/inventory/items/${item.id}/movements`,body:{kind,quantity,reason,reasonLang,...(Number(quantity)>0?{expiryDate:expiryDate||null}:{}),roomId:roomId?Number(roomId):null}});}} data-testid="inventory-movement-form"><fieldset disabled={command.isPending} className="space-y-4"><h2 className="font-semibold">{t('p4.recordMovement')}</h2>
    <div className="grid gap-4 sm:grid-cols-2"><SelectField label={t('p4.movementKind')} value={kind} onChange={v=>setKind(v as 'receipt'|'adjustment')} testId="movement-kind"><option value="receipt">{t('p4.kinds.receipt')}</option><option value="adjustment">{t('p4.kinds.adjustment')}</option></SelectField>
      <FormField label={`${t('p4.quantity')} (${t(`p4.units.${item.unit}`)})`} type="number" inputMode="decimal" step="0.001" min={kind==='receipt'?'0.001':'-9000000000'} max="9000000000" required value={quantity} onChange={e=>setQuantity(e.target.value)} testId="movement-quantity"/>
    </div>{Number(quantity)>0&&<FormField label={lang==='ar'?'تاريخ صلاحية هذه الدفعة (اختياري)':'This batch expiry date (optional)'} type="date" value={expiryDate} onChange={event=>setExpiryDate(event.target.value)} testId="movement-expiry-date"/>}<p className="text-xs text-muted-foreground">{t('p4.quantityHint')}</p>{item.movementMode==='room'&&<SelectField label={lang==='ar'?'الموقع':'Location'} value={roomId} onChange={setRoomId} testId="movement-location"><option value="">{lang==='ar'?'مخزن الفرع':'Branch store'} ({item.branches?.find(branch=>branch.id===item.branchId)?.storeQuantity??'0.000'})</option>{item.branches?.find(branch=>branch.id===item.branchId)?.rooms.map(room=><option key={room.id} value={room.id}>{room.name} ({room.quantity})</option>)}</SelectField>}<SelectField label={t('p4.noteLanguage')} value={reasonLang} onChange={v=>setReasonLang(v as 'en'|'ar')} testId="movement-reason-language"><option value="en">English</option><option value="ar">العربية</option></SelectField>
    <FormField label={t('p4.movementReason')} value={reason} onChange={e=>setReason(e.target.value)} required={kind==='adjustment'} maxLength={1000} lang={reasonLang} dir={reasonLang==='ar'?'rtl':'ltr'} testId="movement-reason"/>
    <FormError message={command.error?errorMessage(command.error):undefined}/><Button type="submit" data-testid="save-inventory-movement">{command.isPending?t('common.loading'):t('p4.saveMovement')}</Button></fieldset>
  </form>;
}
export function InventoryDetailPage() {
  const [,params]=useRoute('/business/inventory/:id'),id=Number(params?.id),{user}=useAuth(),{t,lang}=useI18n(),errorMessage=useErrorMessage(),allowed=can(user,'inventory.read'),[page,setPage]=useState(1),[movementTab,setMovementTab]=useState<'all'|'receipt'|'usage'|'adjustment'|'transfer'>('all');
  const q=useQuery({queryKey:['operations','inventory','item',id,page],queryFn:()=>api<InventoryDetail>(`/clinic/inventory/items/${id}?page=${page}&pageSize=20`),enabled:allowed&&Number.isSafeInteger(id)&&id>0});
  if(!allowed)return <FormError message={t('p4.permissionDenied')}/>;
  if(!Number.isSafeInteger(id)||id<=0)return <FormError message={t('errors.inventory_item_not_found')}/>;
  const item=q.data;
  const L=(ar:string,en:string)=>lang==='ar'?ar:en;
  const movements=item?.movements.filter(m=>movementTab==='all'||movementTab==='receipt'&&m.kind==='receipt'&&!m.reason.startsWith('Transfer #')||movementTab==='usage'&&(m.kind==='consumption'||m.kind==='adjustment'&&m.reason.startsWith('Usage'))||movementTab==='adjustment'&&m.kind==='adjustment'&&!m.reason.startsWith('Usage')&&!m.reason.startsWith('Transfer #')||movementTab==='transfer'&&m.reason.startsWith('Transfer #'))??[];
  return <div className="mx-auto max-w-4xl space-y-5"><Link href="/business/inventory" className="focus-ring inline-block rounded text-sm underline" data-testid="inventory-detail-back">{t('p4.backInventory')}</Link><PageHeader title={t('p4.inventoryTitle')}/>
    {q.isPending?<p role="status">{t('common.loading')}</p>:q.isError?<FormError message={errorMessage(q.error)}/>:item&&<>
      <section className="space-y-3 rounded-xl border bg-card p-4" data-testid="inventory-detail"><h2 className="text-xl font-semibold"><EnteredName item={item}/></h2><p className="text-sm text-muted-foreground"><EnteredName item={item.branch}/></p><dl><dt className="text-xs text-muted-foreground">{t('p4.balance')}</dt><dd className="text-2xl font-semibold" data-testid="inventory-current-balance" data-balance={item.balance}><bdi dir="ltr">{item.balance}</bdi> <span className="text-sm">{t(`p4.units.${item.unit}`)}</span></dd></dl></section>
      <section className="grid gap-4 rounded-xl border bg-card p-4 sm:grid-cols-[110px_1fr]">{item.extra?.imageDataUrl&&/^data:image\/(?:png|jpeg);base64,/.test(item.extra.imageDataUrl)?<img src={item.extra.imageDataUrl} alt="" className="aspect-square w-full rounded-xl object-cover"/>:<div className="grid aspect-square place-items-center rounded-xl bg-muted text-3xl text-primary">◈</div>}<dl className="grid gap-3 text-sm sm:grid-cols-3">{[[L('الفئة','Category'),item.extra?.category],[L('العلامة التجارية','Brand'),item.extra?.brand],[L('الرمز','SKU'),item.extra?.sku],[L('الحد الأدنى','Minimum stock'),item.extra?.minimumStock],[L('تكلفة الوحدة JOD','Unit cost JOD'),item.extra?.unitCost],[L('سعر البيع JOD','Selling price JOD'),item.extra?.billingType==='patient_charge'?item.extra?.sellingPrice:L('لا ينطبق','Not applicable')],[L('الصلاحية','Expiry'),item.extra?.expiryDate],[L('المورد','Supplier'),item.extra?.supplier],[L('شروط التخزين','Storage'),item.extra?.storageConditions]].map(([label,value])=><div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="font-medium">{value||'—'}</dd></div>)}</dl>{item.extra?.description&&<p className="sm:col-span-2 text-sm text-muted-foreground">{item.extra.description}</p>}</section>
      {item.productId&&item.branches&&<StockHierarchy product={{id:item.productId,name:item.name,nameLang:item.nameLang,unit:item.unit,extra:item.extra??{},availability:item.availability??'selected',totalQuantity:item.totalQuantity??item.balance,branches:item.branches}} roomTracking={item.movementMode==='room'} selectedBranchId={item.branchId}/>}
      {item.canManage&&item.productId&&item.branches&&<InventoryAvailabilityEditor key={`availability-${item.productId}-${item.availability}-${item.branches.map(branch=>branch.id).join(',')}`} productId={item.productId} availability={item.availability??'selected'} stocks={item.branches}/>}
      {item.canManage&&<MovementForm key={item.id} item={item}/>}
      <InventoryBatches item={item}/>
      <InventoryServiceUsageEditor key={`usage-${item.id}-${JSON.stringify(item.serviceUsage)}`} item={item}/>
      <InventoryDetailsEditor key={`details-${item.id}-${JSON.stringify(item.extra)}`} item={item}/>
      <section className="space-y-4 rounded-xl border bg-card p-4 sm:p-5"><h2 className="font-semibold">{t('p4.movementHistory')}</h2><p className="text-xs text-muted-foreground">{t('p4.inventoryIntro')}</p>
        <div className="flex flex-wrap gap-2">{(['all','receipt','usage','adjustment','transfer'] as const).map(value=><Button key={value} size="sm" variant={movementTab===value?'default':'outline'} onClick={()=>setMovementTab(value)}>{value==='all'?L('كل الحركات','All movements'):value==='receipt'?L('استلام','Receipts'):value==='usage'?L('استخدام','Usage'):value==='adjustment'?L('تعديلات','Adjustments'):L('تحويلات','Transfers')}</Button>)}</div>
        {!movements.length?<p className="text-sm">{t('p4.noMovements')}</p>:<ol className="space-y-3">{movements.map(m=><li key={m.id} className="space-y-2 rounded-lg border p-3 text-sm" data-testid={`inventory-movement-${m.id}`}><div className="flex flex-wrap justify-between gap-2"><p className="font-medium">{m.reason.startsWith('Transfer #')?L('تحويل','Transfer'):m.reason.startsWith('Usage')?L('استخدام','Usage'):t(`p4.kinds.${m.kind}`)}</p><p className="font-semibold"><bdi dir="ltr">{m.quantity}</bdi> {t(`p4.units.${m.unit}`)}</p></div><time className="block text-xs text-muted-foreground" dateTime={m.createdAt}>{formatAppointmentTime(m.createdAt,item.branch.timeZone,lang,true)}</time>{m.roomId&&<p className="text-xs">{L('الغرفة','Room')}: {item.branches?.find(branch=>branch.id===item.branchId)?.rooms.find(room=>room.id===m.roomId)?.name??`#${m.roomId}`}</p>}<p className="text-xs">{t('p4.recordedBy')}: <EnteredName item={m.actor}/></p>{m.reason&&<p className="whitespace-pre-wrap break-words" lang={m.reasonLang} dir={m.reasonLang==='ar'?'rtl':'ltr'}>{m.reason}</p>}{m.appointmentId&&m.canOpenAppointment&&<Link href={`/appointments/${m.appointmentId}`} className="focus-ring inline-block rounded underline" data-testid={`movement-appointment-${m.id}`}>{t('p3.open')}</Link>}</li>)}</ol>}
        <nav className="flex flex-wrap items-center justify-between gap-3" aria-label={t('p4.movementHistory')}><Button variant="outline" disabled={page<=1} onClick={()=>setPage(page-1)} data-testid="movements-prev">{t('p2.previous')}</Button><span className="text-xs text-muted-foreground">{t('p2.page',{page,pages:Math.max(1,Math.ceil(item.total/20))})}</span><Button variant="outline" disabled={page*20>=item.total} onClick={()=>setPage(page+1)} data-testid="movements-next">{t('p2.next')}</Button></nav>
      </section>
    </>}
  </div>;
}
