import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { useI18n, useErrorMessage } from '@/lib/i18n';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { FormError } from '@/components/form-field';
import { HoursReadout } from './controls';
import type { RecordItem, ListResult } from '@/lib/setup-api';
import { formatInstantTime, formatClockTime } from '@/lib/time-format';
type Archive={branch:RecordItem;counts:Record<string,number>;records:Record<string,Record<string,unknown>[]>;page:number;pageSize:number};
type DraftArchive={id:number;archivedAt:string;branch:RecordItem;services:Record<string,unknown>[];rooms:Record<string,unknown>[];staff:Record<string,unknown>[]};
const labels:Record<string,[string,string]>={services:['الخدمات','Services'],rooms:['الغرف','Rooms'],staff:['الموظفون','Staff'],customers:['العملاء','Customers'],appointments:['المواعيد','Appointments'],waitingList:['قائمة الانتظار','Waiting list'],inventory:['المخزون','Inventory'],stockMovements:['حركات المخزون','Stock movements'],consumptions:['الاستهلاك','Consumption'],purchaseOrders:['طلبات الشراء','Purchase orders'],equipment:['المعدات','Equipment'],roomBlocks:['حجوزات الغرف','Room blocks']};
function archiveValue(value:unknown,zone:string,lang:string,key=''):string{
 if(value===null||value===undefined)return '—';
 if(typeof value==='string'&&/^\d{4}-\d\d-\d\dT\d\d:\d\d/.test(value))return formatInstantTime(value,zone,lang,true);
 if(typeof value==='string'&&['open','close','time'].includes(key)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(value))return formatClockTime(value);
 if(typeof value!=='object')return String(value);
 if(Array.isArray(value))return value.map(v=>archiveValue(v,zone,lang,key)).join(' · ');
 return Object.entries(value as Record<string,unknown>).map(([k,v])=>`${k}: ${archiveValue(v,zone,lang,k)}`).join(' / ');
}
export function BranchArchivePanel(){
 const {lang,dir}=useI18n(),errorMessage=useErrorMessage(),ar=lang==='ar';
 const [open,setOpen]=useState(false),[selected,setSelected]=useState<{id:number;draft:boolean}|null>(null),[listPage,setListPage]=useState(1),[page,setPage]=useState(1),[group,setGroup]=useState('services');
 const list=useQuery({queryKey:['setup','branches','archive-list',listPage],queryFn:()=>api<ListResult>(`/clinic/branches?status=archived&page=${listPage}&pageSize=20`),enabled:open});
 const drafts=useQuery({queryKey:['setup','branches','draft-archives'],queryFn:()=>api<{items:DraftArchive[]}>('/clinic/branches/draft-archives'),enabled:open});
 const detail=useQuery({queryKey:['setup','branches','archive-detail',selected?.id,page],queryFn:()=>api<Archive>(`/clinic/branches/${selected!.id}/archive?page=${page}`),enabled:open&&!!selected&&!selected.draft});
 const draft=selected?.draft?drafts.data?.items.find(item=>item.id===selected.id):undefined;
 const data=draft?{branch:draft.branch,counts:{services:draft.services.length,rooms:draft.rooms.length,staff:draft.staff.length},records:{services:draft.services,rooms:draft.rooms,staff:draft.staff},page:1,pageSize:50}:detail.data;
 const choose=(id:number,isDraft=false)=>{setSelected({id,draft:isDraft});setPage(1);setGroup('services');};
 return <section className="mt-5 rounded-2xl border bg-card p-4" data-testid="branch-archive"><Button variant="outline" onClick={()=>setOpen(!open)} data-testid="open-branch-archive">{ar?'أرشيف الفروع':'Branch archive'}</Button>{open&&<div className="mt-4 space-y-3"><p className="text-sm text-muted-foreground">{ar?'الفروع المحذوفة محفوظة هنا مع بياناتها للمراجعة.':'Deleted branches and their data are preserved here for review.'}</p>{(list.isError||drafts.isError)&&<FormError message={errorMessage(list.error??drafts.error)}/>}<div className="flex flex-wrap gap-2">{list.data?.items.map(branch=><Button key={branch.id} variant="outline" onClick={()=>choose(branch.id)} data-testid={`archive-branch-${branch.id}`}>{branch.name}</Button>)}{drafts.data?.items.map(item=><Button key={'draft-'+item.id} variant="outline" onClick={()=>choose(item.id,true)}>{item.branch.name??(ar?'فرع بدون اسم':'Unnamed branch')} · {ar?'مسودة الإعداد':'Setup draft'}</Button>)}</div>{list.data?.total===0&&!drafts.data?.items.length&&<p>{ar?'لا توجد فروع مؤرشفة.':'No archived branches.'}</p>}{(list.data?.total??0)>20&&<div className="flex gap-3"><Button variant="outline" disabled={listPage<=1} onClick={()=>setListPage(p=>p-1)}>{ar?'السابق':'Previous'}</Button><span>{listPage}</span><Button variant="outline" disabled={listPage*20>=(list.data?.total??0)} onClick={()=>setListPage(p=>p+1)}>{ar?'التالي':'Next'}</Button></div>}</div>}
 <Dialog open={selected!==null} onOpenChange={isOpen=>{if(!isOpen)setSelected(null);}}><DialogContent dir={dir} className="max-h-[90dvh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{data?.branch.name??(ar?'أرشيف الفرع':'Branch archive')}</DialogTitle><DialogDescription>{ar?'للمراجعة فقط — بيانات الفرع محفوظة ولا يستقبل حجوزات جديدة.':'Read only — branch data is preserved; new bookings are disabled.'}</DialogDescription></DialogHeader>{detail.isError&&!draft&&<FormError message={errorMessage(detail.error)}/>} {data&&<><p className="text-sm">{data.branch.address} <bdi>{data.branch.timeZone??'Asia/Amman'}</bdi></p>{data.branch.openingHours&&<details><summary>{ar?'ساعات الفرع':'Branch hours'}</summary><HoursReadout value={data.branch.openingHours}/></details>}<div className="flex flex-wrap gap-2" role="tablist">{Object.entries(data.counts).map(([key,count])=><Button key={key} role="tab" aria-selected={group===key} variant={group===key?'default':'outline'} onClick={()=>{setGroup(key);setPage(1);}}>{labels[key]?.[ar?0:1]??key} ({count})</Button>)}</div><div className="space-y-3" data-testid="archive-records">{(data.records[group]??[]).map((row,index)=><details key={String(row.id??index)} className="rounded-xl border p-3"><summary className="cursor-pointer font-semibold">{archiveValue(row.name??row.startsAt??row.id??index+1,data.branch.timeZone??'Asia/Amman',lang)}</summary><dl className="mt-3 grid gap-2 text-xs sm:grid-cols-2">{Object.entries(row).filter(([key])=>!['clinicId','createdBy','updatedBy','id'].includes(key)).map(([key,value])=><div key={key} className="min-w-0"><dt className="font-semibold">{key.replace(/([A-Z])/g,' $1').replace(/^./,s=>s.toUpperCase())}</dt><dd className="break-words" dir="auto">{archiveValue(value,data.branch.timeZone??'Asia/Amman',lang,key)}</dd></div>)}</dl></details>)}{!data.records[group]?.length&&<p className="text-sm text-muted-foreground">{ar?'لا توجد سجلات في هذه الصفحة.':'No records on this page.'}</p>}</div>{!draft&&(data.counts[group]??0)>50&&<div className="flex items-center gap-3"><Button variant="outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>{ar?'السابق':'Previous'}</Button><span>{page}</span><Button variant="outline" disabled={page*50>=(data.counts[group]??0)} onClick={()=>setPage(p=>p+1)}>{ar?'التالي':'Next'}</Button></div>}</>}</DialogContent></Dialog></section>;
}
