import type { Language } from "./contract";
const en = {
  entryTitle: "Your business starts here",
  entrySubtitle: "Choose how you’d like to get everything ready.",
  voiceDescription: "Talk naturally. Your assistant opens the right pages and fills the details with you.",
  manualDescription: "Explore the workspace and enter your company details at your own pace.",
  voiceAction: "Let’s talk →",
  manualAction: "Open workspace →",
  voiceConsent: "By choosing voice, you agree to send your voice, clinic conversation and uploaded documents to OpenAI. Your microphone audio is also sent to Soniox to help recognize speech; your documents are not sent to Soniox.",
  introText: "Tell me everything about your clinic first. When you finish, say ‘I'm done’. Then we’ll build your workspace together.",
  introNote: "Speak in your own words about your clinic, services, branches and team. You can pause between thoughts.",
  uploadDrop: "Drop your company file here",
  continueWithoutFile: "Continue without a file",
  restart: "Restart setup with current access",
  welcome: "Welcome",
  recordName: "Name",
  title: "Your setup companion",
  brand: "JorMall · Assistant",
  close: "Continue later",
  open: "Smart setup",
  name: "What should I call you?",
  namePlaceholder: "Your first name",
  next: "Continue",
  loading: "One moment…",
  thinking: "Thinking…",
  speaking: "Speaking",
  listening: "Listening to you",
  ready: "Ready when you are",
  paused: "Microphone paused",
  voice: "Set up by voice",
  manual: "I’ll enter the details",
  textMode: "Continue by typing",
  start: "Let’s begin",
  quiet:
    "Find a quiet place and allow about 15 minutes. You can pause and return at any time.",
  noiseHint: "There may be background noise. Move somewhere quieter or use a headset for clearer speech.",
  consent:
    "I agree to send my voice, setup conversation and uploaded business documents to OpenAI to provide this session.",
  privacy:
    "Do not share patient records, passwords or payment details. The app retains setup progress, not audio or original files. Provider retention policies still apply.",
  enableSound: "Enable voice playback",
  sound: "Hear this message",
  voiceUnavailable:
    "Voice is not configured yet. Add the OpenAI key on the server. Manual setup is available now.",
  aiUnavailable:
    "Conversational setup needs an OpenAI server key. Manual setup still works.",
  setupStatus: "Provider configuration is not a live connection test.",
  continueText: "Continue without the microphone",
  send: "Send",
  message: "Your message",
  messagePlaceholder: "Tell me about your clinic and the services you actually offer…",
  keyboard: "Type a reply",
  attach: "Upload a document",
  uploadTitle: "Send it here. I’ll read it while we stay together.",
  uploadHint:
    "PDF, UTF-8 TXT, CSV or JSON · up to 8 MB. No patient records or passwords.",
  chooseFile: "Choose a file",
  fileReading: "Uploading and reading your document…",
  read: "Read successfully",
  unreadable: "Could not read this document",
  review: "Review setup",
  draft: "Company details",
  draftNote:
    "Not yet applied to your business. Review the details before saving.",
  noDraft: "Nothing collected yet. Tell me about your first branch.",
  back: "Back to conversation",
  saveDraft: "Save corrections",
  apply: "Confirm and save to the system",
  confirm:
    "I have reviewed the details and staff access. Create these records and update the listed existing branches.",
  missing:
    "Some details are missing or invalid. Complete the highlighted fields, then save corrections.",
  required: "Required or invalid",
  cancel: "Cancel",
  remove: "Remove item",
  existing: "Existing branch — will be updated",
  newRecord: "New record",
  nameLang: "Name language",
  ar: "Arabic",
  en: "English",
  timeZone: "Time zone (IANA)",
  openingHours: "Branch opening hours",
  workingHours: "Staff working hours",
  breaks: "Breaks",
  scheduleUnknown:
    "Not supplied yet — enter the week or explicitly mark all days closed.",
  closedWeek: "Confirm all days closed",
  noBreaks: "Confirm no breaks this week",
  closed: "Closed / none",
  addRange: "Add time range",
  openTime: "From",
  closeTime: "Until",
  removeRange: "Remove range",
  branchKey: "Branch",
  clinicWide: "All branches / clinic-wide",
  choose: "Choose…",
  durationMinutes: "Duration (minutes)",
  price: "Price",
  currency: "Currency",
  category: "Category",
  requiresRoom: "Needs a room",
  yes: "Yes",
  no: "No",
  capacity: "Room capacity",
  serviceKeys: "Compatible / performed services",
  noServices: "Confirm no services assigned",
  email: "Login email",
  phone: "Phone (optional)",
  jobTitle: "Job title (optional)",
  role: "Role",
  password: "Initial password (at least 10 characters)",
  passwordNote:
    "Entered here only, never sent to the AI. It is hashed on save; staff must change it at first login. Share it securely before saving — it will not be shown afterwards.",
  permissions: "Review exact access",
  readPermission: "Read",
  managePermission: "Manage",
  accountReview: "Account security",
  saved: "Your setup has been saved",
  enter: "Enter the workspace",
  doneNote:
    "Saved records are available in the existing business and staff screens. You can still edit them there.",
  emptyScope: "Existing appointments, customers and inventory are unchanged.",
  navigate: "Open the suggested page",
  interruption: "Interrupt / speak now",
  stopVoice: "End microphone session",
  startVoice: "Start microphone",
  resume: "Resume voice",
  expired:
    "The voice connection needs refreshing. Reconnect to continue.",
  hidden:
    "Microphone stopped because this page became hidden. Resume when you return.",
  error: "Something went wrong. Nothing was confirmed as saved. Try again.",
  retry: "Try again",
  changes: "Saved records",
  passwordRequired:
    "Enter a password of at least 10 characters for every new staff account.",
  passwordsForgotten: "Passwords are not kept when leaving this review screen.",
  reviewHint: "Speak to add more, or review what we’ve collected.",
  busy: "Still processing your previous request. Please wait a moment.",
  refresh: "Refresh company details",
  branches: "Branches",
  services: "Services",
  rooms: "Rooms",
  staff: "Staff",
  employees: "Staff",
  settings: "Settings",
  appointments: "Appointments",
  customers: "Customers",
  inventory: "Inventory",
  mon: "Monday",
  tue: "Tuesday",
  wed: "Wednesday",
  thu: "Thursday",
  fri: "Friday",
  sat: "Saturday",
  sun: "Sunday",
  Hair: "Hair",
  Nails: "Nails",
  Skin: "Skin",
  Laser: "Laser",
  Massage: "Massage",
  Makeup: "Makeup",
  Other: "Other",
  secretary: "Secretary",
  doctor: "Doctor",
  service_provider: "Service provider",
  other_staff: "Other staff",
  manager: "Manager",
  voiceConnecting: "Connecting microphone…",
  fileTooBig: "This file exceeds 8 MB.",
  micDenied:
    "Microphone permission was not granted. Allow it in the browser or continue by typing.",
  micUnsupported:
    "Voice needs HTTPS (or localhost), microphone access and a WebRTC-capable browser.",
  connectionLost:
    "Voice connection ended. Reconnect to continue.",
  audioBlocked:
    "Your browser needs a click before it can play the voice. Press “Enable voice playback”.",
  offline: "Could not reach the server. Check your connection and retry.",
  unsupportedFile: "Choose a PDF or a UTF-8 TXT, CSV or JSON file.",
  pending: "You can return later to continue setting up your company.",
  scopeNote:
    "This assistant prepares branches, services, rooms and staff. Booking, customer and inventory actions remain in their existing permission-checked screens.",
  deleteConfirm: "Remove this item?",
  leaveReview:
    "Leave review? Unsaved corrections and entered passwords will be cleared.",
  guide: "Staff help",
  noCompatible:
    "No available services to select. Add services through the conversation first.",
};
type Key = keyof typeof en;
const ar: Record<Key, string> = {
  entryTitle: "شركتك جاهزة لخطوة جديدة",
  entrySubtitle: "كيف بتحب نجهّز مساحة شغلك؟",
  voiceDescription: "احكي بطبيعتك، ومساعدتك بتفتح الصفحات وبتعبّي التفاصيل معك خطوة بخطوة.",
  manualDescription: "ادخل على مساحة شغلك وعبّي معلومات شركتك بنفسك، وعلى راحتك.",
  voiceAction: "يلا نحكي ←",
  manualAction: "افتح مساحة الشغل ←",
  voiceConsent: "باختيار الصوت، بتوافق نرسل صوتك ومحادثة تجهيز مركز التجميل والملفات إلى OpenAI، وكمان صوت الميكروفون إلى Soniox للمساعدة بفهم الكلام. الملفات ما بتنبعت إلى Soniox.",
  introText: "احكيلي إنت عن عيادتك وكل الخدمات والفروع والفريق اللي عندك. خذ راحتك، ولما تخلص احكي «خلصت». بعدها بنرتّبها مع بعض.",
  introNote: "احكي بطريقتك وعلى راحتك. فيك توقف بين فكرة وفكرة، وما رح نقاطعك بأسئلة.",
  uploadDrop: "اسحب ملف شركتك لهون",
  continueWithoutFile: "نكمّل بدون ملف",
  restart: "نبدأ تجهيز الشركة من جديد",
  welcome: "أهلين",
  recordName: "الاسم",
  title: "مساعدتك لتجهيز البرنامج",
  brand: "JorMall · مساعدتك الذكية",
  close: "بكمل بعدين",
  open: "التجهيز الذكي",
  name: "شو بتحب أناديك؟",
  namePlaceholder: "اكتب اسمك هون",
  next: "نكمل",
  loading: "لحظة معي…",
  thinking: "عم برتّب المعلومات…",
  speaking: "عم بحكي معك",
  listening: "سامعتك، تفضّل",
  ready: "جاهزة، خذ راحتك",
  paused: "الميكروفون متوقف",
  voice: "خلّينا نجهّزه بالصوت",
  manual: "بعبّي البيانات بنفسي",
  textMode: "نكمل بالكتابة",
  start: "يلا نبدأ",
  quiet: "اختار مكان هادي وخلّي عندك حوالي ربع ساعة. بتقدر توقف وترجع بأي وقت.",
  noiseHint: "يبدو في صوت حواليك؛ جرّب مكان أهدى أو سماعة بميكروفون عشان أسمعك أوضح.",
  consent:
    "أوافق على إرسال صوتي ومحادثة التجهيز وملفات العمل المرفوعة إلى OpenAI لتقديم هذه الجلسة.",
  privacy:
    "لا ترسل بيانات المرضى أو كلمات المرور أو معلومات الدفع. البرنامج يحتفظ بتقدّم تجهيز الشركة، ولا يحتفظ بالتسجيل الصوتي أو الملفات الأصلية. تبقى سياسات احتفاظ المزوّد بالبيانات سارية.",
  enableSound: "تفعيل الصوت",
  sound: "اسمع الرسالة",
  voiceUnavailable:
    "الصوت لسه مش مُعدّ. أضف مفتاح OpenAI بإعدادات السيرفر. التعبئة اليدوية شغّالة.",
  aiUnavailable:
    "التجهيز بالمحادثة يحتاج مفتاح OpenAI على السيرفر. بتقدر تعبّي البيانات يدويًا.",
  setupStatus: "وجود الإعدادات لا يعني أنه تم اختبار الاتصال الفعلي.",
  continueText: "نكمل بدون ميكروفون",
  send: "إرسال",
  message: "رسالتك",
  messagePlaceholder: "احكيلي عن عيادتك والخدمات اللي بتقدّمها فعلًا…",
  keyboard: "اكتب ردك",
  attach: "ارفع ملف",
  uploadTitle: "ابعت الملف هون، وأنا بقرأه وبضل معك.",
  uploadHint:
    "PDF أو TXT أو CSV أو JSON بترميز UTF-8 · حتى 8 ميغابايت. بدون بيانات مرضى أو كلمات مرور.",
  chooseFile: "اختيار ملف",
  fileReading: "عم برفع الملف وبقرأ محتواه…",
  read: "تمت قراءة الملف",
  unreadable: "ما قدرت أقرأ هالملف",
  review: "نراجع البيانات",
  draft: "تفاصيل شركتك",
  draftNote: "لسه ما أضفناها للنظام. راجع التفاصيل قبل الحفظ.",
  noDraft: "لسه ما جمعنا بيانات. احكيلي عن أول فرع عندك.",
  back: "نرجع للمحادثة",
  saveDraft: "احفظ التعديلات",
  apply: "تأكيد وحفظ بالنظام",
  confirm:
    "راجعت البيانات وصلاحيات الموظفين، وأوافق على إنشاء السجلات وتحديث الفروع الموجودة والمذكورة هنا.",
  missing:
    "في معلومات ناقصة أو غير صحيحة. كمّل الخانات المحددة، وبعدين احفظ التعديلات.",
  required: "مطلوب أو غير صحيح",
  cancel: "إلغاء",
  remove: "احذف العنصر",
  existing: "فرع موجود — رح نحدّثه",
  newRecord: "سجل جديد",
  nameLang: "لغة الاسم",
  ar: "العربية",
  en: "الإنجليزية",
  timeZone: "المنطقة الزمنية (IANA)",
  openingHours: "ساعات دوام الفرع",
  workingHours: "ساعات دوام الموظف",
  breaks: "الاستراحات",
  scheduleUnknown:
    "لسه ما حددنا الأسبوع. عبّي الساعات أو أكّد أن كل الأيام مغلقة.",
  closedWeek: "كل أيام الأسبوع مغلقة",
  noBreaks: "ما في استراحات خلال الأسبوع",
  closed: "مغلق / لا يوجد",
  addRange: "أضف فترة",
  openTime: "من",
  closeTime: "إلى",
  removeRange: "احذف الفترة",
  branchKey: "الفرع",
  clinicWide: "كل الفروع / على مستوى المركز",
  choose: "اختار…",
  durationMinutes: "مدة الخدمة بالدقائق",
  price: "السعر",
  currency: "العملة",
  category: "التصنيف",
  requiresRoom: "تحتاج غرفة",
  yes: "نعم",
  no: "لا",
  capacity: "سعة الغرفة",
  serviceKeys: "الخدمات المتوافقة / التي يقدّمها الموظف",
  noServices: "بدون خدمات مرتبطة",
  email: "بريد الدخول",
  phone: "الهاتف (اختياري)",
  jobTitle: "المسمّى الوظيفي (اختياري)",
  role: "الدور",
  password: "كلمة المرور الأولية (10 أحرف على الأقل)",
  passwordNote:
    "تُدخل هون فقط، ولا تُرسل للذكاء الاصطناعي. تُحفظ مُشفّرة بالتجزئة، ويجب تغييرها عند أول دخول. شاركها بشكل آمن قبل الحفظ؛ لن تُعرض بعده.",
  permissions: "راجع الصلاحيات بالتفصيل",
  readPermission: "قراءة",
  managePermission: "إدارة",
  accountReview: "أمان الحساب",
  saved: "جهّزنا بياناتك وحفظناها",
  enter: "افتح البرنامج",
  doneNote:
    "السجلات المحفوظة موجودة بشاشات الأعمال والموظفين الحالية، وبتقدر تعدّلها من هناك.",
  emptyScope: "المواعيد والعملاء والمخزون الموجودة ما تغيّرت.",
  navigate: "افتح الصفحة المقترحة",
  interruption: "وقّف الرد / بدي أحكي",
  stopVoice: "إنهاء الميكروفون",
  startVoice: "تشغيل الميكروفون",
  resume: "نكمل بالصوت",
  expired:
    "اتصال الصوت بحاجة لتجديد. شغّله مرة ثانية ونكمّل.",
  hidden: "وقفنا الميكروفون لما غبت عن الصفحة. شغّله لما ترجع.",
  error:
    "صار خطأ. ما بنعتبر البيانات محفوظة بدون تأكيد من السيرفر. جرّب مرة ثانية.",
  retry: "جرّب مرة ثانية",
  changes: "السجلات المحفوظة",
  passwordRequired: "أدخل كلمة مرور من 10 أحرف على الأقل لكل موظف جديد.",
  passwordsForgotten: "كلمات المرور ما بتضل محفوظة لما تطلع من شاشة المراجعة.",
  reviewHint: "احكي لنضيف معلومات، أو خلّينا نراجع اللي جمعناه.",
  busy: "لسه بنعالج طلبك السابق. استنّى لحظة ونكمّل.",
  refresh: "حدّث تفاصيل الشركة",
  branches: "الفروع",
  services: "الخدمات",
  rooms: "الغرف",
  staff: "الموظفون",
  employees: "الموظفون",
  settings: "الإعدادات",
  appointments: "المواعيد",
  customers: "العملاء",
  inventory: "المخزون",
  mon: "الإثنين",
  tue: "الثلاثاء",
  wed: "الأربعاء",
  thu: "الخميس",
  fri: "الجمعة",
  sat: "السبت",
  sun: "الأحد",
  Hair: "الشعر",
  Nails: "الأظافر",
  Skin: "البشرة",
  Laser: "الليزر",
  Massage: "المساج",
  Makeup: "المكياج",
  Other: "أخرى",
  secretary: "سكرتير / سكرتيرة",
  doctor: "طبيب / طبيبة",
  service_provider: "مقدّم / مقدّمة خدمة",
  other_staff: "موظف آخر",
  manager: "مدير",
  voiceConnecting: "عم بوصل الميكروفون…",
  fileTooBig: "حجم الملف أكبر من 8 ميغابايت.",
  micDenied: "إذن الميكروفون مش مفعّل. اسمح له من المتصفح أو كمّل بالكتابة.",
  micUnsupported:
    "الصوت يحتاج HTTPS (أو localhost) وإذن الميكروفون ومتصفح يدعم WebRTC.",
  connectionLost:
    "انقطع اتصال الصوت. شغّله مرة ثانية ونكمّل من هون.",
  audioBlocked: "المتصفح يحتاج ضغطة منك قبل تشغيل الصوت. اضغط «تفعيل الصوت».",
  offline: "ما قدرت أوصل للسيرفر. افحص الاتصال وجرّب مرة ثانية.",
  unsupportedFile: "اختار ملف PDF أو TXT أو CSV أو JSON بترميز UTF-8.",
  pending: "بتقدر ترجع بعدين ونكمّل تجهيز شركتك.",
  scopeNote:
    "المساعدة بتجهّز الفروع والخدمات والغرف والموظفين. إجراءات الحجز والعملاء والمخزون بتضل بشاشاتها الحالية وبنفس الصلاحيات.",
  deleteConfirm: "أحذف هالعنصر؟",
  leaveReview:
    "تطلع من المراجعة؟ رح تنحذف التعديلات غير المحفوظة وكلمات المرور المكتوبة.",
  guide: "مساعدة الموظفين",
  noCompatible: "ما في خدمات متاحة للاختيار. أضف خدمات بالمحادثة أولًا.",
};
const errors: Record<string, Key> = {
  validation: "missing",
  concierge_missing_fields: "missing",
  concierge_staff_passwords: "passwordRequired",
  branch_mismatch: "missing",
  permission_escalation: "missing",
  concierge_busy: "busy",
  concierge_stale: "refresh",
  concierge_session_required: "refresh",
  concierge_origin: "error",
  concierge_consent_required: "consent",
  concierge_llm_unavailable: "aiUnavailable",
  concierge_voice_unavailable: "voiceUnavailable",
  concierge_tts_unavailable: "voiceUnavailable",
  concierge_stt_unavailable: "voiceUnavailable",
  concierge_file_type: "unsupportedFile",
  concierge_text_file: "unsupportedFile",
  concierge_upload_too_large: "fileTooBig",
  concierge_incomplete: "missing",
  concierge_invalid_data: "missing",
  validation_failed: "missing",
  validation_error: "missing",
  concierge_invalid_reference: "missing",
  concierge_branch_changed: "refresh",
  concierge_access_changed: "refresh",
};
export function text(lang: Language, key: Key | string): string {
  return (lang === "ar" ? ar : en)[key as Key] ?? key;
}
export function errorText(lang: Language, code: string): string {
  const special: Record<string, [string, string]> = {
    concierge_stream_interrupted: ['انقطع الاتصال قبل تأكيد حفظ المسودة. حدّث الجلسة قبل إعادة المحاولة.','Connection ended before draft confirmation. Refresh the session before retrying.'],
    concierge_definition_required: ['كل خدمة تحتاج تعريفًا. افتح تعديل الخدمة واختر قالبها ثم احفظها.','Every service needs a definition. Edit the service, choose a template, and save.'],
    concierge_services_only: ['هذا المعالج يخصص الخدمات فقط. بقيت باقي أقسام النظام دون تغيير.','This wizard only customizes services. Other sections were not changed.'],
    service_definition_invalid: ['راجع اسم القسم وحقول الخدمة والخيارات المطلوبة.','Check the service section, fields, and required options.'],

    concierge_migration_required: [
      "جدول أو عمود جديد للمساعدة غير موجود. طبّق ترحيل قاعدة البيانات حسب دليل التشغيل، ثم أعد المحاولة.",
      "An assistant database table or column is missing. Apply the documented migration, then retry.",
    ],
    concierge_daily_limit: [
      "المساعدة وصلت لحدّ الاستخدام المحدد من إدارة النظام. راجع إعدادات الاستخدام.",
      "The administrator-configured usage limit was reached. Check usage settings.",
    ],
    concierge_provider_auth: [
      "مفتاح المزوّد أو صلاحياته مش صحيحة. راجع إعدادات السيرفر.",
      "The provider rejected its key or permissions. Check server secrets.",
    ],
    concierge_provider_limit: [
      "المزوّد مشغول أو الرصيد غير كافٍ. جرّب بعد شوي وراجع حساب المزوّد.",
      "The provider is busy or has insufficient quota. Retry later and check its account.",
    ],
    concierge_provider_quota: [
      "رصيد OpenAI للمفتاح الحالي مستنفد. لتشغيل الصوت والبحث، أضف رصيدًا لحساب API أو حدّث المفتاح بمفتاح من مشروع فيه رصيد. الانتظار وحده ما بحل المشكلة.",
      "The current OpenAI API key has no available credit. Add API credit or use a key from a funded project to enable voice and search. Waiting alone will not resolve this.",
    ],
    concierge_timeout: [
      "الرد تأخّر. جرّب مرة ثانية لنكمّل.",
      "The response timed out. Retry to continue.",
    ],
    concierge_duplicate: [
      "في سجل بنفس الاسم موجود أصلًا. راجع البيانات قبل الإضافة.",
      "A record with the same name already exists. Review it before adding.",
    ],
    email_taken: [
      "البريد مستخدم بحساب موجود. اختار بريد ثاني أو عدّل الحساب من شاشة الموظفين.",
      "That email is already in use. Choose another or edit the existing staff account.",
    ],
  };
  special.workspace_invalid=['راجع اسم العيادة والحقول والألوان وصيغة الشعار.','Check clinic names, fields, colors and logo format.'];
  special.workspace_stale=['عدّل مدير آخر الهوية. استخدم «حل تعارض تعديل الهوية» لتحميل آخر نسخة. مسودة الخدمات لم تُحفظ تشغيليًا.','Another manager changed identity. Use Resolve identity edit conflict to reload the latest identity. Service changes were not applied.'];
  if (special[code]) return special[code]![lang === "ar" ? 0 : 1];
  return text(lang, errors[code] ?? "error");
}
