import { infoPages } from './info-pages';
import type { Language, Session } from './contract';
import { safeLogo, logoPalette } from './branding';
import { createPhoneInput } from '../phone-input';
import { button, el } from './dom';
import { setupPager } from './paging';

export type ImportEdits = {
 facts: { id: string; value: string }[];
 services: { index: number; name: string; detail: string; followUpEnabled: boolean }[];
 branches: { index: number; name: string; detail: string }[];
};
export type ImportSelection = { factIds: string[]; serviceIndexes: number[]; branchIndexes: number[]; logoColor: string|null; edits: ImportEdits };
export const emptyImportEdits = (): ImportEdits => ({ facts: [], services: [], branches: [] });

/** Edits remain local until the manager approves the selected information. */
export function buildImportApproval(session: Session, language: Language, busy: boolean, edits: ImportEdits, approve: (selection: ImportSelection) => void, back: () => void): HTMLElement {
 const ar=language==='ar',w=(a:string,e:string)=>ar?a:e,details=session.branding!.details;
 const root=el('section','jc-import-review');root.dataset.testid='concierge-import-review';
 const selectedFacts:{id:string;check:HTMLInputElement}[]=[],selectedServices:HTMLInputElement[]=[],selectedBranches:HTMLInputElement[]=[];
 const factNames:Record<string,[string,string]>={nameAr:['اسم المركز بالعربية','Arabic name'],nameEn:['اسم المركز بالإنجليزية','English name'],logoDataUrl:['شعار المركز','Clinic logo'],primaryColor:['اللون الأساسي','Primary color'],accentColor:['اللون الإضافي','Accent color'],phone:['رقم الهاتف','Phone'],email:['البريد الإلكتروني','Email'],address:['العنوان','Address'],website:['الموقع أو الصفحة','Website'],subtitleAr:['الوصف بالعربية','Arabic subtitle'],subtitleEn:['الوصف بالإنجليزية','English subtitle']};
 const info=(label:string,value:string|null|undefined)=>{const line=el('div','jc-import-detail-line');line.append(el('strong','',label),el('p','',value||w('غير متوفر','Not available')));return line;};
 const link=(url:string)=>{const line=info(w('المصدر','Source'),url);try{const u=new URL(url);if(u.protocol==='https:'){const a=el('a','',url);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';line.lastChild?.replaceWith(a);}}catch{}return line;};
 const image=(value:string)=>{if(!safeLogo(value))return info(w('الشعار','Logo'),w('الصورة غير صالحة','Invalid image'));const img=el('img','jc-import-detail-logo');img.src=value;img.alt=w('شعار المركز','Clinic logo');return img;};
 const context=()=>{const box=el('div');box.append(info(w('المركز','Clinic'),session.companyProfile?.name??session.branding?.name),info(w('ملخص المعلومات','Information summary'),session.companyProfile?.summary));return box;};
 const field=(label:string,value:string,max:number,multiline=false)=>{const labelNode=el('label','jc-service-field'),input=multiline?el('textarea'):el('input');input.value=value;input.maxLength=max;input.dir='auto';input.setAttribute('aria-label',label);labelNode.append(el('span','',label),input);return {node:labelNode,input};};
 const row=(key:string,title:string,summary:()=>HTMLElement,more:()=>HTMLElement,editor:(form:HTMLFormElement,close:()=>void,refresh:()=>void)=>void)=>{
  const box=el('article','jc-import-row');box.dataset.testid=`import-row-${key}`;
  const line=el('div','jc-import-row-top'),label=el('label','jc-import-option'),check=el('input'),content=el('span','jc-import-option-text');check.type='checkbox';check.checked=true;check.disabled=busy;check.dataset.testid=`import-check-${key}`;
  const refresh=()=>content.replaceChildren(el('strong','',title),summary());refresh();label.append(check,content);line.append(label);
  const actions=el('div','jc-import-row-actions'),panel=el('div','jc-import-detail');panel.id=`import-detail-${key}`;panel.hidden=true;
  const moreButton=button(w('معلومات أكثر','More info'),()=>{const opening=panel.hidden;panel.hidden=!opening;moreButton.setAttribute('aria-expanded',String(opening));if(opening)infoPages(panel,more(),language,`import-info-pages-${key}`);},'jc-button jc-small',`import-info-${key}`);moreButton.setAttribute('aria-expanded','false');moreButton.setAttribute('aria-controls',panel.id);
  const editHost=el('div','jc-import-editor');editHost.hidden=true;
  const editButton=button(w('تعديل','Edit'),()=>{editHost.hidden=false;const form=el('form','jc-import-edit-form');editor(form,()=>{editHost.hidden=true;editHost.replaceChildren();editButton.setAttribute('aria-expanded','false');},()=>{refresh();if(!panel.hidden)infoPages(panel,more(),language,`import-info-pages-${key}`);});editHost.replaceChildren(form);editButton.setAttribute('aria-expanded','true');form.querySelector<HTMLInputElement|HTMLTextAreaElement>('input,textarea')?.focus();},'jc-button jc-small',`import-edit-${key}`);editButton.disabled=busy;editButton.setAttribute('aria-expanded','false');
  actions.append(moreButton,editButton);line.append(actions);box.append(line,panel,editHost);return {box,check};
 };
 const editorActions=(form:HTMLFormElement,close:()=>void,save:()=>void)=>{const actions=el('div','jc-import-row-actions'),submit=el('button','jc-button jc-primary',w('حفظ التعديل','Save edit'));submit.type='submit';actions.append(button(w('رجوع','Back'),close,'jc-button'),submit);form.append(actions);form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity())return;save();close();};};
 const hero=el('div','jc-import-hero'),color=details.colors.find(v=>/^#[0-9a-f]{6}$/i.test(v));
 let paletteColor:string|null=null;const paletteSection=el('div','jc-import-section');paletteSection.hidden=true;let paletteCheck:HTMLInputElement|null=null;
 if(safeLogo(details.logoDataUrl)){const logo=el('img','jc-import-logo');logo.alt=session.branding!.name;logo.onload=()=>{if(color)return;const value=logoPalette(logo)[0];if(!value)return;paletteColor=value;paletteSection.hidden=false;const r=row('logo-color',w('لون مقترح من الشعار، اختَره إذا بناسبك','Color suggested from the logo; select it if it fits'),()=>el('small','',paletteColor!),()=>{const box=el('div');box.append(info(w('اللون','Color'),paletteColor),image(details.logoDataUrl!),info(w('المصدر','Source'),w('مستخرج من شعار المركز','Sampled from the clinic logo')));return box;},(form,close,refresh)=>{const input=field(w('اللون','Color'),paletteColor!,7);input.input.required=true;input.input.setAttribute('type','color');form.append(input.node);editorActions(form,close,()=>{paletteColor=input.input.value;refresh();});});r.check.checked=false;paletteCheck=r.check;paletteSection.replaceChildren(el('h2','',w('لون المركز','Clinic color')),r.box);};logo.src=details.logoDataUrl;hero.append(logo);}else hero.append(el('span','jc-import-logo-placeholder',session.branding!.name.slice(0,1)));
 hero.append(el('div','jc-import-hero-text',session.branding!.name));root.append(hero);
 const facts=session.workspace?.proposals.filter((f,i,all)=>all.findIndex(other=>other.field===f.field)===i)??[];
 if(facts.length){const section=el('div','jc-import-section');section.append(el('h2','',w('الهوية والمعلومات التي وجدناها','Identity and details we found')));for(const fact of facts){const value=()=>edits.facts.find(e=>e.id===fact.id)?.value??fact.value,title=factNames[fact.field]?.[ar?0:1]??fact.field;
  const r=row(`fact-${fact.id}`,title,()=>fact.field==='logoDataUrl'?el('small','',w('شعار المركز','Clinic logo')):el('small','',value()),()=>{const box=el('div');box.append(fact.field==='logoDataUrl'?image(value()):info(title,value()),info(w('النص الذي استخرجت منه المعلومة','Supporting information'),fact.evidence),link(fact.sourceUrl),info(w('حالة المعلومة','Information status'),w('مستخرجة، تحتاج مراجعتك','Extracted; awaiting your review')),context());return box;},(form,close,refresh)=>{const isLogo=fact.field==='logoDataUrl',max=isLogo?125000:fact.field==='website'?500:fact.field==='address'?400:fact.field.startsWith('subtitle')?240:120;
   if(fact.field==='phone'){let phone=value();const control=createPhoneInput({value:phone,label:title,language,testId:`import-phone-${fact.id}`,required:true,onChange:value=>{phone=value;}});form.append(control.node);editorActions(form,close,()=>{const existing=edits.facts.find(e=>e.id===fact.id);if(existing)existing.value=phone;else edits.facts.push({id:fact.id,value:phone});refresh();});return;}
   const f=field(isLogo?w('رابط بيانات الصورة PNG/JPEG/WebP','PNG/JPEG/WebP image data'):title,value(),max,isLogo||fact.field==='address'||fact.field.startsWith('subtitle'));f.input.required=true;if(f.input instanceof HTMLInputElement){f.input.type=fact.field==='email'?'email':fact.field==='website'?'url':'text';if(fact.field.endsWith('Color'))f.input.type='color';}form.append(f.node);
   if(isLogo){const upload=el('input');upload.type='file';upload.accept='image/png,image/jpeg,image/webp';upload.setAttribute('aria-label',w('رفع شعار جديد','Upload new logo'));upload.onchange=()=>{const file=upload.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{f.input.value=String(reader.result);f.input.setCustomValidity(safeLogo(f.input.value)?'':w('استخدم صورة أصغر من 90 كيلوبايت','Use an image smaller than 90 KB'));};reader.readAsDataURL(file);};f.input.oninput=()=>f.input.setCustomValidity('');form.append(upload);}
   editorActions(form,close,()=>{const existing=edits.facts.find(e=>e.id===fact.id);if(existing)existing.value=f.input.value.trim();else edits.facts.push({id:fact.id,value:f.input.value.trim()});refresh();});});if(fact.field==='primaryColor'||fact.field==='accentColor')r.check.checked=false;section.append(r.box);selectedFacts.push({id:fact.id,check:r.check});}root.append(section);}
 if(!color&&safeLogo(details.logoDataUrl))root.append(paletteSection);
 for(const kind of ['services','branches'] as const){if(!details[kind].length)continue;const section=el('div','jc-import-section');section.append(el('h2','',kind==='services'?w('الخدمات المنشورة','Published services'):w('الفروع المنشورة','Published branches')));details[kind].forEach((source,index)=>{
  const current=()=>({...source,...edits[kind].find(e=>e.index===index)}),r=row(`${kind}-${index}`,source.name,()=>{const item=current();const content=el('small','',`${item.name}\n${item.detail}`);return content;},()=>{const item=current(),box=el('div');box.append(info(w('الاسم','Name'),item.name),info(w('التفاصيل كاملة','Full details'),item.detail),link(source.sourceUrl),context());if(source.sourceKind==='indexed')box.append(info(w('طريقة العثور على المعلومة','How this information was found'),w('من نتيجة بحث عامة. تعذرت قراءة البوست مباشرة؛ راجع المصدر قبل الاعتماد.','From a public search result. The post could not be read directly; verify its source before approval.')));if(source.evidence)box.append(info(w('النص المنشور الذي يدعم المعلومة','Published supporting text'),source.evidence));if(kind==='services')box.append(info(w('بيانات الحجز','Booking details'),w('ستحدد السعر والمدة والموظفين والغرف في الخطوة التالية.','Set price, duration, staff and rooms in the next step.')),info(w('رتوش / موعد متابعة','Retouch / follow-up appointment'),(edits.services.find(e=>e.index===index)?.followUpEnabled??false)?w('متاح، السعر الافتراضي صفر','Enabled; default price zero'):w('غير مفعّل','Disabled')));return box;},(form,close,refresh)=>{
   const item=current(),name=field(w('الاسم','Name'),item.name,120),detail=field(w('التفاصيل','Details'),item.detail,1500,true);name.input.required=true;form.append(name.node,detail.node);editorActions(form,close,()=>{if(kind==='services'){const existing=edits.services.find(e=>e.index===index);const update={index,name:name.input.value.trim(),detail:detail.input.value.trim(),followUpEnabled:existing?.followUpEnabled??false};if(existing)Object.assign(existing,update);else edits.services.push(update);}else{const existing=edits.branches.find(e=>e.index===index),update={index,name:name.input.value.trim(),detail:detail.input.value.trim()};if(existing)Object.assign(existing,update);else edits.branches.push(update);}refresh();});});
  if(kind==='services'){const label=el('label','jc-import-follow-up'),check=el('input');check.type='checkbox';check.checked=edits.services.find(e=>e.index===index)?.followUpEnabled??false;check.disabled=busy;check.dataset.testid=`import-follow-up-${index}`;label.append(check,document.createTextNode(w('رتوش / موعد متابعة — السعر الافتراضي صفر','Retouch / follow-up — default price zero')));check.onchange=()=>{const existing=edits.services.find(e=>e.index===index);if(existing)existing.followUpEnabled=check.checked;else edits.services.push({index,name:source.name,detail:source.detail,followUpEnabled:check.checked});};r.box.append(label,el('p','jc-import-note',w('يمكن للطبيب أو مقدم الخدمة أو السكرتيرة تعديل السعر لكل موعد.','The doctor, service provider or secretary can change the price at each appointment.')));}
  section.append(r.box);(kind==='services'?selectedServices:selectedBranches).push(r.check);
 });root.append(section);}
 const missing:string[]=[];if(!safeLogo(details.logoDataUrl))missing.push(w('شعار المركز','Clinic logo'));if(!details.colors.length)missing.push(w('ألوان المركز','Clinic colors'));if(!details.services.length)missing.push(w('قائمة الخدمات','Services'));if(!details.branches.length&&!session.serviceWizard)missing.push(w('أسماء الفروع','Branch names'));if(!session.serviceWizard)missing.push(w('ساعات العمل والفريق والغرف','Opening hours, staff and rooms'));if(details.services.length)missing.push(w('المدة والسعر وتفاصيل الحجز','Duration, price and booking details'));
 const missingBox=el('div','jc-import-missing-box');missingBox.append(el('h2','',w('شو ناقص ونكمّله سوا؟','What is missing? We will complete it together.')));const list=el('ul');for(const item of missing)list.append(el('li','',item));missingBox.append(list);root.append(missingBox);
 const panels:HTMLElement[]=[],pageSize=1;
 for(const section of Array.from(root.querySelectorAll<HTMLElement>(':scope > .jc-import-section,:scope > .jc-import-missing-box')).filter(node=>!node.hidden)){
  const rows=Array.from(section.querySelectorAll<HTMLElement>(':scope > .jc-import-row'));
  if(rows.length<=pageSize){panels.push(section);continue;}
  for(let offset=0;offset<rows.length;offset+=pageSize){const panel=section.cloneNode(false) as HTMLElement;const heading=section.querySelector('h2');if(heading)panel.append(heading.cloneNode(true));panel.append(...rows.slice(offset,offset+pageSize));root.insertBefore(panel,section);panels.push(panel);}section.remove();
 }
 const pager=setupPager(root,panels,language,'concierge-import-pages');if(pager)root.insertBefore(pager,panels[0]!);
 root.append(el('p','jc-import-note',w('اختَر المعلومات الصحيحة ثم اعتمدها. سنكمل بيانات الحجز في الخطوات التالية.','Select the correct information and approve. Complete booking details in the next steps.')));
 const actions=el('div','jc-import-actions'),approveButton=button(w('موافق، اعتمد المعلومات','Approve these details'),()=>{const factIds=selectedFacts.filter(r=>r.check.checked).map(r=>r.id),serviceIndexes=selectedServices.flatMap((c,i)=>c.checked?[i]:[]),branchIndexes=selectedBranches.flatMap((c,i)=>c.checked?[i]:[]);approve({factIds,serviceIndexes,branchIndexes,logoColor:paletteCheck?.checked?paletteColor:null,edits:{facts:edits.facts.filter(e=>factIds.includes(e.id)),services:edits.services.filter(e=>serviceIndexes.includes(e.index)),branches:edits.branches.filter(e=>branchIndexes.includes(e.index))}});},'jc-button jc-primary','concierge-import-approve');approveButton.disabled=busy;
 const backButton=button(w('رجوع','Back'),back,'jc-button','concierge-import-back');backButton.disabled=busy;const skip=button(w('تخطى المعلومات وكمّل','Skip these details and continue'),()=>approve({factIds:[],serviceIndexes:[],branchIndexes:[],logoColor:null,edits:emptyImportEdits()}),'jc-link','concierge-import-skip');skip.disabled=busy;actions.append(backButton,approveButton,skip);root.append(actions);return root;
}
