import { reviewRecordPages, revealReviewField } from './review-pages';
import { createDefinition } from '@workspace/service-definition';
import { DAYS,KINDS,type Draft,type Kind,type Language,type Review,type Week,type Provision } from './contract';
import { el,button } from './dom';
import { text } from './copy';
import { setupPager } from './paging';
type Row=Draft[Kind][number];
const emptyWeek=()=>Object.fromEntries(DAYS.map(day=>[day,[]])) as unknown as Week;
export function buildReview(data:Review,language:Language,callbacks:{save:(draft:Draft)=>Promise<Review|void>;apply:(staff:Provision[])=>Promise<void>;back:()=>void;error:(message:string)=>void}):HTMLElement{
 const tr=(k:string)=>text(language,k),draft=structuredClone(data.draft),root=el('section','jc-review');root.dataset.testid='concierge-review';let dirty=false,busy=false;
 for(const service of draft.services){if(!service.branchScope&&service.branchKey){service.branchScope='branch';dirty=true;}else if(!service.branchScope&&draft.branches.length===1){service.branchScope='branch';service.branchKey=draft.branches[0]!.key;dirty=true;}if(service.currency!=='JOD'){service.currency='JOD';dirty=true;}}
 const header=el('div');header.append(el('h2','',tr('review')),el('p','jc-muted',tr('draftNote')),el('p','jc-muted',tr('scopeNote')));root.append(header);
 const warning=data.issues.length?el('p','jc-error',tr('missing')):null;if(warning){warning.setAttribute('role','status');root.append(warning);}
 const scheduleRenders=new Map<string,()=>void>();
 const staffHours=(row:Row)=>{if(!('workingHours' in row))return null;return draft.branches.find(b=>b.key===row.branchKey)?.openingHours??data.options.branches.find(b=>b.key===row.branchKey)?.openingHours??null;};
 const credentials=new Map<string,{password:HTMLInputElement;checks:Map<string,HTMLInputElement>}>();
 const savedRoles=new Map(draft.staff.map(p=>[p.key,p.role]));
 const total=KINDS.reduce((sum,k)=>sum+draft[k].length,0);if(!total)root.append(el('p','jc-notice',tr('noDraft')));
 const validField=(row:Row,field:string)=>{const value=(row as unknown as Record<string,unknown>)[field];if(field==='name')return typeof value==='string'&&value.trim().length>0;if(field==='timeZone'){try{return typeof value==='string'&&!!new Intl.DateTimeFormat('en',{timeZone:value}).resolvedOptions().timeZone;}catch{return false;}}if(field==='durationMinutes'||field==='capacity')return typeof value==='number'&&Number.isInteger(value)&&value>0&&value<=(field==='durationMinutes'?1440:1000);if(field==='price')return typeof value==='string'&&/^\d{1,9}(\.\d{1,3})?$/.test(value);if(field==='currency')return typeof value==='string'&&/^[A-Z]{3}$/.test(value);if(field==='branchKey'&&'branchScope' in row&&row.branchScope==='all')return true;if(field==='openingHours'||field==='workingHours'||field==='breaks'){if(!value)return false;return Object.values(value as Week).every(ranges=>ranges.every(range=>/^\d\d:\d\d$/.test(range.open)&&/^\d\d:\d\d$/.test(range.close)&&range.open<range.close));}return value!==null&&value!==undefined&&value!=='';};
 const invalid=(key:string,field:string)=>{const row=KINDS.flatMap(kind=>draft[kind] as Row[]).find(item=>item.key===key);return !!row&&data.issues.some(i=>i.key===key&&(i.field===field||i.field.startsWith(field+'.')))&&!validField(row,field);};
 let save:HTMLButtonElement,apply:HTMLButtonElement,confirm:HTMLInputElement;
 function markDirty(){dirty=true;data.draft=structuredClone(draft);if(save)save.disabled=false;if(apply)apply.disabled=true;if(confirm){confirm.checked=false;confirm.disabled=false;}if(warning)warning.textContent=language==='ar'?'كمّل الخانات المطلوبة قبل اعتماد الإعداد.':'Complete the required fields before confirming.';}
 function labelField(row:Row,key:string,input:HTMLInputElement|HTMLSelectElement){const id=`jc-${row.key}-${key}`;input.id=id;input.dataset.testid=`draft-${row.key}-${key}`;const wrap=el('div','jc-field'),label=el('label','jc-label',key==='address'?(language==='ar'?'موقع الفرع':'Branch address'):key==='mapUrl'?(language==='ar'?'رابط الخريطة':'Map link'):tr(key==='name'?'recordName':key)),hint=el('small','jc-muted',key==='currency'?(language==='ar'?'استخدم 3 أحرف مثل JOD':'Use 3 letters, for example JOD'):tr('required'));label.htmlFor=id;wrap.append(label,input,hint);const refresh=()=>{const bad=invalid(row.key,key);wrap.classList.toggle('jc-invalid',bad);input.setAttribute('aria-invalid',String(bad));hint.hidden=!bad;};input.addEventListener('input',refresh);input.addEventListener('change',refresh);refresh();return wrap;}
 function field(row:Row,key:string,type='text'){
  const input=el('input');input.type=type;const record=row as unknown as Record<string,unknown>;input.value=record[key]===null?'':String(record[key]??'');if(type==='text')input.maxLength=key==='address'?400:key==='name'?120:key==='timeZone'?100:200;if(key==='email')input.maxLength=200;if(key==='phone')input.maxLength=50;if(key==='price'){input.type='number';input.min='0';input.step='.001';}if(type==='number'){input.min='1';input.step='1';}if(['email','phone','timeZone','price','currency'].includes(key))input.dir='ltr';
  input.addEventListener('input',()=>{if(key==='currency'){input.value=input.value.toUpperCase();if(input.value==='JD')input.value='JOD';}record[key]=input.value===''?null:type==='number'?Number(input.value):input.value;if(key==='name')record.nameLang=/[\u0600-\u06ff]/u.test(input.value)?'ar':'en';markDirty();});
  const wrap=labelField(row,key,input);
  if(key==='price'){
   const currencyHint=el('small','jc-muted',language==='ar'?'الأسعار بالدينار الأردني (JOD).':'Prices are in Jordanian dinars (JOD).');
   currencyHint.id=`${input.id}-currency`;input.setAttribute('aria-describedby',currencyHint.id);wrap.append(currencyHint);
  }
  return wrap;
 }
 function select(row:Row,key:string,options:{value:string;label:string}[],emptyLabel='choose'){
  const input=el('select'),record=row as unknown as Record<string,unknown>;const blank=el('option','',tr(emptyLabel));blank.value='';input.append(blank);for(const opt of options){const o=el('option','',opt.label);o.value=opt.value;input.append(o);}input.value=record[key]===null?'':String(record[key]);input.onchange=()=>{record[key]=input.value===''?null:key==='requiresRoom'?input.value==='true':input.value;if(key==='branchKey'&&'workingHours' in row&&row.workingHours===null){const hours=staffHours(row);if(hours){row.workingHours=structuredClone(hours);scheduleRenders.get(row.key)?.();}}if(key==='branchKey'&&draft.services.some(service=>service.key===row.key))record.branchScope=input.value?'branch':'all';markDirty();};return labelField(row,key,input);
 }
 function schedule(row:Row,key:'openingHours'|'workingHours'|'breaks'){
  const record=row as unknown as Record<string,unknown>,fieldset=el('fieldset','jc-week jc-week-paged'),legend=el('legend','',tr(key));fieldset.append(legend);if(invalid(row.key,key))legend.append(el('span','',` · ${tr('required')}`));
  const body=el('div');fieldset.append(body);let dayPage=0;const rangePages=new Map<string,number>();
  const render=()=>{body.replaceChildren();const week=record[key] as Week|null,host=el('div','jc-schedule-pages'),days:HTMLElement[]=[],rangeHosts=new Map<string,HTMLElement>();const controls=el('div','jc-schedule-selects'),dayPicker=el('select'),rangePicker=el('select');dayPicker.dataset.testid=`draft-${row.key}-${key}-dayPicker`;dayPicker.setAttribute('aria-label',language==='ar'?'اليوم':'Day');rangePicker.dataset.testid=`draft-${row.key}-${key}-rangePicker`;rangePicker.setAttribute('aria-label',language==='ar'?'فترة الدوام':'Time interval');for(const [index,day] of DAYS.entries()){const option=el('option','',tr(day));option.value=String(index);dayPicker.append(option);}dayPicker.value=String(dayPage);controls.append(dayPicker,rangePicker);body.append(controls);
   if(!week){body.append(button(tr(key==='breaks'?'noBreaks':'closedWeek'),()=>{record[key]=emptyWeek();markDirty();render();},'jc-link'));}
   for(const day of DAYS){const line=el('div','jc-day'),dayLabel=el('div','jc-day-name',tr(day)),ranges=el('div','jc-ranges');line.append(dayLabel,ranges);const current=week?.[day]??[],rangeRows:HTMLElement[]=[];
    if(current.length===0)ranges.append(el('span','jc-muted',week?tr('closed'):tr('scheduleUnknown')));
    current.forEach((range,index)=>{const r=el('div','jc-range');for(const slot of ['open','close'] as const){const label=el('label','',tr(slot==='open'?'openTime':'closeTime')),input=el('input');input.type='time';input.value=range[slot];input.required=true;input.dataset.testid=`draft-${row.key}-${key}-${day}-${index}-${slot}`;input.setAttribute('aria-label',`${tr(day)} ${tr(key)} ${tr(slot==='open'?'openTime':'closeTime')}`);input.oninput=()=>{range[slot]=input.value;markDirty();};label.append(input);r.append(label);}r.append(button('×',()=>{current.splice(index,1);markDirty();render();},'jc-link'));(r.lastElementChild as HTMLElement).setAttribute('aria-label',tr('removeRange'));ranges.append(r);rangeRows.push(r);});rangeHosts.set(day,ranges);
    const rangePager=setupPager(ranges,rangeRows,language,`concierge-ranges-${row.key}-${key}-${day}`);if(rangePager)ranges.prepend(rangePager);
    ranges.addEventListener('click',()=>{rangePages.set(day,Number(ranges.dataset.setupPage)||0);});ranges.addEventListener('jormall:setup-page',event=>{rangePages.set(day,Number((event as CustomEvent).detail)||0);});ranges.dispatchEvent(new CustomEvent('jormall:setup-page',{detail:rangePages.get(day)??0}));
    const add=button(`+ ${tr('addRange')}`,()=>{if(!record[key])record[key]=emptyWeek();const w=record[key] as Week;w[day].push({open:'',close:''});rangePages.set(day,w[day].length-1);markDirty();render();},'jc-link');add.disabled=current.length>=8;ranges.append(add);host.append(line);days.push(line);
   }
   body.append(host);const nav=setupPager(host,days,language,`concierge-days-${row.key}-${key}`);if(nav)host.prepend(nav);host.addEventListener('click',()=>{dayPage=Number(host.dataset.setupPage)||0;});host.addEventListener('jormall:setup-page',event=>{dayPage=Number((event as CustomEvent).detail)||0;});host.dispatchEvent(new CustomEvent('jormall:setup-page',{detail:dayPage}));
   const fillRanges=()=>{rangePicker.replaceChildren();const day=DAYS[dayPage]!,count=(record[key] as Week|null)?.[day].length??0;rangePicker.hidden=count<2;for(let index=0;index<count;index++){const option=el('option','',language==='ar'?`الفترة ${index+1}`:`Interval ${index+1}`);option.value=String(index);rangePicker.append(option);}rangePicker.value=String(rangePages.get(day)??0);};fillRanges();dayPicker.onchange=()=>{dayPage=Number(dayPicker.value);host.dispatchEvent(new CustomEvent('jormall:setup-page',{detail:dayPage}));fillRanges();};rangePicker.onchange=()=>{rangeHosts.get(DAYS[dayPage]!)?.dispatchEvent(new CustomEvent('jormall:setup-page',{detail:Number(rangePicker.value)}));};
  };if(key==='workingHours')scheduleRenders.set(row.key,render);render();return fieldset;
 }
 const branchOptions=[...data.options.branches.map(b=>({value:b.key,label:b.name})),...draft.branches.filter(b=>!data.options.branches.some(e=>e.key===b.key)).map(b=>({value:b.key,label:b.name??tr('newRecord')}))];
 const serviceOptions=[...data.options.services.map(s=>({value:s.key,label:s.name})),...draft.services.map(s=>({value:s.key,label:s.name??tr('newRecord')}))];
 function services(row:Row){const record=row as unknown as Record<string,unknown>,set=el('fieldset','jc-selection');set.append(el('legend','',tr('serviceKeys')));const choices=[{value:'',label:tr('noServices')},...serviceOptions];const inputs:HTMLInputElement[]=[];
  for(const opt of choices){const label=el('label','jc-check'),check=el('input');check.type='checkbox';check.value=opt.value;const selected=record.serviceKeys as string[]|null;check.checked=opt.value?!!selected?.includes(opt.value):selected?.length===0;inputs.push(check);label.append(check,el('span','',opt.label));check.onchange=()=>{if(opt.value===''){if(check.checked)for(const c of inputs)if(c!==check)c.checked=false;}else if(check.checked)inputs[0]!.checked=false;const v=inputs.filter(c=>c.value&&c.checked).map(c=>c.value);record.serviceKeys=v.length?v:inputs[0]!.checked?[]:null;markDirty();};set.append(label);}if(!serviceOptions.length)set.append(el('p','jc-muted',tr('noCompatible')));return set;
 }
 for(const kind of KINDS){if(!draft[kind].length)continue;root.append(el('h3','',tr(kind)));
  for(const row of draft[kind]){const card=el('details','jc-record');card.open=!!data.issues.find(i=>i.key===row.key)||kind==='staff';card.dataset.testid=`draft-${row.key}`;const summary=el('summary','',row.name??tr('newRecord'));summary.lang=row.nameLang??language;card.append(summary);
   card.append(el('p','jc-record-meta','existingId' in row&&row.existingId!==null?tr('existing'):tr('newRecord')));
   const grid=el('div','jc-grid');grid.append(field(row,'name'),select(row,'nameLang',[{value:'ar',label:tr('ar')},{value:'en',label:tr('en')}]));
   if(kind==='branches'){(row as Draft['branches'][number]).timeZone='Asia/Amman';grid.append(field(row,'address'),field(row,'mapUrl','url'));card.append(grid,schedule(row,'openingHours'));}
   else {
    if(kind!=='services')grid.append(select(row,'branchKey',branchOptions,kind==='rooms'?'choose':'clinicWide'));
    else {const service=row as Draft['services'][number],scope=el('select');for(const choice of [{value:'',label:tr('choose')},{value:'all',label:tr('clinicWide')},...branchOptions]){const opt=el('option','',choice.label);opt.value=choice.value;scope.append(opt);}scope.value=service.branchScope==='all'?'all':service.branchKey??'';scope.onchange=()=>{service.branchScope=scope.value==='all'?'all':scope.value?'branch':null;service.branchKey=scope.value&&scope.value!=='all'?scope.value:null;markDirty();};grid.append(labelField(row,'branchScope',scope));}
    if(kind==='services'){const followLabel=el('label','jc-check'),follow=el('input');follow.type='checkbox';follow.checked=!!(row as Draft['services'][number]).followUpEnabled;follow.dataset.testid=`draft-${row.key}-followUpEnabled`;follow.onchange=()=>{(row as Draft['services'][number]).followUpEnabled=follow.checked;markDirty();};followLabel.append(follow,el('span','',language==='ar'?'رتوش / موعد متابعة — السعر الافتراضي صفر، قابل للتعديل لكل موعد':'Retouch / follow-up appointment — default zero, editable per appointment'));card.append(followLabel);grid.append(field(row,'durationMinutes','number'),field(row,'price'),select(row,'category',['Hair','Nails','Skin','Laser','Massage','Makeup','Other'].map(value=>({value,label:tr(value)}))),select(row,'requiresRoom',[{value:'true',label:tr('yes')},{value:'false',label:tr('no')} ]));const service=row as Draft['services'][number],custom=el('input'),customLabel=el('label','jc-field');custom.maxLength=80;custom.value=service.definition?.section??'';if(['خدمات العيادة','Clinic services'].includes(custom.value))custom.value='';custom.dataset.testid=`draft-${row.key}-customCategory`;customLabel.append(el('span','',language==='ar'?'اسم التصنيف الآخر':'Other category name'),custom);customLabel.hidden=service.category!=='Other';custom.oninput=()=>{if(custom.value.trim()){service.definition??={...createDefinition('custom',language),medicalScope:'medical'};service.definition.section=custom.value.trim();}else if(service.definition)service.definition.section=language==='ar'?'خدمات العيادة':'Clinic services';markDirty();};grid.querySelector<HTMLSelectElement>(`[data-testid="draft-${row.key}-category"]`)?.addEventListener('change',()=>{customLabel.hidden=service.category!=='Other';});grid.append(customLabel);card.append(grid);}
    if(kind==='rooms'){grid.append(field(row,'capacity','number'));card.append(grid,services(row));}
    if(kind==='staff'){
     grid.append(field(row,'email','email'),field(row,'phone','tel'),field(row,'jobTitle'),select(row,'role',['secretary','doctor','service_provider','other_staff'].map(value=>({value,label:tr(value)}))));card.append(grid,services(row),el('p','jc-muted',language==='ar'?'يبدأ دوام الموظف بنفس أيام وساعات عمل الفرع، ويمكنك تعديله.':'Staff start with the branch’s opening days and hours, which you can edit.'),button(language==='ar'?'استخدام ساعات عمل الفرع':'Use branch hours',()=>{const hours=staffHours(row);if(hours&&'workingHours' in row){row.workingHours=structuredClone(hours);scheduleRenders.get(row.key)?.();markDirty();}},'jc-link',`use-branch-hours-${row.key}`),schedule(row,'workingHours'),schedule(row,'breaks'));
     const secure=el('fieldset','jc-selection');secure.append(el('legend','',tr('accountReview')),el('p','jc-muted',language==='ar'?'كلمة مرور أولية، 10 أحرف على الأقل.':'Initial password, at least 10 characters.'));const password=el('input');password.type='password';password.minLength=10;password.maxLength=200;password.autocomplete='new-password';password.dir='ltr';password.dataset.testid=`password-${row.key}`;secure.append(labelField(row,'password',password));
     const pset=el('fieldset','jc-selection');pset.append(el('legend','',tr('permissions')));const permissions=el('div','jc-permissions'),checks=new Map<string,HTMLInputElement>();const defaults=data.staffAccess.find(s=>s.key===row.key)?.permissions??[];
     for(const permission of data.grantablePermissions){const [area,operation]=permission.split('.'),label=el('label','jc-check'),check=el('input');check.type='checkbox';check.checked=defaults.includes(permission);check.dataset.testid=`access-${row.key}-${permission}`;label.append(check,el('span','',`${tr(area!)} · ${tr(operation==='manage'?'managePermission':'readPermission')}`));checks.set(permission,check);permissions.append(label);}pset.append(permissions);secure.append(pset);card.append(secure);credentials.set(row.key,{password,checks});
    }
   }
   card.append(button(tr('remove'),()=>{if(!window.confirm(tr('deleteConfirm')))return;const list=draft[kind] as Row[],i=list.findIndex(r=>r.key===row.key);if(i>=0)list.splice(i,1);credentials.delete(row.key);card.remove();markDirty();root.dispatchEvent(new CustomEvent('jormall:setup-page',{detail:Number(root.dataset.setupPage)||0}));},'jc-link jc-remove',`remove-${row.key}`));reviewRecordPages(card,language,row.key);root.append(card);
  }
 }
 const cards=Array.from(root.querySelectorAll<HTMLElement>('.jc-record'));const pager=setupPager(root,cards,language,'concierge-review-pages');if(pager){root.classList.add('jc-paged-review');root.insertBefore(pager,cards[0]!);}
 const confirmation=el('label','jc-check');confirm=el('input');confirm.type='checkbox';confirm.dataset.testid='concierge-confirm';confirmation.append(confirm,el('span','',language==='ar'?'راجعت البيانات وأوافق على حفظ الإعداد.':'I reviewed the details and approve this setup.'));root.append(confirmation);
 const actions=el('div','jc-review-actions');
 save=button(tr('saveDraft'),()=>{if(busy)return;busy=true;disable(true);void callbacks.save(draft).catch(()=>{}).finally(()=>{busy=false;disable(false);});},'jc-button','concierge-save-draft');
 apply=button(language==='ar'?'اعتمد الإعداد':'Confirm setup',()=>{if(busy||!confirm.checked)return;const provision:Provision[]=[];
  for(const person of draft.staff){if(savedRoles.get(person.key)!==person.role){callbacks.error(tr('missing'));return;}const c=credentials.get(person.key)!;if(c.password.value.length<10){callbacks.error(tr('passwordRequired'));const card=c.password.closest<HTMLDetailsElement>('.jc-record');if(card){const index=Array.from(root.querySelectorAll('.jc-record')).indexOf(card);root.dispatchEvent(new CustomEvent('jormall:setup-page',{detail:index}));card.open=true;revealReviewField(card,c.password);}c.password.focus();return;}provision.push({key:person.key,initialPassword:c.password.value,permissions:[...c.checks].filter(([,input])=>input.checked).map(([p])=>p)});}
  busy=true;disable(true);void (async()=>{if(dirty){const fresh=await callbacks.save(draft);if(!fresh||fresh.issues.length)return;}await callbacks.apply(provision);})().catch(()=>{}).finally(()=>{for(const p of provision)p.initialPassword='';busy=false;disable(false);});
 },'jc-button jc-primary','concierge-apply');
 function disable(value:boolean){for(const c of root.querySelectorAll<HTMLInputElement|HTMLButtonElement|HTMLSelectElement>('input,button,select'))c.disabled=value;if(!value){save.disabled=!dirty;apply.disabled=!confirm.checked||(!dirty&&data.issues.length>0)||total===0;confirm.disabled=false;root.dispatchEvent(new CustomEvent('jormall:setup-page',{detail:Number(root.dataset.setupPage)||0}));}}
 confirm.onchange=()=>{apply.disabled=!confirm.checked||(!dirty&&data.issues.length>0)||total===0;};
 actions.append(button(tr('back'),()=>{for(const c of credentials.values())c.password.value='';callbacks.back();},'jc-link','concierge-review-back'),save,apply);root.append(actions);disable(false);return root;
}
