import { WorkspaceIdentityPanel } from '../workspace/identity-panel';
import type { WorkspaceProfile } from '@workspace/service-definition';
import { normalizeServiceName } from '@workspace/service-definition';
import type { WorkspaceSection } from '../workspace/surface';
import { createElement } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { ServiceWizardPanel } from '../services/service-wizard-panel';
import type { ServiceOptions, ServiceDraft } from './contract';
import { safeLogo, logoPalette } from './branding';
import { ConciergeAPI, ConciergeHTTPError, createRequestId } from './api';
import { KINDS,type Bootstrap,type Capabilities,type Language,type Session,type Review,type Draft,type Provision } from './contract';
import { text,errorText } from './copy';
import { el,button,iconButton } from './dom';
import { LiquidOrb } from './orb';
import { SpeechPlayer } from './voice';
import { RealtimeVoiceSession } from './realtime-voice';
import { buildReview } from './review';
const SAFE_PATHS=new Set(['/home','/business/settings','/business/services','/business/rooms','/people/employees','/appointments/view','/appointments/new','/people/customers','/appointments/waiting-list','/business/inventory']);
export type ConciergeOptions={userId:number;onNavigate:(path:string)=>void;onApplied:()=>void;onStaffHelp:()=>void};
/** Production UI controller, embedded in React by manager-concierge.tsx. All state comes from the API. */
export class ConciergeView {
 private sideHost=el('div','jc-service-host');private identityHost=el('div','jc-identity-host');private identityPanel:WorkspaceIdentityPanel|null=null;private resettingEditors=false;private serviceEditing=false;private workspaceEditing=false;private wizardHost=el('div','jc-service-data');private wizardRoot:Root|null=null;private serviceOptions:ServiceOptions|null=null;private optionsLoading=false;private optionsError=false;private servicePreviews:ServiceDraft[]=[];private editorBusy=false;
 private linkEntry=false;private linksText='';private entry=true;private introduction=false;private focusLayer=el('div','jc-focus-layer');private lastAssistantReply='';private uploadDismissed=false;private showSetupPanel=false;
 private overviewParts:string[]=[];private awaitingOverview=false;private overviewSubmitted=false;
 private get dismissedKey(){return `jormall:concierge-later:${this.options.userId}`;}
 private guideGeneration=0;private typing=false;private guidedValues=new Map<string,string>();
 private recordReviewEvent=(event:Event)=>{void this.reviewRecord((event as CustomEvent<{resource:string;key:string;fields:Record<string,unknown>}>).detail);};
 private async reviewRecord(detail:{resource:string;key:string;fields:Record<string,unknown>}){if(!this.session||this.busy||!detail)return;const kind=detail.resource==='employees'?'staff':detail.resource;if(!KINDS.includes(kind as typeof KINDS[number]))return;this.busy=true;this.guideGeneration++;window.dispatchEvent(new Event('jormall:concierge-stop-typing'));this.typing=false;try{while(this.voiceSaving&&!this.closed)await new Promise(resolve=>setTimeout(resolve,60));if(this.closed)return;const draft=structuredClone(this.session.draft),rows=draft[kind as keyof Draft] as unknown as Record<string,unknown>[];const row=rows.find(r=>r.key===detail.key);if(!row){this.busy=false;return;}for(const [key,value] of Object.entries(detail.fields))if(key!=='key'&&Object.hasOwn(row,key))row[key]=value;this.session=await this.api.request<Session>('/draft',{revision:this.session.revision,draft},'PUT');if(this.closed)return;this.busy=false;await this.openReview();}catch(err){this.busy=false;this.showError(err);}}
 readonly dialog=el('dialog','jc-dialog');private launcher:HTMLButtonElement;private stage=el('div','jc-stage');private canvas=el('canvas','jc-orb');private orb:LiquidOrb;private top=el('div','jc-top');private controls=el('div','jc-controls');private caption=el('h1','jc-caption');private status=el('div','jc-status');private errorBox=el('div','jc-error');private notice=el('div','jc-notice');private transcript=el('div','jc-transcript');private guideOrb=el('div','jc-guide-orb');private guidePath='';private guideTimer=0;private guidedRecords=new Set<string>();private language:Language='ar';private controller=new AbortController();private api=new ConciergeAPI(this.controller.signal);private player=new SpeechPlayer(this.api,n=>this.orb.setLevel(n));private mic:RealtimeVoiceSession|null=null;private caps:Capabilities|null=null;private session:Session|null=null;private companySearching=false;private companyQuery='';private busy=false;private fileBusy=false;private speaking=false;private voiceState:'connecting'|'listening'|'speaking'|'paused'|'off'='off';private closed=true;private disposed=false;private booting=false;private voicePreferred=false;private needsAudioClick=false;private keyboard=false;private uploadOpen=false;private modeChoice:'voice'|'text'|null=null;private review:Review|null=null;private speakTicket=0;private lastFocus:HTMLElement|null=null;private composing='';private pendingTurn:{text:string;id:string}|null=null;private voiceTurns:{text:string;id:string}[]=[];private voiceSaving=false;
 constructor(private options:ConciergeOptions){
  this.dialog.dataset.testid='concierge-dialog';this.dialog.setAttribute('aria-labelledby','jc-title');this.caption.id='jc-title';this.caption.setAttribute('aria-live','polite');this.status.setAttribute('role','status');this.errorBox.setAttribute('role','alert');this.notice.setAttribute('role','status');this.transcript.setAttribute('aria-live','off');this.errorBox.hidden=true;this.notice.hidden=true;
  const orbWrap=el('div','jc-orb-wrap');orbWrap.append(this.canvas);this.canvas.setAttribute('aria-hidden','true');orbWrap.dataset.testid='concierge-orb';this.stage.append(orbWrap,this.status,this.caption,this.controls,this.transcript,this.errorBox,this.notice);this.sideHost.hidden=true;this.sideHost.append(this.identityHost,this.wizardHost);this.dialog.append(this.top,this.stage,this.sideHost);this.focusLayer.setAttribute('aria-hidden','true');this.guideOrb.setAttribute('aria-hidden','true');this.guideOrb.append(el('span','jc-cursor-label','AI'));document.body.append(this.focusLayer,this.dialog,this.guideOrb);this.orb=new LiquidOrb(this.canvas);this.orb.pause();
  this.launcher=button(text(this.language,'open'),()=>void this.open(true),'jc-launcher','concierge-open');this.launcher.setAttribute('aria-haspopup','dialog');this.launcher.hidden=true;document.body.append(this.launcher);
  this.dialog.addEventListener('cancel',e=>{e.preventDefault();this.close();});this.dialog.addEventListener('close',()=>{if(!this.closed)this.close();});
  document.addEventListener('visibilitychange',this.visibility);window.addEventListener('pagehide',this.visibility);window.addEventListener('jormall:concierge-open',this.openEvent);window.addEventListener('jormall:concierge-field',this.fieldEvent);window.addEventListener('jormall:concierge-review-record',this.recordReviewEvent);this.dialog.addEventListener('keydown',this.trapFocus);void this.autoOpen();
 }
 private t=(key:string)=>text(this.language,key);
 private openEvent=()=>{void this.open(true);};
 private trapFocus=(event:KeyboardEvent)=>{if(event.key!=='Tab'||!this.focusLayer.classList.contains('jc-focus-visible'))return;const items=Array.from(this.dialog.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),a[href]')).filter(x=>x.offsetParent!==null);if(!items.length)return;const first=items[0]!,last=items.at(-1)!;if(event.shiftKey&&(document.activeElement===first||!this.dialog.contains(document.activeElement))){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};
private fieldEvent=(event:Event)=>{const detail=(event as CustomEvent<{target?:HTMLElement;done?:boolean;cancelled?:boolean;preview?:boolean}>).detail;if(this.closed)return;if(detail?.done){this.typing=false;this.guideOrb.classList.remove('jc-cursor-writing');if(!detail.cancelled)this.guideTimer=window.setTimeout(()=>this.guideFromSession(''),120);return;}if(detail?.target?.isConnected){if(!detail.preview)this.typing=true;const rect=detail.target.getBoundingClientRect();this.guideOrb.style.transform=`translate3d(${Math.min(innerWidth-70,Math.max(8,rect.right-26))}px,${Math.max(8,rect.top+rect.height/2)}px,0)`;this.guideOrb.classList.add('jc-guide-active');this.guideOrb.classList.toggle('jc-cursor-writing',!detail.preview);}};
 private presentation(){const focused=this.linkEntry||this.entry||!this.session?.serviceWizard&&(this.introduction||!!this.review||this.uploadOpen||!!this.session?.companyCandidate||this.companySearching);this.focusLayer.classList.toggle('jc-focus-visible',focused&&!this.closed);this.focusLayer.classList.toggle('jc-focus-soft',this.introduction);this.dialog.classList.toggle('jc-guided',!focused&&!this.session?.serviceWizard&&this.session?.stage==='conversation');this.dialog.dataset.flow=this.linkEntry?'links':this.entry?'entry':this.introduction?'intro':this.uploadOpen?'upload':this.review?'review':this.companySearching?'company-search':this.session?.companyCandidate?'company':'workspace';this.dialog.setAttribute('aria-modal',String(focused));const root=document.getElementById('root');if(root)root.inert=focused&&!this.closed;window.dispatchEvent(new CustomEvent('jormall:concierge-workspace',{detail:{active:!this.closed&&!this.entry}}));}
 private visibility=()=>{if(document.hidden||!this.dialog.open){this.stopVoice();this.stopSpeech();if(!this.closed)this.showNotice('hidden');}};
 private async autoOpen(){try{const initial=await this.api.request<Bootstrap>('/bootstrap');if(this.disposed)return;this.caps=initial.capabilities;this.session=initial.session;this.language=initial.session?.language??'ar';this.launcher.textContent=this.t('open');this.launcher.hidden=true;}catch(err){if(this.disposed)return;if(err instanceof ConciergeHTTPError&&err.status===404){this.launcher.hidden=true;return;}}}
 async open(reopen=false,initial?:Bootstrap){
  if(this.disposed||this.booting)return;if(!this.closed){this.dialog.focus();return;}if(reopen)localStorage.removeItem(this.dismissedKey);this.booting=true;this.closed=false;this.controller.abort();this.controller=new AbortController();this.api=new ConciergeAPI(this.controller.signal);this.player.dispose();this.player=new SpeechPlayer(this.api,n=>this.orb.setLevel(n));this.lastFocus=document.activeElement as HTMLElement;this.dialog.show();this.orb.resume();this.launcher.hidden=true;this.busy=true;this.render();
  try{let data=initial??await this.api.request<Bootstrap>('/bootstrap');if(this.closed)return;
   if(!data.session||!data.session.workspace||!data.session.serviceWizard&&data.session.stage!=='complete'||data.session.stage==='name'||data.session.stage==='complete'||reopen&&data.session.stage==='manual'||data.session?.stage==='conversation'&&!data.session.consented&&data.session.entryMode!=='manual')data=await this.api.request<Bootstrap>('/start',{language:data.session?.language??this.language,reopen:reopen||data.session?.stage==='complete'});
   if(this.closed)return;this.caps=data.capabilities;this.session=data.session;this.language=data.session?.language??this.language;this.busy=false;if(this.session?.serviceWizard&&['conversation','complete'].includes(this.session.stage)){this.entry=true;this.keyboard=this.session.entryMode==='text'&&(this.session.consented||!this.caps?.llm);}this.render();
   // Entry stays silent until the user chooses voice; refreshes never consume speech quota.
  }catch(err){if(!this.closed){this.busy=false;this.render();this.showError(err);}}finally{this.booting=false;}
 }
 close(){if(this.closed)return;if(this.editorBusy&&!this.disposed&&!window.confirm(this.language==='ar'?'إغلاق المعالج وإلغاء التعديلات اليدوية غير المحفوظة؟':'Close the wizard and discard unsaved manual edits?'))return;if(!this.disposed&&this.session?.stage!=='complete')localStorage.setItem(this.dismissedKey,'1');this.resetEditors();this.servicePreviews=[];this.closed=true;this.guideGeneration++;clearTimeout(this.guideTimer);this.guidePath='';this.guideOrb.classList.remove('jc-guide-active');this.controller.abort();this.stopVoice();this.stopSpeech();this.modeChoice=null;this.review=null;this.showSetupPanel=false;this.keyboard=false;this.uploadOpen=false;this.entry=true;this.linkEntry=false;this.companySearching=false;this.introduction=false;this.awaitingOverview=false;this.overviewParts=[];this.presentation();window.dispatchEvent(new Event('jormall:concierge-stop-typing'));this.pendingTurn=null;this.composing='';this.fileBusy=false;this.errorBox.hidden=true;this.notice.hidden=true;this.controls.replaceChildren();this.orb.pause();this.dialog.close();this.launcher.hidden=true;this.lastFocus?.focus();}
 dispose(){this.disposed=true;this.close();this.controller.abort();this.player.dispose();this.orb.dispose();document.removeEventListener('visibilitychange',this.visibility);window.removeEventListener('pagehide',this.visibility);window.removeEventListener('jormall:concierge-open',this.openEvent);window.removeEventListener('jormall:concierge-field',this.fieldEvent);window.removeEventListener('jormall:concierge-review-record',this.recordReviewEvent);this.dialog.remove();this.launcher.remove();this.guideOrb.remove();this.focusLayer.remove();}
 private showError(err:unknown){if(this.closed||err instanceof ConciergeHTTPError&&err.status===401)return;const code=err instanceof ConciergeHTTPError?err.code:err instanceof Error?err.message:'error';if(code==='concierge_access_changed'){this.stopVoice();this.stopSpeech();this.session=null;this.review=null;this.render();this.controls.append(button(this.t('restart'),()=>void this.restart(),'jc-button'));}this.errorBox.textContent=code==='offline'?this.t('offline'):errorText(this.language,code);this.errorBox.hidden=false;if(['concierge_stale','concierge_busy','concierge_stream_interrupted'].includes(code)&&!this.controls.querySelector('[data-testid=concierge-reload-draft]'))this.controls.append(button(this.language==='ar'?'تحديث المسودة من السيرفر':'Reload draft from server',()=>void this.refresh(),'jc-button','concierge-reload-draft'));}
 private showNotice(key:string){this.notice.textContent=this.t(key);this.notice.hidden=false;}
 private clearError(){this.errorBox.hidden=true;this.notice.hidden=true;}
 private stopSpeech(){this.speakTicket++;this.player.stop();this.speaking=false;this.updateStatus();}
 private stopVoice(){this.mic?.stop();this.mic=null;this.voiceState='off';this.transcript.textContent='';this.updateStatus();}
 private updateStatus(){const processing=this.voiceSaving||this.fileBusy||this.busy,voiceSpeaking=this.voiceState==='speaking';const key=this.fileBusy?'fileReading':this.busy||this.voiceSaving?'thinking':this.speaking||voiceSpeaking?'speaking':this.voiceState==='connecting'?'voiceConnecting':this.voiceState==='listening'?'listening':this.voiceState==='paused'?'paused':'ready';this.status.textContent=this.t(key);this.status.dataset.active=String(this.speaking||voiceSpeaking||this.voiceState==='listening');this.status.dataset.busy=String(processing||this.voiceState==='connecting');this.dialog.dataset.phase=processing?'processing':this.speaking||voiceSpeaking?'speaking':this.voiceState==='listening'?'listening':'idle';this.orb?.setActive(processing||this.speaking||voiceSpeaking||this.voiceState==='listening');}
 private render(){if(this.closed)return;this.dialog.lang=this.language;this.dialog.dir=this.language==='ar'?'rtl':'ltr';this.caption.dir=this.dialog.dir;this.dialog.classList.toggle('jc-review-mode',!!this.review);this.presentation();this.renderWizard();this.controls.replaceChildren();this.top.replaceChildren();this.launcher.textContent=this.t('open');
  const actions=el('div','jc-top-actions');const switcher=button(this.language==='ar'?'English':'العربية',()=>void this.switchLanguage(),'jc-link','concierge-language');switcher.disabled=this.busy||!!this.review||this.editorBusy;actions.append(button(this.t('guide'),()=>{this.close();if(this.closed)this.options.onStaffHelp();},'jc-link','concierge-staff-help'),switcher,button(this.t('close'),()=>this.close(),'jc-link','concierge-close'));this.top.append(el('span','jc-brand',this.t('brand')),actions);
  this.caption.textContent=this.linkEntry?(this.language==='ar'?'استيراد معلومات العيادة من روابط أو PDF':'Import clinic details from links or PDF'):this.entry?this.session?.serviceWizard?(this.language==='ar'?'شو بدك تغيّر بنظامك؟':'What would you like to change in your system?'):this.t('entryTitle'):this.introduction?(this.lastAssistantReply||this.t('introText')):this.awaitingOverview?(this.language==='ar'?'احكي كل شي عن عيادتك. لما تخلص، قول «خلصت» أو اضغط الزر.':'Tell me everything about your clinic. Say “I’m done” or press the button when finished.'):this.uploadOpen?this.t('uploadTitle'):this.review?this.t('review'):this.session?.serviceWizard?(this.language==='ar'?'شو بدك تغيّر بنظامك؟':'What would you like to change in your system?'):this.lastAssistantReply||this.session?.message.text||this.t('loading');this.updateStatus();
  if(this.linkEntry){this.linksView();return;}
  if(this.entry&&this.session){this.choiceView();return;}
  if(this.introduction){this.controls.append(el('p','jc-intro-note',this.t('introNote')));return;}
  if(this.uploadOpen){this.uploadView(this.controls);return;}
  if(this.review&&this.session?.serviceWizard){const box=el('div','jc-review-dock');box.append(el('p','jc-muted',this.language==='ar'?'راجع التغييرات في اللوحة، أو احكي التعديل كتابة أو بالصوت قبل الموافقة.':'Review the changes, or request an edit by text or voice before approval.'));
   box.append(button(this.showSetupPanel?(this.language==='ar'?'إخفاء المراجعة':'Hide review'):(this.language==='ar'?'إظهار المراجعة':'Show review'),()=>{this.showSetupPanel=!this.showSetupPanel;this.renderWizard();this.render();},'jc-button','concierge-toggle-review'));
   box.append(button(this.language==='ar'?'تعديل الهوية والخدمات':'Edit identity and services',()=>{this.review=null;this.showSetupPanel=true;this.render();},'jc-button','concierge-edit-setup'));
   this.appendSetupNavigation(box);
   if(this.session.consented||!this.caps?.llm){const form=el('form','jc-compose');const area=el('textarea');area.value=this.composing;area.placeholder=this.language==='ar'?'اكتب شو بدك تعدّل بالعيادة…':'Describe what to change in the clinic…';area.maxLength=6000;area.setAttribute('aria-label',this.language==='ar'?'طلب تعديل':'Edit request');area.dataset.testid='concierge-review-message';area.oninput=()=>{this.composing=area.value;};const send=el('button','jc-button jc-primary',this.language==='ar'?'أرسل التعديل':'Send edit');send.type='submit';form.append(area,send);form.onsubmit=event=>{event.preventDefault();this.review=null;this.render();void this.sendTurn(area.value,true);};box.append(form);}
   if(this.caps?.voice)box.append(button(this.language==='ar'?'تعديل بالصوت':'Edit by voice',()=>{this.review=null;this.showSetupPanel=false;this.render();if(this.session?.consented)void this.startVoice();else void this.beginVoice();},'jc-button','concierge-review-voice'));
   this.controls.append(box);return;}
  if(this.review){this.controls.style.maxWidth='820px';this.controls.append(buildReview(this.review,this.language,{save:d=>this.saveDraft(d),apply:p=>this.apply(p),back:()=>{this.review=null;this.render();},error:m=>{this.errorBox.textContent=m;this.errorBox.hidden=false;}}));if(this.session?.sourceImport)this.controls.append(button(this.language==='ar'?'كمّل إضافة البيانات من الإعدادات اليدوية':'Continue adding details in manual settings',()=>this.go('/business/settings'),'jc-button','concierge-import-manual'));return;}
  this.controls.style.maxWidth='600px';
  if(!this.session){this.controls.append(button(this.t('refresh'),()=>void this.refresh(),'jc-button','concierge-refresh'),button(this.t('manual'),()=>this.go('/business/settings'),'jc-link'));return;}
  const s=this.session;
  if(s.stage==='name')this.nameView();
  else if(s.stage==='choice')this.modeChoice?this.consentView():this.choiceView();
  else if(s.stage==='conversation')this.conversationView();
  else if(s.stage==='complete')this.completeView();
  else this.controls.append(button(this.t('enter'),()=>this.go('/business/settings'),'jc-button jc-primary'));
  if(this.needsAudioClick&&!this.review){const sound=button(this.t('enableSound'),()=>{void this.player.unlock().then(()=>{this.needsAudioClick=false;void this.speakMessage(true);}).catch(()=>this.showNotice('audioBlocked'));},'jc-link jc-small','concierge-sound');this.controls.append(sound);}
  if(this.editorBusy)this.disableControls(true);
  if(s.busy){this.showNotice('busy');this.controls.append(button(this.t('refresh'),()=>void this.refresh(),'jc-link'));}
 }
 private nameView(){const form=el('form','jc-name-form jc-panel-step');form.dataset.testid='concierge-name-form';const label=el('label','jc-label',this.t('name'));label.htmlFor='jc-name';const input=el('input');input.id='jc-name';input.name='preferredName';input.autocomplete='given-name';input.maxLength=80;input.required=true;input.placeholder=this.t('namePlaceholder');input.dataset.testid='concierge-name';const submit=el('button','jc-button jc-primary',this.t('next'));submit.type='submit';submit.disabled=this.busy;submit.dataset.testid='concierge-name-next';form.append(label,input,submit);form.onsubmit=e=>{e.preventDefault();if(this.busy||!input.value.trim())return;void this.mutate('/name',{name:input.value.trim(),revision:this.session!.revision,language:this.language});};this.controls.append(form);if(!this.busy)setTimeout(()=>{if(input.isConnected&&!this.closed)input.focus();},150);}
 private choiceView(){const block=el('div','jc-entry-content'),choices=el('div','jc-mode-grid');block.append(el('p','jc-entry-subtitle',this.session?.serviceWizard?(this.language==='ar'?'أضف خدمة، عدّل أو احذف خدمة، غيّر هوية العيادة، أو أكمل البيانات الناقصة. كل تغيير تراجعه قبل حفظه.':'Add, edit or remove a service, change your clinic identity, or complete missing details. Review each change before saving.'):this.t('entrySubtitle')));
  const voice=button('',()=>void this.beginVoice(),'jc-mode-card jc-mode-voice','concierge-voice-choice');voice.append(el('span','jc-mode-icon','◉'),el('strong','',this.t('voice')),el('span','jc-mode-description',this.t('voiceDescription')),el('span','jc-mode-action',this.t('voiceAction')));voice.disabled=this.busy||!this.caps?.voice;
  const manual=button('',()=>void this.manual(),'jc-mode-card','concierge-manual');manual.append(el('span','jc-mode-icon','⌨'),el('strong','',this.t('manual')),el('span','jc-mode-description',this.t('manualDescription')),el('span','jc-mode-action',this.t('manualAction')));const links=button('',()=>{this.stopVoice();this.stopSpeech();this.voicePreferred=false;this.entry=false;this.linkEntry=true;this.render();},'jc-mode-card','concierge-links-choice');links.disabled=this.busy;links.append(el('span','jc-mode-icon','↗'),el('strong','',this.language==='ar'?'روابط أو ملف PDF':'Links or PDF'),el('span','jc-mode-description',this.language==='ar'?'أضف موقع العيادة أو روابطها، أو ارفع ملف PDF عنها. راجع كل معلومة قبل الحفظ.':'Add your clinic website or social links, or upload a PDF. Review every fact before saving.'),el('span','jc-mode-action',this.language==='ar'?'أضف المصادر ←':'Add sources →'));const chat=button('',()=>void this.beginText(),'jc-mode-card','concierge-text-choice');chat.append(el('span','jc-mode-icon','✎'),el('strong','',this.language==='ar'?'شات كتابة':'Text chat'),el('span','jc-mode-description',this.session?.serviceWizard?(this.language==='ar'?'اكتب شو بدك تغيّر بنظام العيادة، وبنشوف التعديل سوا قبل الحفظ.':'Describe the change you want in the clinic system, then review it before saving.'):this.language==='ar'?'احكي عن عيادتك كتابة، وبنجهز التفاصيل معك خطوة خطوة.':'Describe your clinic by typing, and we will set it up step by step.'),el('span','jc-mode-action',this.language==='ar'?'ابدأ الشات ←':'Start chat →'));choices.append(voice,chat,manual,links);block.append(choices,el('p','jc-entry-consent',this.t('voiceConsent')));if(!this.caps?.voice)block.append(el('p','jc-config',this.t('voiceUnavailable')));this.controls.append(block);
 }
 private linksView(){
  const form=el('form','jc-panel-step jc-compose'),input=el('textarea');input.value=this.linksText;input.rows=5;input.maxLength=2500;input.placeholder='https://your-clinic.com\nhttps://instagram.com/your-clinic';input.setAttribute('aria-label',this.language==='ar'?'روابط الموقع والسوشال، كل رابط بسطر':'Website and social links, one per line');input.dataset.testid='concierge-links-input';input.dir='ltr';input.disabled=this.busy;input.oninput=()=>{this.linksText=input.value;};
  const submit=el('button','jc-button jc-primary',this.language==='ar'?'استورد الروابط':'Import links');submit.type='submit';submit.disabled=this.busy;submit.dataset.testid='concierge-links-submit';form.append(input,el('p','jc-muted',this.language==='ar'?'حتى 5 روابط عامة. يقرأ الخادم بيانات الصفحات المتاحة، وتراجع كل معلومة قبل الحفظ.':'Up to 5 public links. The server reads available page metadata; review each fact before saving.'),submit);form.onsubmit=e=>{e.preventDefault();void this.importLinks();};
  const pdf=el('div','jc-pdf-import'),picker=el('input');picker.type='file';picker.accept='.pdf,application/pdf';picker.hidden=true;picker.dataset.testid='concierge-links-pdf';picker.onchange=()=>{const file=picker.files?.[0];if(file)void this.importPdfFromLinks(file);};const choose=button(this.language==='ar'?'ارفع ملف PDF عن العيادة':'Upload a clinic PDF',()=>picker.click(),'jc-button','concierge-links-pdf-choose');choose.disabled=this.busy||!this.caps?.llm;pdf.append(el('strong','',this.language==='ar'?'عندك بروفايل العيادة PDF؟':'Have a clinic profile PDF?'),el('p','jc-muted',this.language==='ar'?'ارفع ملفًا حتى 8 MB. سنستخرج اقتراحات للمراجعة، بدون تفعيل خدمات تلقائيًا.':'Upload up to 8 MB. We will propose details for review, without activating services automatically.'),picker,choose);if(!this.caps?.llm)pdf.append(el('p','jc-muted',this.language==='ar'?'رفع PDF يحتاج تفعيل OpenAI على السيرفر. الروابط متاحة الآن.':'PDF reading needs OpenAI configured on the server. Links are available now.'));
  this.controls.append(form,pdf,button(this.t('back'),()=>{if(this.busy)return;this.linkEntry=false;this.entry=true;this.render();},'jc-link'));
 }
 private async importPdfFromLinks(file:File){
  if(this.busy||!this.session)return;if(!/\.pdf$/i.test(file.name)||file.size===0){this.showNotice('unsupportedFile');return;}if(file.size>(this.caps?.uploadMaxBytes??8*1024*1024)){this.showNotice('fileTooBig');return;}
  if(!this.session.consented&&!window.confirm(this.language==='ar'?'سيُرسل ملف PDF إلى OpenAI لاستخراج معلومات إعداد العيادة. لا ترفع بيانات مرضى أو كلمات مرور. موافق؟':'This PDF will be sent to OpenAI to extract clinic setup details. Do not upload patient records or passwords. Continue?'))return;
  this.busy=true;this.fileBusy=true;this.clearError();this.render();
  try{if(['complete','manual'].includes(this.session.stage)){const opened=await this.api.request<Bootstrap>('/start',{language:this.language,reopen:true});if(this.closed)return;this.session=opened.session;}if(!this.session)return;
   this.session=await this.api.request<Session>('/mode',{mode:'text',revision:this.session.revision,consent:true});if(this.closed)return;
   this.session=await this.api.upload<Session>(file,this.session.revision,createRequestId());if(this.closed)return;this.entry=false;this.linkEntry=false;this.uploadOpen=false;this.fileBusy=false;this.busy=false;this.render();
  }catch(err){if(this.closed)return;this.fileBusy=false;this.busy=false;this.linkEntry=true;this.render();this.showError(err);}
 }
 private async importLinks(){if(this.busy||!this.session)return;let urls:string[];try{urls=this.linksText.trim().split(/\s+/).filter(Boolean).map(value=>{const url=new URL(/^https?:\/\//i.test(value)?value:'https://'+value);if(url.protocol!=='https:'||url.username||url.password||url.port&&url.port!=='443'||url.href.length>500)throw Error();return url.href;});if(!urls.length||urls.length>5)throw Error();}catch{this.errorBox.textContent=this.language==='ar'?'حط من رابط واحد لخمس روابط عامة صحيحة.':'Enter one to five valid public HTTPS links.';this.errorBox.hidden=false;return;}this.busy=true;this.clearError();this.render();try{if(['complete','manual'].includes(this.session.stage)){const data=await this.api.request<Bootstrap>('/start',{language:this.language,reopen:true});if(this.closed)return;this.session=data.session;}if(!this.session)return;this.session=await this.api.request<Session>('/mode',{mode:'manual',revision:this.session.revision,consent:false});if(this.closed)return;this.entry=false;this.linkEntry=false;this.companySearching=true;this.companyQuery=urls.join(' · ');this.render();const session=await this.api.request<Session>('/import-links',{revision:this.session.revision,urls});if(this.closed)return;this.session=session;this.companySearching=false;this.busy=false;this.lastAssistantReply='';this.render();}catch(err){if(this.closed)return;this.companySearching=false;this.busy=false;this.linkEntry=true;this.render();this.showError(err);}}
 private async beginVoice(){if(this.busy||this.editorBusy||!this.session)return;if(!this.entry&&!this.session.consented&&!window.confirm(this.t('voiceConsent')))return;this.clearError();this.busy=true;this.render();try{if(['complete','manual'].includes(this.session.stage)){const opened=await this.api.request<Bootstrap>('/start',{language:this.language,reopen:true});if(this.closed)return;this.session=opened.session;}if(!this.session)return;const session=await this.api.request<Session>('/mode',{mode:'voice',revision:this.session.revision,consent:true});if(this.closed)return;this.session=session;this.busy=false;this.entry=false;this.showSetupPanel=false;if(session.serviceWizard)this.options.onNavigate('/home');this.awaitingOverview=!session.serviceWizard&&!this.overviewSubmitted&&!KINDS.some(k=>session.draft[k].length);this.introduction=this.awaitingOverview;this.lastAssistantReply='';this.render();await this.startVoice();}catch(err){if(this.closed)return;this.busy=false;this.entry=true;this.introduction=false;this.render();this.showError(err);}}
 private consentView(){const block=el('div','jc-panel-step jc-consent');const check=el('input');check.type='checkbox';check.dataset.testid='concierge-consent';const label=el('label','jc-check');label.append(check,el('span','',this.t('consent')));block.append(el('p','jc-quiet',this.t('quiet')),label,el('p','jc-muted',this.t('privacy')));
  const start=button(this.t('start'),()=>{if(!check.checked||this.busy)return;const mode=this.modeChoice!;void this.player.unlock().catch(()=>{});this.voicePreferred=mode==='voice';this.keyboard=mode==='text';void this.mutate('/mode',{mode,revision:this.session!.revision,consent:true},false).then(ok=>{if(ok&&mode==='voice')void this.startVoice();});},'jc-button jc-primary','concierge-start');start.disabled=true;check.onchange=()=>{start.disabled=!check.checked||this.busy;};const choices=el('div','jc-choices');choices.append(button(this.t('back'),()=>{this.modeChoice=null;this.render();},'jc-link'),start);block.append(choices);this.controls.append(block);}
 private async mutate(path:string,body:unknown,speak=true):Promise<boolean>{if(this.busy)return false;this.clearError();this.busy=true;this.stopSpeech();this.mic?.setListening(false);this.updateStatus();this.disableControls(true);
  try{const session=await this.api.request<Session>(path,body);if(this.closed)return false;this.session=session;this.modeChoice=null;this.busy=false;this.render();if(speak)void this.speakMessage();return true;}
  catch(err){if(!this.closed){this.busy=false;this.disableControls(false);this.updateStatus();this.showError(err);}return false;}
 }
 private async manual(){
  if(!this.session?.serviceWizard){this.go('/business/settings');return;}
  if(this.busy||this.editorBusy)return;this.stopVoice();this.stopSpeech();this.voicePreferred=false;this.keyboard=false;
  this.entry=false;this.linkEntry=false;this.introduction=false;this.showSetupPanel=true;this.options.onNavigate('/home');
  await this.mutate('/mode',{mode:'manual',revision:this.session.revision,consent:false},false);
 }
 private async beginText(){
  if(this.busy||this.editorBusy||!this.session)return;
  if(this.caps?.llm&&!this.session.consented&&!window.confirm(this.language==='ar'?'سيُرسل وصف خدمات العيادة ومسودة الإعداد إلى OpenAI. لا تدخل معلومات مرضى. هل توافق على تفعيل المحادثة؟':'Your service description and setup draft will be sent to OpenAI. Do not enter patient information. Enable AI chat?'))return;
  this.stopVoice();this.stopSpeech();this.voicePreferred=false;this.entry=false;this.keyboard=true;this.showSetupPanel=false;if(this.session.serviceWizard)this.options.onNavigate('/home');
  await this.mutate('/mode',{mode:'text',revision:this.session.revision,consent:!!this.caps?.llm},false);
 }
 private appendSetupNavigation(host:HTMLElement){const ar=this.language==='ar',nav=el('nav','jc-setup-nav');nav.setAttribute('aria-label',ar?'أقسام العيادة':'Clinic sections');nav.append(el('strong','',ar?'اعرض أي قسم في النظام':'Open a clinic section'));
  const links:[string,string,string][]=[['/home','الرئيسية','Home'],['/appointments/view','المواعيد','Appointments'],['/people/customers','العملاء','Customers'],['/people/employees','الموظفون','Staff'],['/business/services','الخدمات','Services'],['/business/rooms','الغرف','Rooms'],['/business/inventory','المخزون','Inventory'],['/business/settings','الفروع والإعدادات','Branches and settings']];
  const grid=el('div','jc-setup-nav-grid');for(const [path,arabic,english] of links)grid.append(button(ar?arabic:english,()=>{if(!SAFE_PATHS.has(path))return;this.showSetupPanel=false;this.render();this.options.onNavigate(path);},'jc-link',`concierge-open-${path.replaceAll('/','-')}`));nav.append(grid);host.append(nav);
 }
 private conversationView(){const block=el('div','jc-panel-step');const dock=el('div','jc-dock');
  if(this.session?.workflow&&!this.session.serviceWizard){const flow=this.session.workflow;const progress=el('p','jc-workflow',`${flow.index+1} / ${flow.total} · ${flow.label}`);progress.dataset.testid='concierge-workflow';block.append(progress);}
  if(this.session?.serviceWizard){block.append(el('p','jc-muted',this.language==='ar'?'اطلب إضافة خدمة أو تعديلها، تعديل هوية العيادة، أو إكمال معلومة ناقصة. راجع التغييرات قبل اعتمادها.':'Ask to add or edit a service, update your clinic identity, or complete missing information. Review changes before approval.'));if(this.lastAssistantReply)block.append(el('p','jc-assistant-reply',this.lastAssistantReply));}
  if(!this.session?.serviceWizard&&this.session?.workflow?.step==='branches'&&this.session.draft.branches.length){const branches=el('div','jc-branch-progress');branches.dataset.testid='concierge-branch-progress';branches.append(el('strong','',this.language==='ar'?'فروعك — نكمل واحدًا واحدًا':'Your branches — one at a time'));const current=this.session.draft.branches.findIndex(b=>!b.name||!b.timeZone||!b.openingHours);this.session.draft.branches.forEach((branch,index)=>{const row=el('div','jc-branch-progress-row');row.dataset.current=String(index===(current<0?this.session!.draft.branches.length-1:current));row.append(el('span','jc-branch-number',String(index+1)),el('span','',branch.name??(this.language==='ar'?'فرع بحاجة إلى اسم':'Unnamed branch')),el('small','',branch.name&&branch.timeZone&&branch.openingHours?(this.language==='ar'?'مكتمل':'Complete'):index===(current<0?this.session!.draft.branches.length-1:current)?(this.language==='ar'?'نعمل عليه الآن':'Current'):(this.language==='ar'?'بعده':'Next')));branches.append(row);});block.append(branches);}
   if(this.awaitingOverview){
    const summary=el('div','jc-overview-capture');summary.dataset.testid='concierge-overview-capture';summary.append(el('strong','',this.language==='ar'?'وصفك أولًا، والأسئلة بعده':'Your story first, questions later'),el('p','',this.language==='ar'?'احكي اسم العيادة، خدماتها الفعلية، الفروع والفريق وأي تفاصيل مهمة. رح نسمع لحد ما تقول «خلصت».':'Tell us your clinic name, actual services, branches, team and anything else important. We will listen until you say “I’m done”.'));
    if(this.overviewParts.length)summary.append(el('p','jc-overview-count',this.language==='ar'?`وصلنا ${this.overviewParts.length} جزء من وصفك.`:`Captured ${this.overviewParts.length} part${this.overviewParts.length===1?'':'s'} of your description.`));
    const mic=iconButton(this.t(this.mic?.connected?'stopVoice':'startVoice'),this.mic?.connected?'pause':'mic',()=>{if(this.busy)return;if(this.mic?.connected){this.stopVoice();this.render();}else void this.startVoice();},'concierge-mic');mic.dataset.on=String(this.voiceState==='listening');mic.disabled=this.busy;dock.append(mic);
    const done=button(this.language==='ar'?'خلصت وصف العيادة':'I’m done describing my clinic',()=>{this.voiceTurns.push({text:this.language==='ar'?'خلصت':'I’m done',id:createRequestId()});void this.saveVoiceTurns();},'jc-button jc-primary','concierge-overview-done');done.disabled=this.busy||this.voiceSaving||!this.overviewParts.length;block.append(summary,dock,done);this.controls.append(block);return;
   }
  if(!this.session?.companyChecked||this.session.companyCandidate||this.companySearching){this.companyView(block);this.controls.append(block);return;}
  if(this.caps?.voice){const mic=iconButton(this.t(this.mic?.connected?'stopVoice':'startVoice'),this.mic?.connected?'pause':'mic',()=>{if(this.busy)return;if(this.mic?.connected){this.stopVoice();this.render();}else if(!this.session?.consented)void this.beginVoice();else void this.startVoice();},'concierge-mic');mic.dataset.on=String(this.voiceState==='listening');mic.disabled=this.busy;dock.append(mic);}
  if(this.speaking)dock.append(iconButton(this.t('interruption'),'stop',()=>{this.stopSpeech();this.mic?.setListening(true);this.render();},'concierge-interrupt'));
  const keyboard=iconButton(this.t('keyboard'),'keyboard',()=>{this.keyboard=!this.keyboard;if(this.keyboard)this.mic?.setListening(false);else if(!this.speaking&&!this.busy)this.mic?.setListening(true);this.render();},'concierge-keyboard');keyboard.disabled=this.busy;dock.append(keyboard);
  const attach=iconButton(this.t('attach'),'attach',()=>{this.uploadOpen=true;this.uploadDismissed=false;this.render();},'concierge-attach');attach.disabled=this.busy||!this.session?.consented||!this.caps?.llm;dock.append(attach);
  const review=button(this.t('review'),()=>void this.openReview(),'jc-button','concierge-review-open');review.disabled=this.busy;dock.append(review);block.append(dock);
  if(!this.session?.serviceWizard&&this.session?.workflow&&this.session.workflow.step!=='review'){const next=button(this.language==='ar'?'خلصنا القسم، نكمل':'Section complete — continue',()=>void this.finishStep(),'jc-link','concierge-step-next');next.disabled=this.busy||this.voiceSaving;block.append(next);}
  if(this.session?.serviceWizard){block.append(button(this.showSetupPanel?(this.language==='ar'?'إخفاء مسودة الإعداد':'Hide setup draft'):(this.language==='ar'?'عرض مسودة الإعداد':'Show setup draft'),()=>{this.showSetupPanel=!this.showSetupPanel;this.render();},'jc-link','concierge-toggle-draft'));const sources=button(this.language==='ar'?'أضف روابط العيادة':'Add clinic links',()=>{if(this.busy||this.editorBusy)return;this.stopVoice();this.linkEntry=true;this.render();},'jc-link','concierge-add-links');sources.disabled=this.busy||this.editorBusy;block.append(sources);if(!this.session.consented){block.append(el('p','jc-muted',this.language==='ar'?'الإدخال اليدوي لا يرسل بيانات إلى نموذج AI.':'Manual entry does not send data to an AI model.'));block.append(button(this.caps?.llm?(this.language==='ar'?'فعّل محادثة AI':'Enable AI chat'):(this.language==='ar'?'تابع بالكتابة المحلية':'Continue with local text'),()=>void this.beginText(),'jc-button'));if(!this.caps?.llm)block.append(el('p','jc-muted',this.language==='ar'?'الكتابة المحلية تجيب عن السؤال المحدد، أو استخدم: «خدمة: ليزر رجال لحية فقط» و«اسم العيادة: ...». لا تحتاج مفتاح AI.':'Local text answers the focused question, or use “service: Beard laser for men only” and “clinic name: ...”. No AI key is needed.'));}}
  else block.append(button(this.language==='ar'?'البحث عن العيادة':'Find clinic',()=>void this.confirmCompany('retry'),'jc-link','concierge-company-retry'));
  if((this.keyboard||this.session?.serviceWizard)&&(this.session?.consented||!this.caps?.llm)){const form=el('form','jc-compose');const area=el('textarea');area.value=this.composing;area.placeholder=this.session?.serviceWizard?(this.language==='ar'?'شو بدك تغيّر بنظامك؟ مثال: أضف خدمة ليزر رجالي…':'What would you like to change? For example: add a men’s laser service…'):this.t('messagePlaceholder');area.maxLength=6000;area.required=true;area.setAttribute('aria-label',this.t('message'));area.dataset.testid='concierge-message';area.oninput=()=>{this.composing=area.value;};area.disabled=this.busy;const send=el('button','jc-button jc-primary',this.t('send'));send.type='submit';send.disabled=this.busy;send.dataset.testid='concierge-send';form.append(area,send);form.onsubmit=e=>{e.preventDefault();void this.sendTurn(area.value);};block.append(form);}
  const last=this.session?.uploads.at(-1);if(last){const file=el('div','jc-file',`${last.status==='read'?'✓':'!'} ${last.name} — ${this.t(last.status==='read'?'read':'unreadable')}`);file.dataset.failed=String(last.status!=='read');file.dataset.testid='concierge-file-result';if(last.summary)file.title=last.summary;block.append(file);}
  const summary=el('div','jc-summary');for(const kind of KINDS){const n=this.session!.draft[kind].length;if(n)summary.append(el('span','',`${n} ${this.t(kind)}`));}if(summary.childNodes.length)block.append(summary);
  this.controls.append(block);
   if(this.pendingTurn){this.controls.append(button(this.t('retry'),()=>void this.sendTurn(this.pendingTurn!.text),'jc-link','concierge-retry-turn'));}
   if(this.voiceTurns.length&&!this.voiceSaving)this.controls.append(button(this.t('retry'),()=>void this.saveVoiceTurns(),'jc-link','concierge-retry-voice'));
 }
 private companyView(block:HTMLElement){const candidate=this.session?.companyCandidate,candidates=this.session?.companyCandidates??[];
  if(this.companySearching){const pending=el('section','jc-company-card');pending.dataset.testid='concierge-company-searching';pending.setAttribute('role','status');pending.append(el('h2','',this.language==='ar'?'عم ببحث عن المركز…':'Searching for your center…'),el('p','jc-company-summary',this.companyQuery),el('p','jc-muted',this.language==='ar'?'رح تظهر النتيجة هون للتأكد منها قبل ما نكمّل.':'Results will appear here for confirmation.'));block.append(pending);return;}
  if(this.caps?.voice){const mic=iconButton(this.t(this.mic?.connected?'stopVoice':'startVoice'),this.mic?.connected?'pause':'mic',()=>{if(this.busy)return;if(this.mic?.connected){this.stopVoice();this.render();}else if(!this.session?.consented)void this.beginVoice();else void this.startVoice();},'concierge-mic');mic.dataset.on=String(this.voiceState==='listening');block.append(mic);}
  if(candidates.length>1){const choices=el('section','jc-company-options');choices.dataset.testid='concierge-company-options';choices.append(el('h2','',this.language==='ar'?'أي واحدة من هذول عيادتك؟':'Which of these is your clinic?'),el('p','jc-muted',this.language==='ar'?'اختَر العيادة الصحيحة. بعدها بنجيب تفاصيلها المنشورة لتراجعها.':'Choose your clinic. We will then load its published details for your review.'));candidates.forEach((item,index)=>{const card=el('article','jc-company-option');card.append(el('span','jc-company-kicker',`${index+1}`),el('h3','',item.name),el('p','jc-company-summary',item.summary));for(const source of item.sources){const link=el('a','',source.title);link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';card.append(link);}card.append(button(this.language==='ar'?'هاي عيادتي':'This is my clinic',()=>void this.confirmCompany('yes',index),'jc-button jc-primary',`concierge-company-option-${index+1}`));choices.append(card);});block.append(choices);}
  if(candidate&&candidates.length<=1){const card=el('section','jc-company-card');if(candidate.linkWarnings?.length)card.append(el('p','jc-muted',this.language==='ar'?'بعض الروابط غير متاحة أو لم تؤكد هوية العيادة. لم ندمج بياناتها.':'Some links were unavailable or could not confirm clinic identity. Their details were not merged.'));card.dataset.testid='concierge-company-card';card.append(el('p','jc-company-kicker',this.language==='ar'?'نتيجة البحث العام':'Public search result'),el('h2','',candidate.name));
   if(candidate.found){if(candidate.details){const details=candidate.details;const identity=el('div','jc-public-brand');const swatches=el('div','jc-brand-swatches');const drawColors=()=>{swatches.replaceChildren();for(const color of details.colors.filter(color=>/^#[0-9a-f]{6}$/i.test(color))){const swatch=el('span','jc-brand-swatch');swatch.style.backgroundColor=color;swatch.title=color;swatch.setAttribute('aria-label',color);swatches.append(swatch);}};drawColors();if(safeLogo(details.logoDataUrl)){const logo=el('img','jc-business-logo');logo.src=details.logoDataUrl;logo.alt=candidate.name;logo.onload=()=>{const colors=logoPalette(logo);if(colors.length){details.colors=colors;drawColors();}};identity.append(logo);}else identity.append(el('p','jc-muted',this.language==='ar'?'ما ظهر شعار موثوق بالمصادر.':'No verified logo was found.'));identity.append(swatches);card.append(identity);for(const kind of ['branches','services'] as const){const section=el('details','jc-public-details');section.open=true;section.append(el('summary','',this.language==='ar'?(kind==='branches'?'الفروع المنشورة':'الخدمات المنشورة'):(kind==='branches'?'Published branches':'Published services')));for(const item of details[kind]){const row=el('p','');row.append(el('strong','',item.name),document.createTextNode(' — '+item.detail+' '));const link=el('a','',this.language==='ar'?'المصدر':'Source');link.href=item.sourceUrl;link.target='_blank';link.rel='noopener noreferrer';row.append(link);section.append(row);}if(!details[kind].length)section.append(el('p','jc-muted',this.language==='ar'?'ما لقينا تفاصيل موثوقة منشورة؛ رح نسألك عنها.':'No verified public details; we will ask you.'));card.append(section);}card.append(el('p','jc-muted',this.language==='ar'?'تأكيد الهوية يعرض الحقائق للاختيار فقط. لا نستبدل هويتك أو نضيف خدمات دون قرارك.':'Confirming identity only presents selectable facts. It does not replace your branding or add services without your decision.'));}if(candidate.industry||candidate.location)card.append(el('p','jc-company-meta',[candidate.industry,candidate.location].filter(Boolean).join(' · ')));card.append(el('p','jc-company-summary',candidate.summary));const links=el('div','jc-company-sources');for(const source of candidate.sources){const a=el('a','',source.title);a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';links.append(a);}card.append(links,el('p','jc-company-question',this.language==='ar'?'هذا مركزك؟':'Is this your company?'));const buttons=el('div','jc-choices');buttons.append(button(this.language==='ar'?'نعم، هاي شركتي':'Yes, this is mine',()=>void this.confirmCompany('yes'),'jc-button jc-primary'),button(this.language==='ar'?'لا، دورّي مرة ثانية':'No, search again',()=>void this.confirmCompany('retry'),'jc-button'));card.append(buttons);}
   else {card.append(el('p','jc-company-summary',this.language==='ar'?'ما لقيت تطابق موثوق. بأي مدينة المركز؟ اكتب الاسم الأدق أو رابط صفحته تحت لنعيد البحث.':'No reliable match. Add the city, exact name or public business URL below to search again.'));card.append(button(this.language==='ar'?'جرّب اسم ثاني':'Try another name',()=>void this.confirmCompany('retry'),'jc-button'));}
   block.append(card);}
  block.append(button(this.language==='ar'?'أكمل يدويًا دون اعتماد نتيجة البحث':'Continue manually without accepting this result',()=>void this.confirmCompany('skip'),'jc-button','concierge-company-manual'));if(!this.caps?.llm){block.append(button(this.language==='ar'?'جرّب روابط أخرى':'Try different links',()=>{this.linkEntry=true;this.render();},'jc-link'));return;}
  const form=el('form','jc-compose');const area=el('input');area.type='text';area.maxLength=120;area.required=true;area.placeholder=this.language==='ar'?'شو اسم العيادة وبأي مدينة؟':'What is your company name?';area.setAttribute('aria-label',area.placeholder);area.dataset.testid='concierge-company-name';const submit=el('button','jc-button jc-primary',this.language==='ar'?'ابحثي':'Search');submit.type='submit';form.append(area,submit);form.onsubmit=e=>{e.preventDefault();void this.lookupCompany(area.value);};block.append(form,el('p','jc-footer',this.language==='ar'?'رح نبحث بمصادر عامة، وبنأكد النتيجة معك قبل ما نكمّل.':'We will check public sources and ask you to confirm the match.'));}
private async lookupCompany(raw:string){const query=raw.trim().slice(0,120);if(!query||!this.session||this.busy)return;this.companySearching=true;this.companyQuery=query;this.busy=true;this.clearError();this.render();this.mic?.pauseForCompanyLookup();try{const session=await this.api.request<Session>('/company-lookup',{revision:this.session.revision,query});if(this.closed)return;this.session=session;this.companySearching=false;this.busy=false;this.lastAssistantReply='';this.render();if((session.companyCandidates?.length??0)>1)this.mic?.showCompanyChoices(session.companyCandidates!.map((item,index)=>({number:index+1,name:item.name,summary:item.summary})));else this.mic?.showCompanyResult(!!session.companyCandidate?.found,session.companyCandidate??undefined);}catch(err){if(this.closed)return;this.busy=false;this.render();this.companySearching=false;this.render();this.showError(err);this.mic?.resumeAfterLookupError();}}
 private async finishStep(){if(this.session?.serviceWizard){await this.openReview();return;}if(!this.session||this.busy)return;this.busy=true;this.clearError();try{const session=await this.api.request<Session>('/step-confirm',{revision:this.session.revision});if(this.closed)return;this.session=session;this.lastAssistantReply='';this.busy=false;this.render();void this.showQuestionField();this.mic?.inform(`Stay on server step ${session.workflow?.step}. Say only: ${JSON.stringify(session.workflow?.prompt??session.message.text)}`);}catch(err){this.busy=false;this.showError(err);}}
 private async confirmCompany(answer:'yes'|'retry'|'skip',selectedIndex=0){if(!this.session||this.busy)return;this.busy=true;this.updateStatus();try{const selected=this.session.companyCandidates?.[selectedIndex]??this.session.companyCandidate,name=answer==='yes'?selected?.name??null:null;const session=await this.api.request<Session>('/company-confirm',{revision:this.session.revision,answer,selectedIndex,...(answer==='yes'&&selected?.details?{colors:selected.details.colors}:{})});if(this.closed)return;this.session=session;if(answer==='yes'&&this.overviewParts.length)await this.flushOverviewParts();this.busy=false;this.lastAssistantReply='';this.render();const finalSession=this.session;if(answer==='retry')this.mic?.askCompanyAgain();else {if(session.sourceImport&&!session.serviceWizard&&!this.mic?.connected){await this.openReview();return;}void this.showQuestionField();this.mic?.inform(`Identity confirmed: ${JSON.stringify(name)}. Ask ONLY the current server question: ${JSON.stringify(finalSession.workflow?.prompt??finalSession.message.text)}. Do not search again.`);}}catch(err){if(this.closed)return;this.busy=false;this.render();this.showError(err);}}
 private guideFromQuestion(reply:string){if(this.session?.serviceWizard)return;if(this.introduction||!this.session?.companyChecked)return;const q=reply.toLowerCase();if(!this.uploadDismissed&&/ارفع|ابعث.*ملف|ابعته.*هون|upload|attach.*file/.test(q)&&!this.uploadOpen){this.uploadOpen=true;this.render();return;}if(this.uploadOpen||this.typing)return;const path=/موظف|موظفين|فريق|staff|employees?/.test(q)?'/people/employees':/خدم|service/.test(q)?'/business/services':/غرف|غرفة|rooms?/.test(q)?'/business/rooms':/فرع|فروع|branch/.test(q)?'/business/settings':null;if(path&&path!==this.guidePath)this.guideTo(path);}
 private guideFromSession(utterance:string){if(this.session?.serviceWizard)return;if(!this.session?.companyChecked||this.closed||this.typing||this.uploadOpen||this.review)return;const paths={branches:'/business/settings',staff:'/people/employees',services:'/business/services',rooms:'/business/rooms'};for(const kind of KINDS)for(const row of this.session.draft[kind]){const key=`${kind}:${row.key}`,signature=JSON.stringify(row);if(row.name&&this.guidedValues.get(key)!==signature){void this.fillRecord(paths[kind],kind==='staff'?'employees':kind,row,key,signature);return;}}void this.showQuestionField();}
 private async showQuestionField(){if(this.session?.serviceWizard)return;const focus=this.session?.workflow?.focus;if(!focus||!this.session?.companyChecked||this.closed||this.entry||this.introduction||this.typing||this.uploadOpen||this.review)return;const path=focus.resource==='employees'?'/people/employees':focus.resource==='services'?'/business/services':focus.resource==='rooms'?'/business/rooms':'/business/settings';const generation=++this.guideGeneration;this.guidePath=path;this.options.onNavigate(path);for(let attempt=0;attempt<30;attempt++){if(this.closed||this.typing||generation!==this.guideGeneration)return;const form=document.querySelector<HTMLElement>(`[data-testid="form-${focus.resource}"][data-assistant-key="${focus.key}"]`);if(form){window.dispatchEvent(new CustomEvent('jormall:concierge-focus-field',{detail:focus}));return;}if(document.querySelector(`[data-testid="add-${focus.resource}"]`))window.dispatchEvent(new CustomEvent('jormall:concierge-open-record',{detail:{resource:focus.resource,key:focus.key}}));await new Promise(resolve=>setTimeout(resolve,100));}}
 private async fillRecord(path:string,resource:string,row:{key:string;name:string|null},key:string,signature:string){this.typing=true;const generation=++this.guideGeneration;const alive=()=>!this.closed&&generation===this.guideGeneration&&!this.review&&!this.uploadOpen;const wait=async(selector:string)=>{for(let i=0;i<32&&alive();i++){const target=document.querySelector<HTMLElement>(selector);if(target&&!(target instanceof HTMLButtonElement&&target.disabled))return target;await new Promise(resolve=>setTimeout(resolve,100));}return null;};this.guidePath=path;this.options.onNavigate(path);
  const target=await wait(`[data-testid="add-${resource}"]`);if(!target||!alive()){this.typing=false;return;}target.scrollIntoView({block:'center',behavior:'smooth'});const bounds=target.getBoundingClientRect();this.guideOrb.style.transform=`translate3d(${bounds.left+10}px,${bounds.top+10}px,0)`;this.guideOrb.classList.add('jc-guide-active');await new Promise(resolve=>setTimeout(resolve,550));if(!alive()){this.typing=false;return;}window.dispatchEvent(new CustomEvent('jormall:concierge-open-record',{detail:{resource,key:row.key}}));const form=await wait(`[data-testid="form-${resource}"][data-assistant-key="${row.key}"]`);if(!form||!alive()){this.typing=false;return;}this.guidedValues.set(key,signature);window.dispatchEvent(new CustomEvent('jormall:concierge-prefill',{detail:{resource,key:row.key,fields:row}}));
 }
 private guideTo(path:string|null,fill=false){if(!path||!SAFE_PATHS.has(path)||this.closed||this.review)return;if(this.guidePath===path){this.locateGuide(path,0,fill);return;}if(!this.guideOrb.classList.contains('jc-guide-active')){const origin=this.canvas.getBoundingClientRect();this.guideOrb.style.transform=`translate3d(${origin.left+origin.width/2-19}px,${origin.top+origin.height/2-19}px,0)`;this.guideOrb.classList.add('jc-guide-active');}this.guidePath=path;this.options.onNavigate(path);this.guideTimer=window.setTimeout(()=>this.locateGuide(path,0,fill),80);}
 private locateGuide(path:string,attempt:number,fill=false){clearTimeout(this.guideTimer);if(this.closed||this.guidePath!==path)return;const resource=path==='/people/employees'?'employees':path==='/business/services'?'services':path==='/business/rooms'?'rooms':path==='/business/settings'?'branches':null;
  const target=document.querySelector<HTMLElement>(resource?`[data-testid="add-${resource}"]`:'main h1');if(!target){if(attempt<16)this.guideTimer=window.setTimeout(()=>this.locateGuide(path,attempt+1,fill),250);return;}
  const bounds=target.getBoundingClientRect();this.guideOrb.style.transform=`translate3d(${Math.max(10,bounds.left+bounds.width/2-19)}px,${Math.max(10,bounds.top+bounds.height/2-19)}px,0)`;this.guideOrb.classList.add('jc-guide-active');target.scrollIntoView({behavior:'smooth',block:'center'});
 }
 private uploadView(parent:HTMLElement){const panel=el('div','jc-upload jc-panel-step');panel.dataset.testid='concierge-upload';panel.append(el('span','jc-upload-symbol','↑'),el('h3','',this.t('uploadDrop')),el('p','jc-muted',this.t('uploadHint')));const input=el('input');input.type='file';input.accept='.pdf,.txt,.csv,.json';input.hidden=true;input.dataset.testid='concierge-file';input.onchange=()=>{if(input.files?.[0])void this.upload(input.files[0]);};const choose=button(this.fileBusy?this.t('fileReading'):this.t('chooseFile'),()=>input.click(),'jc-button jc-primary','concierge-file-choose');choose.disabled=this.busy;panel.append(input,choose);panel.ondragover=e=>{e.preventDefault();panel.classList.add('jc-drop-hover');};panel.ondragleave=()=>panel.classList.remove('jc-drop-hover');panel.ondrop=e=>{e.preventDefault();panel.classList.remove('jc-drop-hover');if(e.dataTransfer?.files[0]&&!this.busy)void this.upload(e.dataTransfer.files[0]);};parent.append(panel,button(this.t('continueWithoutFile'),()=>{this.uploadOpen=false;this.uploadDismissed=true;this.render();},'jc-link','concierge-upload-dismiss'));}
 private async sendTurn(raw:string,returnToReview=false){const message=raw.trim();if(!message||this.busy||this.voiceSaving||this.editorBusy||!this.session||this.closed)return;if(!this.session.companyChecked){await this.lookupCompany(message);return;}if(!this.pendingTurn||this.pendingTurn.text!==message)this.pendingTurn={text:message,id:createRequestId()};const id=this.pendingTurn.id;
  this.busy=true;this.clearError();this.stopSpeech();this.mic?.setListening(false);this.updateStatus();this.disableControls(true);
  try{const session=await this.turnRequest({revision:this.session.revision,requestId:id,text:message});if(this.closed)return;this.session=session;this.composing='';this.pendingTurn=null;this.uploadOpen=session.ui==='upload';this.lastAssistantReply=session.serviceWizard?session.message.text:'';this.busy=false;this.render();this.guideFromSession(message);if(session.serviceWizard&&session.navigation&&SAFE_PATHS.has(session.navigation))this.options.onNavigate(session.navigation);if(returnToReview){await this.openReview();return;}if(this.mic?.connected){this.mic.setListening(true);this.mic.inform(`Say only this server-provided next question: ${JSON.stringify(session.message.text)}`);}else if(this.voicePreferred)void this.speakMessage();else if(!this.keyboard&&!this.uploadOpen)this.mic?.setListening(true);}
  catch(err){if(this.closed)return;this.busy=false;this.render();this.showError(err);}
 }
 private async upload(file:File){if(this.busy||this.voiceSaving||this.editorBusy||!this.session)return;if(!/\.(pdf|txt|csv|json)$/i.test(file.name)){this.showNotice('unsupportedFile');return;}if(file.size>(this.caps?.uploadMaxBytes??8*1024*1024)){this.showNotice('fileTooBig');return;}
  this.busy=true;this.fileBusy=true;this.clearError();this.updateStatus();this.disableControls(true);
  try{while(this.voiceSaving&&!this.closed)await new Promise(resolve=>setTimeout(resolve,60));if(this.closed)return;const session=await this.api.upload<Session>(file,this.session.revision,createRequestId());if(this.closed)return;this.session=session;this.uploadOpen=false;this.uploadDismissed=true;this.busy=false;this.fileBusy=false;this.render();this.guideFromSession(session.message.text);if(this.mic?.connected)this.mic.inform(`The app finished reading the uploaded file. ${session.uploads.at(-1)?.status==='read'?'It extracted these setup counts: '+JSON.stringify(Object.fromEntries(KINDS.map(k=>[k,session.draft[k].length]))):'The file was not readable; ask for another file or spoken details.'} Ask only the current server question: ${JSON.stringify(session.workflow?.prompt??session.message.text)}. Do not advance to a different section; never say the records are finally saved.`);else if(this.voicePreferred)void this.speakMessage();void this.saveVoiceTurns();}
  catch(err){if(this.closed)return;this.busy=false;this.fileBusy=false;this.render();this.showError(err);void this.saveVoiceTurns();}
 }
 private async startVoice(){if(this.busy||this.closed||!this.session?.consented||!this.caps?.voice)return;this.stopVoice();this.stopSpeech();this.clearError();this.voicePreferred=true;this.keyboard=false;this.uploadOpen=false;void this.player.unlock().catch(()=>this.showNotice('audioBlocked'));
  const mic=new RealtimeVoiceSession(this.api,{level:n=>this.orb.setLevel(n),partial:partial=>{this.transcript.textContent=partial;},utterance:utterance=>{this.voiceTurns.push({text:utterance,id:createRequestId()});void this.saveVoiceTurns();},reply:reply=>{if(!this.closed&&this.mic===mic){this.lastAssistantReply=reply;if(this.session?.serviceWizard){const shown=this.controls.querySelector<HTMLElement>('.jc-assistant-reply');if(shown)shown.textContent=reply;else this.render();}else this.caption.textContent=reply;this.guideFromQuestion(reply);}},introDone:()=>{if(this.closed||this.mic!==mic)return;this.introduction=false;this.lastAssistantReply='';this.render();},state:state=>{this.voiceState=state;this.updateStatus();},noise:()=>{if(!this.closed&&this.mic===mic)this.showNotice('noiseHint');},error:code=>{if(this.closed)return;if(this.introduction){this.introduction=false;this.entry=true;}if(code!=='audioBlocked'){this.voiceState='off';this.keyboard=true;}this.render();if(['micUnsupported','micDenied','connectionLost','expired','audioBlocked'].includes(code))this.showNotice(code);else this.showError(new ConciergeHTTPError(code,0));}});this.mic=mic;await mic.connect(this.language,!this.session.companyChecked,this.introduction,!!this.session.serviceWizard);if(this.closed||this.mic!==mic)return;this.render();}
 private async flushOverviewParts(){while(this.overviewParts.length&&this.session&&!this.closed){let size=0,count=0;for(const part of this.overviewParts){if(size&&size+part.length+1>5000)break;size+=part.length+1;count++;if(size>=5000)break;}const overview=this.overviewParts.slice(0,count).join('\n').slice(0,5000);const session=await this.turnRequest({revision:this.session.revision,requestId:createRequestId(),text:overview});if(this.closed)return;this.session=session;this.overviewParts.splice(0,count);this.render();}}
  private async saveVoiceTurns(){
   if(this.voiceSaving||this.closed||this.busy||this.editorBusy)return;this.voiceSaving=true;this.updateStatus();this.renderWizard();
   try{while(this.voiceTurns.length&&!this.closed&&!this.busy&&this.session?.stage==='conversation'){
    const utterance=this.voiceTurns[0]!;
    try{
     if(this.awaitingOverview){
      const spoken=utterance.text.trim();const done=/^(خلصت|خلصنا|انتهيت|هيك كل شي|هذا كل شي|بس هيك|i(?:'|’)m done|that(?:'|’)s all|finished)[.!،؟?\s]*$/i.test(spoken);
      if(!done){for(let offset=0;offset<spoken.length;offset+=4500)this.overviewParts.push(spoken.slice(offset,offset+4500));this.voiceTurns.shift();this.render();continue;}
      if(!this.overviewParts.length){this.voiceTurns.shift();this.showNotice('ready');continue;}
      this.mic?.setListening(false);
      if(!this.session.companyChecked){this.awaitingOverview=false;this.overviewSubmitted=true;this.voiceTurns.shift();this.render();this.mic?.setListening(true);this.mic?.inform('The manager finished describing the clinic. Ask only for the exact clinic name and city so the app can search and confirm it. Do not ask branch details yet.');continue;}
      await this.flushOverviewParts();
      this.awaitingOverview=false;this.overviewSubmitted=true;this.voiceTurns.shift();this.render();
      this.mic?.inform(`The manager finished their full clinic description. The app saved its supported draft. Ask only the next server question: ${JSON.stringify(this.session.message.text)}. Do not invent missing prices, services or branches.`);continue;
     }
     if(!this.session.companyChecked){const answer=utterance.text.trim().replace(/[.!،؟?]/g,'').toLowerCase(),choices=this.session.companyCandidates??[];const number=/(?:^|\s)([123١٢٣])(?:$|\s)|\b(first|second|third)\b|(الأول|الاول|الأولى|الاولى|الثاني|الثانية|الثالث|الثالثة|أول واحد|ثاني واحد|ثالث واحد)/i.exec(answer);const selected=number?({'1':0,'١':0,'first':0,'الأول':0,'الاول':0,'الأولى':0,'الاولى':0,'أول واحد':0,'2':1,'٢':1,'second':1,'الثاني':1,'الثانية':1,'ثاني واحد':1,'3':2,'٣':2,'third':2,'الثالث':2,'الثالثة':2,'ثالث واحد':2} as Record<string,number>)[number.slice(1).find(Boolean)??number[1]??'']:-1;if(choices.length>1&&selected!==undefined&&selected>=0&&selected<choices.length)await this.confirmCompany('yes',selected);else if(choices.length<=1&&this.session.companyCandidate?.found&&/^(نعم|ايوه|أيوه|اه|آه|صح|هاي شركتي|اه هاي شركتي|نعم هاي شركتي|هذا مركزي|اه هذا مركزي|نعم هذا مركزي|نعم هذا المركز|yes|correct)$/.test(answer))await this.confirmCompany('yes');else if(this.session.companyCandidate&&/^(لا|مش شركتي|لا مش شركتي|مش مركزي|لا مش مركزي|no)$/.test(answer))await this.confirmCompany('retry');else await this.lookupCompany(utterance.text);this.voiceTurns.shift();continue;}
     if(/^(خلصنا القسم|خلصنا هالقسم|section complete|next section)[.!،؟?]*$/i.test(utterance.text.trim())){await this.finishStep();this.voiceTurns.shift();continue;}
     const session=await this.turnRequest({revision:this.session.revision,requestId:utterance.id,text:utterance.text});if(this.closed)return;this.session=session;this.voiceTurns.shift();if(session.ui==='upload'&&!this.uploadDismissed)this.uploadOpen=true;this.render();this.guideFromSession(utterance.text);if(!this.voiceTurns.length)this.mic?.inform(`Current step: ${session.workflow?.step??'setup'}. Say only the server-provided response: ${JSON.stringify(session.message.text)}. Do not ask about other sections or announce a search.`);
    }catch(err){this.showError(err);this.keyboard=true;this.render();this.mic?.inform('التطبيق لم يستلم المعلومات بنجاح. اطلبي إعادة المحاولة بنفس الخطوة، ولا تنتقلي لخطوة ثانية.');break;}
   }}finally{this.voiceSaving=false;this.updateStatus();if(!this.closed)this.render();const next=this.controls.querySelector<HTMLButtonElement>('[data-testid="concierge-step-next"]');if(next)next.disabled=this.busy;}
  }
 private async speakMessage(force=false){if(!this.session||!this.caps?.tts||this.closed||this.review||this.busy||this.mic?.connected)return;const id=this.session.message.id;this.stopSpeech();const ticket=++this.speakTicket;this.mic?.setListening(false);this.speaking=true;this.updateStatus();if(this.session.stage==='conversation')this.render();
  try{await this.player.play(id,()=>{if(ticket===this.speakTicket){this.needsAudioClick=false;this.speaking=true;this.updateStatus();}});}
  catch(err){if(ticket!==this.speakTicket||this.closed)return;if((err as Error).name==='NotAllowedError'){this.needsAudioClick=true;this.showNotice('audioBlocked');}else if((err as Error).name!=='AbortError'){this.showError(err);}}
  finally{if(ticket===this.speakTicket&&!this.closed){this.speaking=false;this.updateStatus();if(this.session?.stage==='conversation')this.render();else {const sound=this.controls.querySelector<HTMLButtonElement>('[data-testid=concierge-sound]');if(sound)sound.textContent=this.t(this.needsAudioClick?'enableSound':'sound');}if(!this.keyboard&&!this.uploadOpen&&!this.review)this.mic?.setListening(true);}}
 }
 private async openReview(){if(this.busy||this.editorBusy)return;this.clearError();this.stopSpeech();this.stopVoice();this.busy=true;this.updateStatus();this.disableControls(true);try{this.review=await this.api.request<Review>('/review');if(this.closed)return;this.showSetupPanel=true;this.busy=false;this.render();this.dialog.scrollTo({top:0,behavior:'instant'});}catch(err){if(this.closed)return;this.busy=false;this.render();this.showError(err);}}
 private async saveDraft(draft:Draft){this.clearError();try{const session=await this.api.request<Session>('/draft',{revision:this.session!.revision,draft},'PUT');if(this.closed)return;this.session=session;this.review=await this.api.request<Review>('/review');if(this.closed)return;this.render();}catch(err){this.showError(err);throw err;}}
 private async apply(staff:Provision[]){if(this.busy)throw new ConciergeHTTPError('concierge_busy',409);this.busy=true;this.clearError();this.renderWizard();try{const session=await this.api.request<Session>('/apply',{revision:this.session!.revision,confirmed:true,staff});if(this.closed)return;this.session=session;this.review=null;this.options.onApplied();}catch(err){this.showError(err);throw err;}finally{this.busy=false;if(!this.closed)this.render();}}
 private completeView(){const block=el('div','jc-panel-step'),counts=el('div','jc-counts');for(const kind of KINDS){const n=this.session?.applied?.[kind]?.length??0;if(n)counts.append(el('div','',`${n} ${this.t(kind)}`));}block.append(counts,el('p','jc-muted',this.t('doneNote')),el('p','jc-muted',this.t('emptyScope')),button(this.t('enter'),()=>this.go('/home'),'jc-button jc-primary','concierge-enter'));this.controls.append(block);}
 private disableControls(disabled:boolean){for(const control of this.controls.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLButtonElement>('button,input,textarea'))control.disabled=disabled;}
 private async refresh(){if(this.busy)return;if(this.editorBusy){if(!window.confirm(this.language==='ar'?'سيُلغى التعديل اليدوي غير المحفوظ. تحديث المسودة؟':'Discard unsaved local edits and reload the draft?'))return;this.resetEditors();}this.clearError();this.busy=true;this.stopSpeech();this.stopVoice();this.updateStatus();try{let data=await this.api.request<Bootstrap>('/bootstrap');if(!data.session)data=await this.api.request<Bootstrap>('/start',{language:this.language,reopen:false});if(this.closed)return;this.session=data.session;this.caps=data.capabilities;this.review=null;this.pendingTurn=null;this.busy=false;this.render();}catch(err){if(this.closed)return;this.busy=false;this.render();this.showError(err);}}
 private async restart(){this.clearError();try{const data=await this.api.request<Bootstrap>('/start',{language:this.language,reopen:true});if(this.closed)return;this.session=data.session;this.caps=data.capabilities;this.review=null;this.modeChoice=null;this.render();}catch(err){this.showError(err);}}
 private async switchLanguage(){if(this.busy||this.editorBusy)return;const language=this.language==='ar'?'en':'ar';this.stopSpeech();this.stopVoice();this.clearError();this.busy=true;try{const data=await this.api.request<Bootstrap>('/start',{language,reopen:false});if(this.closed)return;this.session=data.session;this.caps=data.capabilities;this.language=language;this.busy=false;this.render();}catch(err){if(this.closed)return;this.busy=false;this.render();this.showError(err);}}
 private setEditing(kind:'service'|'workspace',editing:boolean){
  if(kind==='service')this.serviceEditing=editing;else this.workspaceEditing=editing;
  this.editorBusy=this.serviceEditing||this.workspaceEditing;
  if(this.editorBusy){this.stopVoice();this.stopSpeech();}
  this.disableControls(this.editorBusy||this.busy);
  const language=this.top.querySelector<HTMLButtonElement>('[data-testid=concierge-language]');if(language)language.disabled=this.editorBusy||this.busy||!!this.review;
  if(!this.closed&&!this.resettingEditors)this.renderWizard();
 }
 private resetEditors(){this.resettingEditors=true;this.wizardRoot?.unmount();this.wizardRoot=null;this.identityPanel?.dispose();this.identityPanel=null;this.editorBusy=false;this.serviceEditing=false;this.workspaceEditing=false;this.resettingEditors=false;}
 private renderWizard(){
   const visible=!!this.session?.serviceWizard&&!this.entry&&!this.linkEntry&&this.session.stage==='conversation';
  this.dialog.classList.toggle('jc-service-mode',visible);this.sideHost.hidden=!visible||!this.showSetupPanel;
  if(!visible){this.wizardRoot?.render(null);return;}
  const session=this.session!;
  if(session.workspace){
   const sections:WorkspaceSection[]=[];
   for(const service of session.draft.services){const name=service.definition?.section||(this.language==='ar'?'خدمات العيادة':'Clinic services');let section=sections.find(s=>s.name===name);if(!section){section={name,serviceIds:[],serviceNames:[]};sections.push(section);}section.serviceNames.push(service.name??(this.language==='ar'?'خدمة تحتاج اسمًا':'Unnamed service'));}
   const props={draft:session.workspace,revision:session.revision,language:this.language,busy:this.busy||this.voiceSaving||this.serviceEditing||!!session.busy,review:!!this.review,sections,
    onSave:(profile:WorkspaceProfile)=>this.workspaceRequest('/workspace-draft',{profile},'PUT'),onFact:(id:string,accept:boolean)=>this.workspaceRequest('/workspace-fact',{id,accept}),onReload:()=>this.workspaceRequest('/workspace-reload',{}),onDirty:(dirty:boolean)=>this.setEditing('workspace',dirty)};
   if(this.identityPanel)this.identityPanel.update(props);else this.identityPanel=new WorkspaceIdentityPanel(this.identityHost,props);
  }
  if(!this.wizardRoot)this.wizardRoot=createRoot(this.wizardHost);
  if(!this.serviceOptions&&!this.optionsLoading&&!this.optionsError)void this.loadServiceOptions();
  this.wizardRoot.render(createElement(ServiceWizardPanel,{session,language:this.language,options:this.serviceOptions,optionsError:this.optionsError,busy:this.busy||this.voiceSaving||this.workspaceEditing||!!session.busy,previews:this.servicePreviews,review:this.review,
   onSave:(draft:Draft)=>this.saveServiceDraft(draft),onAccept:(key:string)=>this.acceptSuggestion(key),onReview:()=>void this.openReview(),onBack:()=>{this.review=null;this.render();},onApply:()=>this.apply([]),onRetryOptions:()=>void this.loadServiceOptions(),onEditing:(editing:boolean)=>this.setEditing('service',editing)
  }));
 }
 private async workspaceRequest(path:string,body:Record<string,unknown>,method='POST'){
  if(!this.session||this.busy||this.voiceSaving||this.serviceEditing)throw new ConciergeHTTPError('concierge_busy',409);
  this.busy=true;this.stopVoice();this.stopSpeech();this.clearError();this.renderWizard();
  try{const session=await this.api.request<Session>(path,{...body,revision:this.session.revision},method);if(this.closed)throw new Error('closed');this.session=session;this.review=null;this.lastAssistantReply='';}
  catch(error){this.showError(error);throw error;}
  finally{this.busy=false;if(!this.closed)this.render();}
 }
 private async loadServiceOptions(){
  if(this.optionsLoading||this.closed)return;this.optionsLoading=true;this.optionsError=false;
  try{this.serviceOptions=await this.api.request<ServiceOptions>('/service-options');}catch{if(!this.closed)this.optionsError=true;}
  finally{this.optionsLoading=false;if(!this.closed)this.renderWizard();}
 }
 private async saveServiceDraft(draft:Draft){
  if(!this.session||this.busy||this.voiceSaving)throw new ConciergeHTTPError('concierge_busy',409);
  this.busy=true;this.clearError();this.renderWizard();
  try{const session=await this.api.request<Session>('/draft',{revision:this.session.revision,draft},'PUT');if(this.closed)return;this.session=session;this.lastAssistantReply='';}
  catch(e){this.showError(e);throw e;}
  finally{this.busy=false;if(!this.closed)this.render();}
 }
 private async acceptSuggestion(key:string){
  if(!this.session||this.busy||this.voiceSaving)throw new ConciergeHTTPError('concierge_busy',409);
  this.busy=true;this.renderWizard();this.clearError();
  try{this.session=await this.api.request<Session>('/service-suggestion',{revision:this.session.revision,key});}
  catch(e){this.showError(e);throw e;}
  finally{this.busy=false;if(!this.closed)this.render();}
 }
 private async turnRequest(body:{revision:number;requestId:string;text:string}):Promise<Session>{
  if(!this.session?.serviceWizard)return this.api.request<Session>('/turn',body);
  const removal=body.text.trim().match(/^(?:احذف|إحذف|شيل|أزل|ازل|امسح|حذف|إزالة|ازالة|remove|delete)\s+(?:لي\s+)?(?:خدمة\s+)?(.+)$/i);
  if(removal){const name=normalizeServiceName(removal[1]!.trim());const matches=this.session.draft.services.filter(service=>{const current=normalizeServiceName(service.name??'');return current===name||name.length>=3&&current.includes(name);});if(matches.length===1){const draft={...this.session.draft,services:this.session.draft.services.filter(service=>service.key!==matches[0]!.key)};return this.api.request<Session>('/draft',{revision:body.revision,draft},'PUT');}}
  this.servicePreviews=[];this.renderWizard();
  try{return await this.api.turnStream(body,service=>{if(this.closed||this.session?.revision!==body.revision)return;this.servicePreviews=[...this.servicePreviews.filter(s=>s.key!==service.key),service];this.renderWizard();});}
  finally{this.servicePreviews=[];if(!this.closed)this.renderWizard();}
 }
 private go(path:string){this.close();if(this.closed)this.options.onNavigate(path);}
}
