import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import ts from 'typescript';
const require=createRequire(import.meta.url),cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const module={exports:{}};cache.set(file,module.exports);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;new Function('exports','module','require',code)(module.exports,module,name=>name.startsWith('.')?load(path.resolve(path.dirname(file),name+'.ts')):require(name));return module.exports;}
const {setupWorkflow,canFinishStep}=load('artifacts/api-server/src/domain/concierge-workflow.ts'),{emptyDraft}=load('artifacts/api-server/src/domain/concierge-core.ts');
const draft=emptyDraft(),state={draft,companySkipped:true,completedSteps:[]},existing={branches:[],services:[],rooms:[]};
assert.equal(setupWorkflow(state,'ar').step,'company');state.companyProfile={name:'Synthetic center'};
assert.equal(setupWorkflow(state,'ar').step,'branches');assert.equal(canFinishStep('branches',draft,existing),false);
draft.branches.push({key:'b',existingId:null,name:'فرع عمان',nameLang:'ar',timeZone:null,openingHours:null});assert.match(setupWorkflow(state,'ar').prompt,/المنطقة الزمنية/);assert.equal(canFinishStep('branches',draft,existing),false);
draft.branches[0].timeZone='Asia/Amman';draft.branches[0].openingHours=Object.fromEntries(['mon','tue','wed','thu','fri','sat','sun'].map(d=>[d,[]]));assert.equal(canFinishStep('branches',draft,existing),true);assert.equal(setupWorkflow(state,'ar').step,'branches');state.completedSteps.push('branches');assert.equal(setupWorkflow(state,'ar').step,'services');
draft.services.push({key:'s',name:'ليزر',nameLang:'ar',branchKey:null,durationMinutes:30,price:'20',currency:'JOD',category:'Laser',requiresRoom:true});assert.equal(canFinishStep('services',draft,existing),true);state.completedSteps.push('services');assert.equal(setupWorkflow(state,'ar').step,'rooms');assert.equal(canFinishStep('rooms',draft,existing),false);
draft.rooms.push({key:'r',name:'غرفة ليزر',nameLang:'ar',branchKey:'b',capacity:1,serviceKeys:['s']});assert.equal(canFinishStep('rooms',draft,existing),true);state.completedSteps.push('rooms','staff');assert.equal(setupWorkflow(state,'ar').step,'review');draft.branches[0].name=null;assert.equal(setupWorkflow(state,'ar').step,'branches');
const {publicIPv4,siteIdentity,rasterDataUrl}=load('artifacts/api-server/src/concierge/public-business-site.ts');for(const ip of ['127.0.0.1','10.1.1.1','172.16.0.1','192.168.1.1','169.254.169.254','100.64.0.1','::1','::ffff:127.0.0.1'])assert.equal(publicIPv4(ip),false,ip);assert.equal(publicIPv4('8.8.8.8'),true);
assert.equal(siteIdentity('<p>Welcome to WordPress</p><img src="/logo.png">','https://example.com').logo,null);
const site=siteIdentity('<meta name="theme-color" content="#aabbcc"><img alt="Center logo" src="/logo.png"><a href="/services">Services</a><script>alert(1)</script><p>Facial 30 JOD</p>','https://example.com');assert.equal(site.logo,'https://example.com/logo.png');assert.deepEqual(site.colors,['#aabbcc']);assert.ok(!site.text.includes('alert'));assert.equal(site.pages[0],'https://example.com/services');assert.equal(rasterDataUrl(Buffer.from('<svg onload="alert(1)"/>')),null);
globalThis.window=globalThis;const {RealtimeVoiceSession}=load('artifacts/jormall/src/components/concierge/realtime-voice.ts');const sent=[];const voice=new RealtimeVoiceSession({}, {state(){},reply(){},partial(){},level(){},noise(){},utterance(){},error(code){throw Error(code);}});voice.channel={readyState:'open',send:value=>sent.push(JSON.parse(value)),close(){}};
voice.inform('First question');voice.handle({type:'response.created'});voice.handle({type:'output_audio_buffer.started'});voice.handle({type:'response.done'});voice.inform('Search is complete');assert.equal(sent.filter(e=>e.type==='response.create').length,1,'generation done must not overlap audible playback');voice.handle({type:'input_audio_buffer.speech_started'});assert.equal(sent.some(e=>e.type==='response.cancel'||e.type==='output_audio_buffer.clear'),false,'background speech must not clear playback');voice.handle({type:'output_audio_buffer.stopped'});assert.equal(sent.filter(e=>e.type==='response.create').length,2);assert.match(sent.at(-1).response.instructions,/العربي/);voice.stop();
console.log('PASS ordered workflow, explicit completion, missing-field gates, identity gate, safe public-site parsing and audio playback serialization');
