/** Executable local rules/source checks only. Never substitutes for PostgreSQL or browser acceptance. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url), ts=require(process.env.TYPESCRIPT_PATH||'typescript');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'), cache=new Map();
function load(relative){
 const file=path.resolve(root,relative);if(cache.has(file))return cache.get(file).exports;
 const output=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
 const module={exports:{}};cache.set(file,module);
 const localRequire=(p)=>p.startsWith('.')?load(path.resolve(path.dirname(file),p+'.ts')):require(p);
 new Function('exports','module','require',output)(module.exports,module,localRequire);return module.exports;
}
const rules=load('artifacts/api-server/src/domain/scheduling-rules.ts');
const time=load('artifacts/api-server/src/domain/scheduling-time.ts');
const setup=load('artifacts/api-server/src/domain/setup-rules.ts');
const permission=load('artifacts/api-server/src/domain/permissions.ts');
const en=load('artifacts/jormall/src/lib/i18n/en.ts').en, ar=load('artifacts/jormall/src/lib/i18n/ar.ts').ar;
let checks=0;function test(name,fn){fn();checks++;console.log(`PASS ${name}`);}
const manager={id:1,clinicId:1,role:'manager',permissions:['appointments.manage']};
const doctor={id:2,clinicId:1,role:'doctor',permissions:['customers.read']};
const provider={...doctor,role:'service_provider'};
const reader={id:3,clinicId:1,role:'other_staff',permissions:['appointments.read']};
const appointment={clinicId:1,employeeId:2,status:'pending'};
for(const actor of [manager,reader,doctor,provider])test(`${actor.role} can open permitted scheduling`,()=>assert.ok(rules.canAccessScheduling(actor)));
test('manager status alone does not bypass permissions',()=>assert.equal(rules.canAccessScheduling({...manager,permissions:[]}),false));
test('platform owner cannot operate clinic scheduling',()=>assert.equal(rules.canAccessScheduling({...manager,role:'platform_owner'}),false));
test('unscoped doctor rejected',()=>assert.equal(rules.canAccessScheduling({...doctor,clinicId:null}),false));
test('own assigned provider can read',()=>assert.ok(rules.canReadAppointment(doctor,appointment)));
test('provider cannot read another employee',()=>assert.equal(rules.canReadAppointment(doctor,{...appointment,employeeId:4}),false));
test('explicit read allows other assignments',()=>assert.ok(rules.canReadAppointment({...doctor,permissions:['appointments.read']},{...appointment,employeeId:4})));
test('manage implies read',()=>assert.ok(rules.canReadAll(manager)));
test('read does not imply booking permission',()=>assert.equal(rules.canSchedule(reader),false));
test('provider cannot book implicitly',()=>assert.equal(rules.canSchedule(provider),false));
for(const actor of [manager,reader,doctor,provider])test(`${actor.role} cross-clinic denial`,()=>assert.equal(rules.canReadAppointment(actor,{...appointment,clinicId:9}),false));
test('plain reader cannot see operational notes',()=>assert.equal(rules.canWriteNotes(reader,appointment),false));
test('assigned provider can write notes',()=>assert.ok(rules.canWriteNotes(provider,appointment)));
test('provider with broader read cannot write others notes',()=>assert.equal(rules.canWriteNotes({...doctor,permissions:['appointments.read']},{...appointment,employeeId:4}),false));
test('manager can reschedule pending',()=>assert.ok(rules.canReschedule(manager,appointment)));
test('manager can reschedule confirmed',()=>assert.ok(rules.canReschedule(manager,{...appointment,status:'confirmed'})));
for(const status of ['checked_in','in_service','completed','cancelled','no_show'])test(`cannot reschedule ${status}`,()=>assert.equal(rules.canReschedule(manager,{...appointment,status}),false));
test('provider cannot reschedule',()=>assert.equal(rules.canReschedule(provider,appointment),false));
for(const status of rules.APPOINTMENT_STATUSES)test(`all status edges known for ${status}`,()=>assert.ok(rules.TRANSITIONS[status].every((v)=>rules.APPOINTMENT_STATUSES.includes(v))));
test('pending requires confirmation before check-in',()=>assert.deepEqual(rules.allowedTransitions(manager,appointment),['confirmed','cancelled','no_show']));
test('provider can start checked-in service',()=>assert.deepEqual(rules.allowedTransitions(doctor,{...appointment,status:'checked_in'}),['in_service']));
test('provider can finish in-service appointment',()=>assert.deepEqual(rules.allowedTransitions(doctor,{...appointment,status:'in_service'}),['completed']));
test('provider cannot confirm own pending appointment',()=>assert.deepEqual(rules.allowedTransitions(doctor,appointment),[]));
for(const status of ['completed','cancelled','no_show'])test(`${status} is terminal`,()=>assert.deepEqual(rules.allowedTransitions(manager,{...appointment,status}),[]));
test('status actions cannot cross clinics',()=>assert.deepEqual(rules.allowedTransitions(manager,{...appointment,clinicId:2}),[]));
test('canonical command payload ignores object order and undefined',()=>assert.equal(rules.canonicalJson({z:2,a:{y:3,x:4},nothing:undefined}),rules.canonicalJson({a:{x:4,y:3},z:2})));
test('canonical command keeps array order',()=>assert.notEqual(rules.canonicalJson([1,2]),rules.canonicalJson([2,1])));
test('adjacent reservations do not overlap',()=>assert.equal(rules.overlaps(0,45,45,90),false));
test('partial reservations overlap',()=>assert.equal(rules.overlaps(0,45,30,75),true));
test('contained reservation overlaps',()=>assert.equal(rules.overlaps(0,90,30,45),true));
test('leap day validates',()=>assert.equal(rules.validDate('2028-02-29'),true));
test('impossible day rejected',()=>assert.equal(rules.validDate('2026-02-29'),false));
test('malformed date rejected',()=>assert.equal(rules.validDate('2026-2-1'),false));
test('date shift crosses year boundary',()=>assert.equal(rules.shiftDate('2026-12-31',1),'2027-01-01'));
test('new doctor preset has no all-appointments grant',()=>assert.ok(!permission.ROLE_PRESETS.doctor.some((v)=>v.startsWith('appointments.'))));
test('new provider preset has no all-appointments grant',()=>assert.ok(!permission.ROLE_PRESETS.service_provider.some((v)=>v.startsWith('appointments.'))));
test('provider navigation retains appointments without global read',()=>assert.ok(permission.navFor(doctor).includes('appointments')));
const empty=()=>setup.normalizeWeek({});const hours=(open='09:00',close='17:00')=>Object.fromEntries(setup.DAYS.map((d)=>[d,[{open,close}]]));
const base={date:'2026-10-05',timeZone:'UTC',branchHours:hours(),workingHours:hours(),breaks:empty(),timeOff:[],durationMinutes:45,employeeId:2,requiresRoom:false,roomIds:[],busy:[],now:Date.parse('2026-10-04T00:00:00Z')};
const slots=(more={})=>time.computeSlots({...base,...more});const at=(h,m=0)=>`${base.date}T${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:00.000Z`;
const busy=(employeeId,roomId,start,end)=>({employeeId,roomId,startsAt:start,endsAt:end});
test('15-minute grid returns 30 starts for 8h day and 45min service',()=>assert.equal(slots().length,30));
test('first slot fits opening and service duration',()=>assert.deepEqual(slots()[0],{startsAt:at(9),endsAt:at(9,45),roomId:null}));
test('last slot ends at closing',()=>assert.equal(slots().at(-1).endsAt,at(17)));
test('closed branch yields none',()=>assert.deepEqual(slots({branchHours:empty()}),[]));
test('off-duty employee yields none',()=>assert.deepEqual(slots({workingHours:empty()}),[]));
test('branch and employee hours intersect',()=>{const v=slots({workingHours:hours('10:00','16:00')});assert.equal(v[0].startsAt,at(10));assert.equal(v.at(-1).endsAt,at(16));});
test('service cannot span split shifts',()=>{const split=hours();split.mon=[{open:'09:00',close:'12:00'},{open:'13:00',close:'17:00'}];assert.ok(slots({branchHours:split}).every((v)=>!(v.startsAt<at(13)&&v.endsAt>at(12))));});
test('break excludes intersecting slots but permits adjacent',()=>{const b=empty();b.mon=[{open:'12:00',close:'13:00'}];const v=slots({breaks:b});assert.ok(v.some((s)=>s.endsAt===at(12)));assert.ok(v.some((s)=>s.startsAt===at(13)));assert.ok(v.every((s)=>!(s.startsAt<at(13)&&s.endsAt>at(12))));});
test('UTC time off excludes intersecting appointments',()=>{const v=slots({timeOff:[{startsAt:at(10),endsAt:at(11),note:''}]});assert.ok(v.every((s)=>!(s.startsAt<at(11)&&s.endsAt>at(10))));});
test('all past starts excluded',()=>assert.deepEqual(slots({now:Date.parse(at(17))}),[]));
test('exact current instant is not offered',()=>assert.equal(slots({now:Date.parse(at(9))})[0].startsAt,at(9,15)));
test('employee busy removes overlap regardless of room',()=>assert.ok(slots({busy:[busy(2,4,at(9),at(10))]}).every((s)=>s.startsAt>=at(10))));
test('other employee irrelevant without room requirement',()=>assert.equal(slots({busy:[busy(99,4,at(9),at(10))]}).length,30));
test('required room absent yields no slots',()=>assert.deepEqual(slots({requiresRoom:true}),[]));
test('compatible room deterministic allocation',()=>assert.equal(slots({requiresRoom:true,roomIds:[9,4]})[0].roomId,4));
test('occupied first room falls back to compatible alternative',()=>assert.equal(slots({requiresRoom:true,roomIds:[4,9],busy:[busy(99,4,at(9),at(10))]})[0].roomId,9));
test('all rooms busy suppresses overlapping starts',()=>assert.equal(slots({requiresRoom:true,roomIds:[4,9],busy:[busy(99,4,at(9),at(10)),busy(88,9,at(9),at(10))]})[0].startsAt,at(10)));
test('adjacent employee reservation allowed',()=>assert.equal(slots({busy:[busy(2,null,at(9),at(9,45))]})[0].startsAt,at(9,45)));
test('required room remains reserved for full service interval',()=>assert.ok(slots({requiresRoom:true,roomIds:[4],busy:[busy(99,4,at(10),at(11))]}).every((s)=>!(s.startsAt<at(11)&&s.endsAt>at(10)))));
test('invalid service duration produces none',()=>assert.deepEqual(slots({durationMinutes:0}),[]));
test('too-long service produces none',()=>assert.deepEqual(slots({durationMinutes:1441}),[]));
test('invalid booking date produces none',()=>assert.deepEqual(slots({date:'2026-02-30'}),[]));
test('non-hour duration preserved',()=>assert.equal(Date.parse(slots({durationMinutes:50})[0].endsAt)-Date.parse(at(9)),50*60000));
test('UTC wall conversion round-trip',()=>assert.equal(time.wallConverter('2026-10-05','UTC')(540),Date.parse(at(9))));
for(const zone of ['Asia/Amman','Asia/Kathmandu','Pacific/Kiritimati'])test(`${zone} branch-local slot round-trip`,()=>{const v=slots({timeZone:zone})[0];assert.equal(time.wallTime(v.startsAt,zone),'2026-10-05T09:00');assert.equal(time.wallTime(v.endsAt,zone),'2026-10-05T09:45');});
test('DST spring nonexistent time skipped',()=>assert.equal(time.wallConverter('2026-03-08','America/New_York')(150),null));
test('DST repeated wall time skipped',()=>assert.equal(time.wallConverter('2026-11-01','America/New_York')(90),null));
test('DST transition never stretches real service duration',()=>{for(const date of ['2026-03-08','2026-11-01']){const v=slots({date,timeZone:'America/New_York',branchHours:hours('00:00','05:00'),workingHours:hours('00:00','05:00'),now:0});assert.ok(v.length>0);assert.ok(v.every((s)=>Date.parse(s.endsAt)-Date.parse(s.startsAt)===45*60000));}});
let syntaxFiles=0;const all=[];
function scan(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(['node_modules','.git','dist','migration-baseline'].includes(e.name))continue;const f=path.join(dir,e.name);if(e.isDirectory())scan(f);else if(/\.tsx?$/.test(e.name)&&!e.name.endsWith('.d.ts')){const text=fs.readFileSync(f,'utf8');const source=ts.createSourceFile(f,text,ts.ScriptTarget.Latest,true,e.name.endsWith('.tsx')?ts.ScriptKind.TSX:ts.ScriptKind.TS);assert.equal(source.parseDiagnostics.length,0,`${f}: ${source.parseDiagnostics.map((d)=>ts.flattenDiagnosticMessageText(d.messageText,' ')).join('; ')}`);syntaxFiles++;all.push({f,text,source});}}}
scan(path.join(root,'artifacts'));scan(path.join(root,'lib/db/src'));scan(path.join(root,'scripts/src'));
const lookup=(dict,key)=>key.split('.').reduce((v,k)=>v?.[k],dict);
test('all literal UI translation keys exist in both dictionaries',()=>{for(const {f,source}of all.filter((v)=>v.f.includes('/artifacts/jormall/'))){function walk(node){if(ts.isCallExpression(node)&&ts.isIdentifier(node.expression)&&node.expression.text==='t'&&node.arguments[0]&&ts.isStringLiteral(node.arguments[0])){const key=node.arguments[0].text;for(const dict of [en,ar])assert.equal(typeof lookup(dict,key),'string',`${f}: missing ${key}`);}ts.forEachChild(node,walk);}walk(source);}});
test('all scheduling error codes have English and Arabic copy',()=>{for(const {f,text}of all.filter((v)=>v.f.endsWith('/services/scheduling.ts'))){for(const m of text.matchAll(/(?:conflict|badRequest|notFound)\('([^']+)'\)/g)){assert.equal(typeof en.errors[m[1]],'string',`${f}: ${m[1]}`);assert.equal(typeof ar.errors[m[1]],'string',`${f}: ${m[1]}`);}}});
test('custom scheduling validation messages are localized',()=>{for(const k of ['invalid_date','invalid_date_range','reason_required','notes_language_required','contact_required']){assert.equal(typeof en.errors[k],'string',k);assert.equal(typeof ar.errors[k],'string',k);}});
test('both SQL exclusion declarations and guard wrapper present (source only)',()=>{const sql=fs.readFileSync(path.join(root,'lib/db/sql/scheduling-guards.sql'),'utf8');for(const fragment of ['btree_gist','appointments_employee_no_overlap','appointments_room_no_overlap',"tstzrange(starts_at, ends_at, '[)')", "status <> 'cancelled'"])assert.ok(sql.includes(fragment),fragment);assert.equal((sql.match(/EXCLUDE USING gist/g)||[]).length,2);const pkg=JSON.parse(fs.readFileSync(path.join(root,'lib/db/package.json'),'utf8'));assert.ok(pkg.scripts.push.includes('install-scheduling-guards'));});
test('guard SQL in migration matches runtime installation source',()=>{const sql=fs.readFileSync(path.join(root,'lib/db/sql/scheduling-guards.sql'),'utf8').trim();const migration=fs.readFileSync(path.join(root,'lib/db/migrations/0002_phase3_scheduling.sql'),'utf8');assert.ok(migration.trim().endsWith(sql));});
console.log(JSON.stringify({syntaxFiles,phase3OfflineChecks:checks,result:'passed',limitation:'Pure rules and source checks only; full workspace typecheck, API/PostgreSQL tests, migrations and browser acceptance have not run.'},null,2));
