/** Pure executable rules + explicitly labelled source assertions. NOT database/API/browser acceptance. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const require=createRequire(import.meta.url),ts=require(process.env.TYPESCRIPT_PATH||'typescript');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),cache=new Map();
function load(relative){const file=path.resolve(root,relative);if(cache.has(file))return cache.get(file).exports;
 const out=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
 const module={exports:{}};cache.set(file,module);new Function('exports','module','require',out)(module.exports,module,p=>p.startsWith('.')?load(path.resolve(path.dirname(file),p+'.ts')):require(p));return module.exports;}
const rules=load('artifacts/api-server/src/domain/operations-rules.ts'),time=load('artifacts/api-server/src/domain/scheduling-time.ts');
const en=load('artifacts/jormall/src/lib/i18n/en.ts').en,ar=load('artifacts/jormall/src/lib/i18n/ar.ts').ar;
let executed=0,sourceChecks=0;
function test(name,fn,source=false){fn();source?sourceChecks++:executed++;console.log(`PASS ${source?'SOURCE':'RULE'} ${name}`);}
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
for(const [v,n]of [['0',0n],['1',1000n],['0.001',1n],['12.34',12340n],['-12.345',-12345n],['9000000000',9000000000000n],['-0',0n]])test(`exact decimal parse ${v}`,()=>assert.equal(rules.quantityMilli(v),n));
for(const v of ['1e3','NaN','Infinity',' 1','1 ','01','+1','.1','1.','0.0001','-01','9000000000.001','', '1,5'])test(`reject quantity ${JSON.stringify(v)}`,()=>assert.throws(()=>rules.quantityMilli(v)));
for(const n of [0n,1n,-1n,1000n,-1999n,9000000000000n])test(`decimal roundtrip ${n}`,()=>assert.equal(rules.quantityMilli(rules.quantityString(n)),n));
test('decimal sum is exact, not floating point',()=>assert.equal(rules.quantityString(rules.quantityMilli('0.1')+rules.quantityMilli('0.2')),'0.300'));
test('positive-only consumption excludes zero and negative',()=>{for(const v of ['0','-0.000','-1'])assert.equal(rules.validQuantity(v,true),false);});
test('signed adjustments exclude zero',()=>{assert.equal(rules.validQuantity('0'),false);assert.equal(rules.validQuantity('-0.001'),true);});
test('semantic material normalization sorts and fixes precision',()=>assert.deepEqual(rules.normalizedLines([{itemId:2,quantity:'2'},{itemId:1,quantity:'0.1'}]),[{itemId:1,quantity:'0.100'},{itemId:2,quantity:'2.000'}]));
test('normalization does not mutate caller array',()=>{const a=[{itemId:2,quantity:'2'},{itemId:1,quantity:'1'}];rules.normalizedLines(a);assert.equal(a[0].itemId,2);});
test('duplicate material rejected',()=>assert.throws(()=>rules.normalizedLines([{itemId:1,quantity:'1'},{itemId:1,quantity:'2'}])));
test('negative material rejected',()=>assert.throws(()=>rules.normalizedLines([{itemId:1,quantity:'-1'}])));
test('100 material lines accepted',()=>assert.equal(rules.normalizedLines(Array.from({length:100},(_,i)=>({itemId:i+1,quantity:'1'}))).length,100));
test('101 material lines rejected',()=>assert.throws(()=>rules.normalizedLines(Array.from({length:101},(_,i)=>({itemId:i+1,quantity:'1'})))));
const dt=h=>new Date(`2026-10-05T${h}:00.000Z`),entry={branchId:1,serviceId:2,preferredEmployeeId:null,windowStart:dt('09:00'),windowEnd:dt('12:00')},vacancy={branchId:1,serviceId:2,employeeId:3,startsAt:dt('10:00'),endsAt:dt('10:45')};
test('same service fits whole vacancy',()=>assert.equal(rules.waitingFits(entry,vacancy,45),true));
test('shorter current service may fit',()=>assert.equal(rules.waitingFits(entry,vacancy,30),true));
test('longer service rejected',()=>assert.equal(rules.waitingFits(entry,vacancy,46),false));
test('zero duration rejected',()=>assert.equal(rules.waitingFits(entry,vacancy,0),false));
test('other branch rejected',()=>assert.equal(rules.waitingFits({...entry,branchId:8},vacancy,45),false));
test('other service rejected',()=>assert.equal(rules.waitingFits({...entry,serviceId:8},vacancy,45),false));
test('matching preferred employee accepted',()=>assert.equal(rules.waitingFits({...entry,preferredEmployeeId:3},vacancy,45),true));
test('other preferred employee rejected',()=>assert.equal(rules.waitingFits({...entry,preferredEmployeeId:8},vacancy,45),false));
test('start before requested window rejected',()=>assert.equal(rules.waitingFits({...entry,windowStart:dt('10:15')},vacancy,45),false));
test('finish after requested window rejected',()=>assert.equal(rules.waitingFits({...entry,windowEnd:dt('10:30')},vacancy,45),false));
test('exact requested boundaries accepted',()=>assert.equal(rules.waitingFits({...entry,windowStart:dt('10:00'),windowEnd:dt('10:45')},vacancy,45),true));
test('full preferred day converts to next local midnight',()=>{const c=time.wallConverter('2026-10-05','Asia/Amman');assert.equal(time.wallTime(new Date(c(1440)),'Asia/Amman'),'2026-10-06T00:00');});
const doctor={id:3,clinicId:1,role:'doctor',permissions:['inventory.manage']},appt={clinicId:1,employeeId:3};
test('assigned doctor with stock permission can record actual use',()=>assert.equal(rules.canRecordConsumption(doctor,appt),true));
test('assigned provider with stock permission can record',()=>assert.equal(rules.canRecordConsumption({...doctor,role:'service_provider'},appt),true));
test('other assigned doctor denied',()=>assert.equal(rules.canRecordConsumption({...doctor,id:4},appt),false));
test('global appointment read does not authorize consuming for others',()=>assert.equal(rules.canRecordConsumption({...doctor,id:4,permissions:['inventory.manage','appointments.read']},appt),false));
test('inventory read alone cannot consume',()=>assert.equal(rules.canRecordConsumption({...doctor,permissions:['inventory.read']},appt),false));
test('unprivileged manager denied',()=>assert.equal(rules.canRecordConsumption({...doctor,role:'manager'},appt),false));
test('authorized appointment manager can consume',()=>assert.equal(rules.canRecordConsumption({...doctor,id:4,role:'manager',permissions:['appointments.manage','inventory.manage']},appt),true));
test('manager without inventory permission denied',()=>assert.equal(rules.canRecordConsumption({...doctor,role:'manager',permissions:['appointments.manage']},appt),false));
test('cross-clinic consumption denied',()=>assert.equal(rules.canRecordConsumption({...doctor,clinicId:2},appt),false));
test('platform owner cannot consume even with grants',()=>assert.equal(rules.canRecordConsumption({...doctor,role:'platform_owner',permissions:['appointments.manage','inventory.manage']},appt),false));
for(const unit of rules.INVENTORY_UNITS)test(`unit localized ${unit}`,()=>{assert.equal(typeof en.p4.units[unit],'string');assert.equal(typeof ar.p4.units[unit],'string');});
for(const status of rules.WAITING_STATUSES)test(`waiting status localized ${status}`,()=>{assert.equal(typeof en.p4.statuses[status],'string');assert.equal(typeof ar.p4.statuses[status],'string');});
for(const kind of ['receipt','adjustment','consumption'])test(`movement kind localized ${kind}`,()=>{assert.equal(typeof en.p4.kinds[kind],'string');assert.equal(typeof ar.p4.kinds[kind],'string');});
const wait=read('artifacts/api-server/src/services/waiting-list.ts'),inventory=read('artifacts/api-server/src/services/inventory.ts'),context=read('artifacts/api-server/src/services/operations-context.ts'),schema=read('lib/db/src/schema/operations.ts'),guard=read('lib/db/sql/inventory-guards.sql'),migration=read('lib/db/migrations/0003_phase4_waiting_inventory.sql'),validation=read('artifacts/api-server/src/domain/operations-validation.ts');
test('phase4 error codes have both localized dictionaries',()=>{for(const source of [wait,inventory,context])for(const m of source.matchAll(/(?:conflict|badRequest|notFound)\('([^']+)'\)/g))for(const d of [en,ar])assert.equal(typeof d.errors[m[1]],'string',m[1]);},true);
test('phase4 validation messages localized',()=>{for(const key of ['invalid_quantity','invalid_waiting_window','window_pair_required','confirm_consumption_required','duplicate_inventory_item','consumption_requires_completed'])for(const d of [en,ar])assert.equal(typeof d.errors[key],'string',key);},true);
test('confirmation schema requires explicit true',()=>assert.ok(validation.includes('confirmed:z.literal(true)')),true);
test('stale confirmation returns instead of rolling back decisions',()=>assert.ok(wait.includes("return {error:'waiting_offer_changed',nextOfferId:next?.id??null}")),true);
test('replacement shares booking slot implementation',()=>{assert.ok(wait.includes("from './scheduling-slots'"));assert.ok(wait.includes('await fittingContext(tx,fresh,entry,vacancy)'));},true);
test('queue filters first and sorts by creation then id',()=>{assert.ok(wait.includes("eq(waitingEntriesTable.status,'waiting')"));assert.ok(wait.includes('orderBy(asc(waitingEntriesTable.createdAt),asc(waitingEntriesTable.id))'));},true);
test('next offer not an automatic appointment write',()=>{const f=wait.slice(wait.indexOf('export async function offerNextReplacement'),wait.indexOf('async function expireWaiting'));assert.ok(!f.includes('insert(appointmentsTable)'));assert.ok(f.includes("'suggested'"));},true);
test('auth refreshed before operations idempotency replay',()=>{assert.ok(context.includes('refreshOperatingActor(tx,actor)'));assert.ok(context.indexOf('await authorize(tx,fresh)')<context.indexOf('const replay=await replayOperation'));},true);
test('inventory balance is not a writable model column',()=>{const fields=schema.slice(schema.indexOf('export const inventoryItemsTable'),schema.indexOf('export const inventoryConsumptionsTable'));assert.ok(!/balance\s*:/.test(fields));},true);
test('consumption unique per appointment and line item',()=>{assert.ok(schema.includes("unique('inventory_consumptions_appointment_unique')"));assert.ok(schema.includes("unique('inventory_movements_consumption_item_unique')"));},true);
test('immutable SQL guards cover update/delete/truncate',()=>{for(const table of ['inventory_movements','inventory_consumptions'])assert.ok(guard.includes(`BEFORE UPDATE OR DELETE OR TRUNCATE ON public.${table}`));},true);
test('deferred line-count checks cover header and lines',()=>{assert.equal((guard.match(/DEFERRABLE INITIALLY DEFERRED/g)||[]).length,2);assert.ok(guard.includes('expected <> actual'));},true);
test('database negative stock guard and stable item unit',()=>{assert.ok(guard.includes('balance+NEW.quantity < 0'));assert.ok(guard.includes('NEW.id,NEW.clinic_id,NEW.branch_id,NEW.unit'));},true);
test('all phase4 constraint names represented in migration',()=>{for(const m of schema.matchAll(/(?:unique|uniqueIndex|index|check)\('([^']+)'|name:'([^']+)'/g))assert.ok(migration.includes(m[1]||m[2]),m[1]||m[2]);},true);
test('versioned migration embeds exactly the installed guards',()=>assert.ok(migration.trim().endsWith(guard.trim())),true);
test('development push installs both guard sets',()=>{const pkg=JSON.parse(read('lib/db/package.json'));for(const key of ['push','push-force'])for(const name of ['scheduling','inventory'])assert.ok(pkg.scripts[key].includes(`install-${name}-guards`));},true);
test('service totals derive only from actual movement group',()=>{assert.ok(inventory.includes("eq(inventoryMovementsTable.kind,'consumption')"));assert.ok(inventory.includes('inventoryMovementsTable.unit,branchesTable.id'));},true);
test('completion invokes stock recording in same transaction',()=>{const s=read('artifacts/api-server/src/services/scheduling.ts');assert.ok(s.includes('await recordConsumptionInTx(tx, fresh, after, input.consumption)'));},true);
test('operations routes precede generic scheduling routes',()=>{const s=read('artifacts/api-server/src/routes/index.ts');assert.ok(s.indexOf('router.use(operationsRouter)')<s.indexOf('router.use(schedulingRouter)'));},true);
test('optional assistant remains opt-in if present',()=>{const file=path.join(root,'artifacts/api-server/src/ai/config.ts');if(fs.existsSync(file))assert.ok(fs.readFileSync(file,'utf8').includes("enabled:env.AI_ASSISTANT_ENABLED==='true'"));},true);
console.log(JSON.stringify({result:'passed',phase4RuleChecks:executed,phase4SourceAssertions:sourceChecks,total:executed+sourceChecks,limitation:'These do not execute application dependencies, SQL, migrations, API requests, or a browser.'},null,2));
