/** Real PostgreSQL/Express acceptance suite. Provider HTTP is STUBBED, never live.
 * Requires a migrated disposable database and TEST_DATABASE_DISPOSABLE=1.
 * Leaves synthetic audited records; fixture accounts are deactivated afterwards.
 */
import {randomUUID} from 'node:crypto';
import {beforeEach,afterEach,afterAll,describe,it,expect,vi} from 'vitest';
import {and,eq,inArray,sql} from 'drizzle-orm';
import {db,usersTable,branchesTable,servicesTable,managerOnboardingTable,auditEventsTable} from '@workspace/db';
import {Fixture,agent,login} from './helpers';
import {ROLE_PRESETS} from '../domain/permissions';
import {emptyDraft,type Draft} from '../domain/concierge-core';
const f=new Fixture();let manager:ReturnType<typeof agent>,clinic:number,userId:number,email:string;
const week={mon:[{open:'09:00',close:'17:00'}],tue:[],wed:[],thu:[],fri:[],sat:[],sun:[]};
const none={mon:[],tue:[],wed:[],thu:[],fri:[],sat:[],sun:[]};
const makeDraft=():Draft=>({branches:[{key:'new_branch',existingId:null,name:'Synthetic voice branch',nameLang:'en',timeZone:'UTC',openingHours:week}],services:[{key:'new_service',name:'Synthetic skin service',nameLang:'en',branchKey:'new_branch',durationMinutes:30,price:'20',currency:'JOD',category:'Skin',requiresRoom:false}],rooms:[],staff:[]});
const staff=(mail:string)=>({key:'new_staff',name:'Synthetic staff',nameLang:'en' as const,email:mail,phone:null,jobTitle:null,branchKey:'new_branch',role:'secretary' as const,serviceKeys:['new_service'],workingHours:week,breaks:none});
const post=(path:string,body:unknown,a=manager)=>a.post('/api/concierge'+path).set('X-JorMall-Intent','concierge').send(body as object);
const put=(path:string,body:unknown)=>manager.put('/api/concierge'+path).set('X-JorMall-Intent','concierge').send(body as object);
const get=()=>manager.get('/api/concierge/bootstrap');
const output=(patch:Draft=emptyDraft(),extra:Record<string,unknown>={})=>new Response(JSON.stringify({status:'completed',output:[{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify({reply:'Synthetic draft, not yet saved.',ui:'review',navigation:'none',patch,fileRead:null,fileSummary:null,...extra})}]}],usage:{input_tokens:20,output_tokens:15}}));
function enable(){vi.stubEnv('OPENAI_API_KEY','synthetic-contract-key');}
async function start(){const opened=await post('/start',{language:'ar'});expect(opened.status).toBe(200);const named=await post('/name',{name:'Synthetic manager',language:'ar',revision:opened.body.session.revision});expect(named.status).toBe(200);return named.body;}
async function conversation(){enable();const s=await start();const r=await post('/mode',{mode:'text',revision:s.revision,consent:true});expect(r.status).toBe(200);const [row]=await db.select().from(managerOnboardingTable).where(eq(managerOnboardingTable.userId,userId));await db.update(managerOnboardingTable).set({state:{...row!.state,serviceWizard:false,companyProfile:{name:'Synthetic verified center',summary:'Fixture',found:true,sources:[]}}}).where(eq(managerOnboardingTable.userId,userId));return (await get()).body.session;}
async function save(draft:Draft){const s=await conversation();const r=await put('/draft',{revision:s.revision,draft});expect(r.status).toBe(200);return r.body;}
async function branchCount(){const rows=await db.select({id:branchesTable.id}).from(branchesTable).where(eq(branchesTable.clinicId,clinic));return rows.length;}
describe('Manager voice concierge: tenant safety, drafts and explicit atomic apply',()=>{
 beforeEach(async()=>{
  if(process.env.TEST_DATABASE_DISPOSABLE!=='1')throw new Error('A migrated DISPOSABLE database and TEST_DATABASE_DISPOSABLE=1 are mandatory.');
  vi.stubEnv('CONCIERGE_ENABLED','true');vi.stubEnv('OPENAI_API_KEY','');vi.stubEnv('JORMALL_OPENAI_API_KEY','');
  vi.stubGlobal('fetch',vi.fn(async()=>{throw new Error('Unexpected provider request in non-live test');}));
  clinic=(await f.createClinic()).id;const u=await f.createUser({clinicId:clinic,role:'manager',permissions:ROLE_PRESETS.manager,mustChangePassword:false});userId=u.id;email=u.email;manager=agent();expect((await login(manager,u.email,u.password)).status).toBe(200);
 });
 afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();});
 afterAll(async()=>{if(f.userIds.length)await db.update(usersTable).set({isActive:false}).where(inArray(usersTable.id,f.userIds));});
 it('switches to voice without discarding confirmed identity or collected legacy details',async()=>{const s=await conversation();const d=await put('/draft',{revision:s.revision,draft:makeDraft()});const r=await post('/mode',{revision:d.body.revision,mode:'voice',consent:true});expect(r.status).toBe(200);expect(r.body.companyChecked).toBe(true);expect(r.body.workflow.step).toBe('branches');expect(r.body.draft.branches).toHaveLength(1);expect(fetch).not.toHaveBeenCalled();});
 it('keeps incomplete sections in place and advances only after explicit confirmation',async()=>{let s=await conversation();let r=await post('/step-confirm',{revision:s.revision});expect(r.body.workflow.step).toBe('branches');r=await put('/draft',{revision:r.body.revision,draft:makeDraft()});for(const expected of ['services','rooms','staff','review']){r=await post('/step-confirm',{revision:r.body.revision});expect(r.status).toBe(200);expect(r.body.workflow.step).toBe(expected);}expect(await branchCount()).toBe(0);});
 it('imports sourced names only after confirmation and leaves unknown fields for manual review',async()=>{const s=await conversation();const [row]=await db.select().from(managerOnboardingTable).where(eq(managerOnboardingTable.userId,userId));const details={logoDataUrl:null,colors:['#123456'],website:'https://example.com',branches:[{name:'Public branch',detail:'Fixture address',sourceUrl:'https://example.com'}],services:[{name:'Public facial',detail:'Fixture service',sourceUrl:'https://example.com'}],status:'partial'};await db.update(managerOnboardingTable).set({state:{...row!.state,companyProfile:null,sourceImport:false,companyCandidate:{name:'Synthetic center',summary:'Fixture',found:true,sources:[],details}}}).where(eq(managerOnboardingTable.userId,userId));expect(await branchCount()).toBe(0);const r=await post('/company-confirm',{revision:s.revision,answer:'yes',colors:['#345678']});expect(r.status).toBe(200);expect(r.body.draft.branches[0].openingHours).toBe(null);expect(r.body.draft.services).toHaveLength(0);expect(r.body.serviceSuggestions).toHaveLength(1);expect(r.body.branding.details.colors).toEqual(['#345678']);expect((await manager.get('/api/concierge/review')).body.issues.length).toBeGreaterThan(0);expect(await branchCount()).toBe(0);expect(fetch).not.toHaveBeenCalled();});
 it('confirms only the clinic selected from multiple search choices',async()=>{const s=await conversation();const [row]=await db.select().from(managerOnboardingTable).where(eq(managerOnboardingTable.userId,userId));const first={name:'First center',summary:'North',found:true,sources:[],details:{logoDataUrl:null,colors:[],website:null,branches:[],services:[],status:'partial'}};const second={name:'Second center',summary:'Amman',found:true,sources:[],details:{logoDataUrl:null,colors:[],website:null,branches:[],services:[],status:'partial'}};await db.update(managerOnboardingTable).set({state:{...row!.state,companyProfile:null,companyCandidate:first,companyCandidates:[first,second]}}).where(eq(managerOnboardingTable.userId,userId));const r=await post('/company-confirm',{revision:s.revision,answer:'yes',selectedIndex:1});expect(r.status).toBe(200);expect(r.body.companyProfile.name).toBe('Second center');expect(r.body.companyCandidates).toEqual([]);expect(fetch).not.toHaveBeenCalled();});
 it('rejects unsafe URL schemes, embedded credentials and too many import links before provider calls',async()=>{const s=await conversation();for(const urls of [['http://example.com'],['https://user:password@example.com'],['javascript:alert(1)'],Array(6).fill('https://example.com')]){expect((await post('/import-links',{revision:s.revision,urls})).status).toBe(400);}expect(fetch).not.toHaveBeenCalled();});
 it('requires a signed-in account',async()=>{expect((await agent().get('/api/concierge/bootstrap')).status).toBe(401);});
 it('rejects doctors and accounts awaiting password change',async()=>{for(const role of ['doctor','manager'] as const){const u=await f.createUser({clinicId:clinic,role,permissions:ROLE_PRESETS[role],mustChangePassword:role==='manager'}),a=agent();await login(a,u.email,u.password);expect((await a.get('/api/concierge/bootstrap')).status).toBe(403);}});
 it('can be disabled without removing existing staff help',async()=>{vi.stubEnv('CONCIERGE_ENABLED','false');expect((await get()).status).toBe(404);expect((await manager.get('/api/assistant/bootstrap?language=en')).status).toBe(200);});
 it('rejects missing intent and cross-site mutations',async()=>{expect((await manager.post('/api/concierge/start').send({language:'ar'})).status).toBe(403);expect((await post('/start',{language:'ar'}).set('sec-fetch-site','cross-site')).status).toBe(403);});
 it('shows configuration, not a claimed live connection; manual mode works without keys',async()=>{const b=await get();expect(b.status).toBe(200);expect(b.body.capabilities.voice).toBe(false);expect(b.body.capabilities.configuredOnly).toBe(true);expect(b.headers['cache-control']).toContain('no-store');const s=await start();const r=await post('/mode',{revision:s.revision,mode:'manual',consent:false});expect(r.status).toBe(200);expect(r.body.stage).toBe('manual');expect(fetch).not.toHaveBeenCalled();});
 it('starts branch-first onboarding when no branch exists',async()=>{const s=await start();expect(s.serviceWizard).toBe(false);enable();const r=await post('/mode',{revision:s.revision,mode:'text',consent:true});expect(r.status).toBe(200);expect(r.body.workflow.step).toBe('company');expect(r.body.draft.branches).toHaveLength(0);});
 it('finishes named branches one at a time before moving to services',async()=>{enable();const s=await start();const opened=await post('/mode',{revision:s.revision,mode:'text',consent:true});const [row]=await db.select().from(managerOnboardingTable).where(eq(managerOnboardingTable.userId,userId));await db.update(managerOnboardingTable).set({state:{...row!.state,companyProfile:{name:'Synthetic clinic',summary:'Fixture',found:true,sources:[]}}}).where(eq(managerOnboardingTable.userId,userId));const first={key:'branch_first',existingId:null,name:'First branch',nameLang:'en' as const,timeZone:'UTC',openingHours:week};const second={key:'branch_second',existingId:null,name:'Second branch',nameLang:'en' as const,timeZone:null,openingHours:null};const partial=await put('/draft',{revision:opened.body.revision,draft:{...emptyDraft(),branches:[first,second]}});expect(partial.status).toBe(200);expect(partial.body.workflow.step).toBe('branches');expect(partial.body.workflow.focus.key).toBe('branch_second');const waiting=await post('/step-confirm',{revision:partial.body.revision});expect(waiting.body.workflow.step).toBe('branches');const complete=await put('/draft',{revision:waiting.body.revision,draft:{...emptyDraft(),branches:[first,{...second,timeZone:'UTC',openingHours:week}]}});expect(complete.status).toBe(200);const next=await post('/step-confirm',{revision:complete.body.revision});expect(next.body.workflow.step).toBe('services');});
 it('saves the preferred name without overwriting the account name',async()=>{const before=(await db.select().from(usersTable).where(eq(usersTable.id,userId)))[0]!;const s=await start();expect(s.stage).toBe('choice');expect(s.preferredName).toBe('Synthetic manager');const after=(await db.select().from(usersTable).where(eq(usersTable.id,userId)))[0]!;expect(after.name).toBe(before.name);});
 it('rejects cloud mode without consent',async()=>{enable();const s=await start();const r=await post('/mode',{revision:s.revision,mode:'voice',consent:false});expect(r.status).toBe(403);expect(fetch).not.toHaveBeenCalled();});
 it('rejects caller-supplied clinic IDs and executable fields',async()=>{const s=await conversation();for(const extra of [{clinicId:clinic+1},{sql:'DROP TABLE users'},{confirmed:true}]){const r=await post('/turn',{revision:s.revision,requestId:randomUUID(),text:'hello',...extra});expect(r.status).toBe(400);}expect(fetch).not.toHaveBeenCalled();});
 it('collects model output only as a persisted draft',async()=>{const s=await conversation();vi.stubGlobal('fetch',vi.fn(async()=>output(makeDraft())));const r=await post('/turn',{revision:s.revision,requestId:randomUUID(),text:'Synthetic setup'});expect(r.status).toBe(200);expect(r.body.draft.branches).toHaveLength(1);expect(await branchCount()).toBe(0);expect((await get()).body.session.draft.services).toHaveLength(1);});
 it('replays an identical successful turn without another provider charge',async()=>{const s=await conversation(),transport=vi.fn(async()=>output(makeDraft()));vi.stubGlobal('fetch',transport);const body={revision:s.revision,requestId:randomUUID(),text:'Synthetic setup'};const a=await post('/turn',body),b=await post('/turn',body);expect(a.status).toBe(200);expect(b.status).toBe(200);expect(b.body.revision).toBe(a.body.revision);expect(transport).toHaveBeenCalledTimes(1);});
 it('rejects stale draft edits',async()=>{const s=await conversation();expect((await put('/draft',{revision:s.revision,draft:makeDraft()})).status).toBe(200);expect((await put('/draft',{revision:s.revision,draft:emptyDraft()})).status).toBe(409);});
 it('does not accept a forged file-read success without an attachment',async()=>{const s=await conversation();vi.stubGlobal('fetch',vi.fn(async()=>output(emptyDraft(),{fileRead:true,fileSummary:'invented'})));const r=await post('/turn',{revision:s.revision,requestId:randomUUID(),text:'hello'});expect(r.status).toBe(503);expect((await get()).body.session.uploads).toHaveLength(0);});
 it('rejects malformed or action-like model output without business writes',async()=>{const s=await conversation();vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({status:'completed',output:[{type:'function_call',name:'create_user'}]}))));expect((await post('/turn',{revision:s.revision,requestId:randomUUID(),text:'hello'})).status).toBe(503);expect(await branchCount()).toBe(0);});
 it('cannot reference a foreign branch',async()=>{const other=(await f.createClinic()).id;const [b]=await db.insert(branchesTable).values({clinicId:other,name:'Foreign branch',timeZone:'UTC',openingHours:week}).returning();const s=await conversation(),draft=makeDraft();draft.branches[0]!.existingId=b!.id;expect((await put('/draft',{revision:s.revision,draft})).status).toBe(403);expect(await branchCount()).toBe(0);});
 it('cannot provision platform owner/manager or smuggle passwords into drafts',async()=>{const s=await conversation();for(const person of [{...staff('x@example.test'),role:'platform_owner'},{...staff('x@example.test'),role:'manager'},{...staff('x@example.test'),initialPassword:'private'}]){expect((await put('/draft',{revision:s.revision,draft:{...makeDraft(),staff:[person]}})).status).toBe(400);}});
 it('requires confirmed=true and complete reviewed data',async()=>{const s=await save(makeDraft());expect((await post('/apply',{revision:s.revision,confirmed:false,staff:[]})).status).toBe(400);expect(await branchCount()).toBe(0);});
 it('applies branches/services atomically and safely replays a duplicate confirmation',async()=>{const s=await save(makeDraft()),body={revision:s.revision,confirmed:true,staff:[]};const a=await post('/apply',body),b=await post('/apply',body);expect(a.status).toBe(200);expect(b.status).toBe(200);expect(b.body.applied).toEqual(a.body.applied);expect(await branchCount()).toBe(1);expect((await db.select().from(servicesTable).where(eq(servicesTable.clinicId,clinic)))).toHaveLength(1);expect(a.body.draft).toEqual(emptyDraft());});
 it('concurrent confirmations do not create duplicate records',async()=>{const s=await save(makeDraft()),body={revision:s.revision,confirmed:true,staff:[]};const [a,b]=await Promise.all([post('/apply',body),post('/apply',body)]);expect(a.status).toBe(200);expect(b.status).toBe(200);expect(await branchCount()).toBe(1);});
 it('rolls back earlier creates if a staff account conflicts',async()=>{const draft=makeDraft();draft.staff=[staff(email)];const s=await save(draft);const r=await post('/apply',{revision:s.revision,confirmed:true,staff:[{key:'new_staff',initialPassword:'Synthetic-long-password',permissions:[]}]});expect(r.status).toBe(409);expect(await branchCount()).toBe(0);expect((await get()).body.session.stage).toBe('conversation');});
 it('creates staff using hashing, forced password change and exact reviewed permissions',async()=>{const draft=makeDraft();draft.staff=[staff(`synthetic-${randomUUID()}@example.test`)];const s=await save(draft);const r=await post('/apply',{revision:s.revision,confirmed:true,staff:[{key:'new_staff',initialPassword:'Synthetic-long-password',permissions:['appointments.read']}]});expect(r.status).toBe(200);const [u]=await db.select().from(usersTable).where(eq(usersTable.id,r.body.applied.staff[0]));f.userIds.push(u!.id);expect(u!.passwordHash).not.toContain('Synthetic-long-password');expect(u!.mustChangePassword).toBe(true);expect(u!.permissions).toEqual(['appointments.read']);const [saved]=await db.select().from(managerOnboardingTable).where(eq(managerOnboardingTable.userId,userId));expect(JSON.stringify(saved)).not.toContain('Synthetic-long-password');const audit=await db.select().from(auditEventsTable).where(eq(auditEventsTable.clinicId,clinic));expect(JSON.stringify(audit)).not.toContain('Synthetic-long-password');});
 it('revocation during model latency prevents output and later draft reads; explicit reopen resets access',async()=>{const s=await conversation();vi.stubGlobal('fetch',vi.fn(async()=>{await db.update(usersTable).set({permissions:['settings.manage']}).where(eq(usersTable.id,userId));return output(makeDraft());}));expect((await post('/turn',{revision:s.revision,requestId:randomUUID(),text:'hello'})).status).toBe(403);expect((await get()).status).toBe(403);const r=await post('/start',{language:'ar',reopen:true});expect(r.status).toBe(200);expect(r.body.session.draft).toEqual(emptyDraft());expect(r.body.session.consented).toBe(false);});
 it('rejects arbitrary TTS text or an unknown utterance ID',async()=>{await conversation();expect((await post('/speech',{text:'arbitrary'})).status).toBe(400);expect((await post('/speech',{utteranceId:'unknown'})).status).toBe(404);expect(fetch).not.toHaveBeenCalled();});
 it('streams Arabic OpenAI speech without exposing the project key',async()=>{enable();await start();vi.stubGlobal('fetch',vi.fn(async(url:string|URL,init?:RequestInit)=>{expect(String(url)).toBe('https://api.openai.com/v1/audio/speech');expect(init?.headers).toMatchObject({Authorization:'Bearer synthetic-contract-key'});const body=JSON.parse(init!.body as string);expect(body).toMatchObject({model:'gpt-4o-mini-tts',voice:'marin',response_format:'mp3'});return new Response(new Uint8Array([1,2,3]),{headers:{'content-type':'audio/mpeg'}});}));const r=await post('/speech',{utteranceId:'stage:choice'});expect(r.status).toBe(200);expect(r.headers['content-type']).toContain('audio/mpeg');expect(r.body).toEqual(Buffer.from([1,2,3]));expect(JSON.stringify(r.headers)).not.toContain('synthetic-contract-key');});
 it('returns OpenAI SDP answer, never the project key',async()=>{await conversation();vi.stubGlobal('fetch',vi.fn(async(url:string|URL,init?:RequestInit)=>{expect(String(url)).toBe('https://api.openai.com/v1/realtime/calls');expect(init?.headers).toMatchObject({Authorization:'Bearer synthetic-contract-key'});return new Response('v=0\r\no=- 2 2 IN IP4 127.0.0.1\r\n');}));const r=await manager.post('/api/concierge/realtime-offer').set('X-JorMall-Intent','concierge').set('Content-Type','application/sdp').send('v=0\r\no=- 1 1 IN IP4 127.0.0.1\r\n');expect(r.status).toBe(200);expect(r.text).toContain('v=0');expect(r.text).not.toContain('synthetic-contract-key');});
 it('refuses non-PDF bytes labelled as PDF before calling a provider',async()=>{const s=await conversation();const r=await manager.post('/api/concierge/upload').set('X-JorMall-Intent','concierge').set('X-Draft-Revision',String(s.revision)).set('X-Request-Id',randomUUID()).set('X-File-Name','synthetic.pdf').set('Content-Type','application/octet-stream').send(Buffer.from('not a pdf'));expect(r.status).toBe(400);expect(fetch).not.toHaveBeenCalled();});
});
