import {randomUUID} from 'node:crypto';
import {beforeAll,describe,expect,it} from 'vitest';
import {and,eq} from 'drizzle-orm';
import {db,branchesTable,servicesTable,inventoryItemsTable,serviceCostProfilesTable,serviceMaterialCostsTable} from '@workspace/db';
import {ROLE_PRESETS} from '../domain/permissions';
import {Fixture,agent,login} from './helpers';
const f=new Fixture(),manager=agent(),reader=agent();let clinicId:number,a:number,b:number,global:number,local:number,foreign:number,itemA:number,itemB:number;
beforeAll(async()=>{
 if(process.env.TEST_DATABASE_DISPOSABLE!=='1')throw Error('Requires disposable test database');
 clinicId=(await f.createClinic()).id;const other=(await f.createClinic()).id;
 const user=await f.createUser({clinicId,role:'manager',permissions:ROLE_PRESETS.manager});await login(manager,user.email,user.password);
 const readUser=await f.createUser({clinicId,role:'other_staff',permissions:['inventory.read']});await login(reader,readUser.email,readUser.password);
 const branches=await db.insert(branchesTable).values([{clinicId,name:'A',openingHours:{mon:[],tue:[],wed:[],thu:[],fri:[],sat:[],sun:[]}},{clinicId,name:'B',openingHours:{mon:[],tue:[],wed:[],thu:[],fri:[],sat:[],sun:[]}}]).returning();a=branches[0]!.id;b=branches[1]!.id;
 const services=await db.insert(servicesTable).values([{clinicId,name:'Shared service',durationMinutes:30,price:'50',category:'Skin',requiresRoom:false},{clinicId,branchId:a,name:'A service',durationMinutes:30,price:'50',category:'Skin',requiresRoom:false},{clinicId:other,name:'Other clinic service',durationMinutes:30,price:'50',category:'Skin',requiresRoom:false}]).returning();global=services[0]!.id;local=services[1]!.id;foreign=services[2]!.id;
});
const create=(serviceUsage:unknown,overrides={})=>manager.post('/api/clinic/inventory/items').send({name:'Usage fixture',nameLang:'en',unit:'ml',branchId:a,availability:'all',branchStocks:[{branchId:a,quantity:'20'},{branchId:b,quantity:'10'}],serviceUsage,idempotencyKey:randomUUID(),...overrides});
describe('inventory service usage estimates',()=>{
 it('lists active services within the same clinic',async()=>{const r=await manager.get('/api/clinic/inventory/catalog');expect(r.status).toBe(200);expect(r.body.services.map((s:{id:number})=>s.id)).toEqual(expect.arrayContaining([global,local]));expect(r.body.services.some((s:{id:number})=>s.id===foreign)).toBe(false);});
 it('creates exact per-session recipes only at eligible branches without consuming stock',async()=>{const r=await create([{serviceId:global,quantity:'0.333'},{serviceId:local,quantity:'2'}]);expect(r.status).toBe(201);itemA=r.body.id;const d=await manager.get(`/api/clinic/inventory/items/${itemA}`);itemB=d.body.branches.find((row:{id:number})=>row.id===b).itemId;expect(d.body.serviceUsage).toEqual(expect.arrayContaining([expect.objectContaining({serviceId:global,quantity:'0.333'}),expect.objectContaining({serviceId:local,quantity:'2.000'})]));expect(d.body.balance).toBe('20.000');expect(d.body.totalQuantity).toBe('30.000');const other=await manager.get(`/api/clinic/inventory/items/${itemB}`);expect(other.body.serviceUsage).toEqual([expect.objectContaining({serviceId:global,quantity:'0.333'})]);});
 it('updates one branch and preserves overhead and other branch recipes',async()=>{await db.update(serviceCostProfilesTable).set({overhead:'7'}).where(and(eq(serviceCostProfilesTable.clinicId,clinicId),eq(serviceCostProfilesTable.serviceId,global),eq(serviceCostProfilesTable.branchId,a)));expect((await manager.patch(`/api/clinic/inventory/items/${itemA}`).send({extra:{},serviceUsage:[{serviceId:global,quantity:'1.125'}]})).status).toBe(200);expect((await manager.get(`/api/clinic/inventory/items/${itemA}`)).body.serviceUsage).toEqual([expect.objectContaining({serviceId:global,quantity:'1.125'})]);expect((await manager.get(`/api/clinic/inventory/items/${itemB}`)).body.serviceUsage[0].quantity).toBe('0.333');const [profile]=await db.select().from(serviceCostProfilesTable).where(and(eq(serviceCostProfilesTable.clinicId,clinicId),eq(serviceCostProfilesTable.serviceId,global),eq(serviceCostProfilesTable.branchId,a)));expect(profile!.overhead).toBe('7.000');});
 it('rolls back foreign or incompatible service assignments atomically',async()=>{const before=await db.select().from(inventoryItemsTable).where(eq(inventoryItemsTable.clinicId,clinicId));for(const serviceUsage of [[{serviceId:foreign,quantity:'1'}],[{serviceId:local,quantity:'1'}]]){const r=await create(serviceUsage,{branchId:b,availability:'selected',branchIds:[b],branchStocks:[{branchId:b,quantity:'10'}]});expect(r.status).toBe(400);expect(r.body.error).toBe('inventory_service_invalid');}expect((await db.select().from(inventoryItemsTable).where(eq(inventoryItemsTable.clinicId,clinicId))).length).toBe(before.length);expect((await manager.patch(`/api/clinic/inventory/items/${itemA}`).send({extra:{},serviceUsage:[{serviceId:foreign,quantity:'1'}]})).status).toBe(400);expect((await manager.get(`/api/clinic/inventory/items/${itemA}`)).body.serviceUsage[0].quantity).toBe('1.125');});
 it('rejects duplicate, empty, negative, zero or over-precision quantities',async()=>{for(const quantity of ['', '-1','0','1.0001'])expect((await create([{serviceId:global,quantity}])).status).toBe(400);expect((await create([{serviceId:global,quantity:'1'},{serviceId:global,quantity:'2'}])).status).toBe(400);});
 it('enforces management permission and allows clearing without changing stock',async()=>{expect((await reader.patch(`/api/clinic/inventory/items/${itemA}`).send({extra:{},serviceUsage:[]})).status).toBe(403);expect((await manager.patch(`/api/clinic/inventory/items/${itemA}`).send({extra:{},serviceUsage:[]})).status).toBe(200);const d=await manager.get(`/api/clinic/inventory/items/${itemA}`);expect(d.body.serviceUsage).toEqual([]);expect(d.body.balance).toBe('20.000');expect((await db.select().from(serviceMaterialCostsTable).where(eq(serviceMaterialCostsTable.itemId,itemB))).length).toBe(1);});
});
