import {describe,it,expect} from 'vitest';
import { staffWorksAt,staffScheduleAt,staffScheduleIssue } from '../domain/staff-branches';
import { normalizeWeek } from '../domain/setup-rules';
import { computeSlots,wallTime } from '../domain/scheduling-time';
import { archiveDraftBranch } from '../domain/archive-draft-branch';
import { emptyDraft } from '../domain/concierge-core';
const hours=(open:string,close:string,day='mon')=>normalizeWeek({[day]:[{open,close}]}),empty=normalizeWeek({});
const shift=(branchId:number,open:string,close:string,day='mon')=>({branchId,workingHours:hours(open,close,day),breaks:empty});
const branches=[{id:1,timeZone:'Asia/Amman'},{id:2,timeZone:'Asia/Amman'}];
describe('staff schedules across branches',()=>{
 it('rejects overlapping work even when a break would hide part of the overlap',()=>{const a=shift(1,'09:00','12:00');a.breaks=hours('11:00','12:00');expect(staffScheduleIssue([a,shift(2,'11:00','15:00')],branches)).toBe('staff_branch_hours_overlap');});
 it('allows adjacent shifts and different working days',()=>{expect(staffScheduleIssue([shift(1,'09:00','12:00'),shift(2,'12:00','17:00')],branches)).toBeNull();expect(staffScheduleIssue([shift(1,'09:00','12:00'),shift(2,'09:00','12:00','tue')],branches)).toBeNull();});
 it('compares actual time across time zones, including seasonal changes',()=>{expect(staffScheduleIssue([shift(1,'09:00','10:00'),shift(2,'06:00','07:00')],[branches[0]!,{id:2,timeZone:'UTC'}])).toBe('staff_branch_hours_overlap');expect(staffScheduleIssue([shift(1,'09:00','10:00'),shift(2,'01:00','02:00')],[branches[0]!,{id:2,timeZone:'America/New_York'}],Date.parse('2026-10-01'))).toBe('staff_branch_hours_overlap');});
 it('requires a unique valid branch and explicit working days for each assignment',()=>{expect(staffScheduleIssue([shift(1,'09:00','10:00'),shift(1,'12:00','13:00')],branches)).toBe('duplicate_branch_schedule');expect(staffScheduleIssue([{branchId:1,workingHours:empty,breaks:empty}],branches)).toBe('staff_branch_hours_required');expect(staffScheduleIssue([shift(3,'09:00','10:00')],branches)).toBe('invalid_reference');});
 it('does not drop a shift when its boundary falls in a repeated DST hour',()=>{expect(staffScheduleIssue([shift(1,'07:00','08:00','sun'),shift(2,'01:00','03:00','sun')],[{id:1,timeZone:'UTC'},{id:2,timeZone:'America/New_York'}],Date.parse('2026-10-01'))).toBe('staff_branch_hours_overlap');});
 it('uses only the selected branch schedule and keeps legacy single-branch hours readable',()=>{const employee={branchId:null,branchSchedules:[shift(1,'09:00','12:00'),shift(2,'13:00','17:00')],workingHours:empty,breaks:empty};expect(staffWorksAt(employee,3)).toBe(false);expect(staffWorksAt(employee,2)).toBe(true);expect(staffScheduleAt(employee,2).workingHours).toEqual(hours('13:00','17:00'));expect(staffWorksAt({branchId:1},2)).toBe(false);});
 it.each([{branchClose:'17:00',providerClose:'12:00',end:'12:00'},{branchClose:'17:00',providerClose:'18:00',end:'17:00'}])('offers a final full appointment ending at $end',({branchClose,providerClose,end})=>{const slots=computeSlots({date:'2026-10-05',timeZone:'Asia/Amman',branchHours:hours('09:00',branchClose),workingHours:hours('09:00',providerClose),breaks:empty,timeOff:[],durationMinutes:45,employeeId:1,requiresRoom:false,roomIds:[],busy:[],now:Date.parse('2026-10-01')});expect(wallTime(slots.at(-1)!.endsAt,'Asia/Amman').slice(11)).toBe(end);expect(slots.every(s=>wallTime(s.endsAt,'Asia/Amman').slice(11)<=end)).toBe(true);});
 it('archives a draft branch and its records while preserving other staff assignments',()=>{const draft=emptyDraft();draft.branches=[{key:'branch_a',name:'A',existingId:null,nameLang:'en',timeZone:'Asia/Amman',openingHours:hours('09:00','17:00')},{key:'branch_b',name:'B',existingId:null,nameLang:'en',timeZone:'Asia/Amman',openingHours:hours('09:00','17:00')}];draft.staff=[{key:'staff_a',name:'Doctor',nameLang:'en',email:'doctor@example.test',phone:null,jobTitle:null,role:'doctor',branchKey:null,serviceKeys:[],workingHours:empty,breaks:empty,branchSchedules:[{branchKey:'branch_a',workingHours:hours('09:00','12:00'),breaks:empty},{branchKey:'branch_b',workingHours:hours('13:00','17:00'),breaks:empty}]}];const result=archiveDraftBranch(draft,'branch_a')!;expect(result.draft.branches).toHaveLength(1);expect(result.draft.staff[0]!.branchSchedules).toHaveLength(1);expect(result.snapshot.staff[0]!.branchSchedules).toHaveLength(2);expect(draft.branches).toHaveLength(2);});
});
